export type DonrussInsertsEntry = {
  number: string;
  name: string;
  team?: string;
  section: string;
};

export const DONRUSS_2025_INSERTS: DonrussInsertsEntry[] = [
  { number: "1", name: "Lamar Jackson", team: "Baltimore Ravens", section: "Action All-Pros" },
  { number: "2", name: "Saquon Barkley", team: "Philadelphia Eagles", section: "Action All-Pros" },
  { number: "3", name: "Justin Jefferson", team: "Minnesota Vikings", section: "Action All-Pros" },
  { number: "4", name: "Ja'Marr Chase", team: "Cincinnati Bengals", section: "Action All-Pros" },
  { number: "5", name: "Amon-Ra St. Brown", team: "Detroit Lions", section: "Action All-Pros" },
  { number: "6", name: "Brock Bowers", team: "Las Vegas Raiders", section: "Action All-Pros" },
  { number: "7", name: "Myles Garrett", team: "Cleveland Browns", section: "Action All-Pros" },
  { number: "8", name: "Trey Hendrickson", team: "Cincinnati Bengals", section: "Action All-Pros" },
  { number: "9", name: "Fred Warner", team: "San Francisco 49ers", section: "Action All-Pros" },
  { number: "10", name: "Xavier McKinney", team: "Green Bay Packers", section: "Action All-Pros" },
  { number: "11", name: "Josh Allen", team: "Buffalo Bills", section: "Action All-Pros" },
  { number: "12", name: "Derrick Henry", team: "Baltimore Ravens", section: "Action All-Pros" },
  { number: "13", name: "Terry McLaurin", team: "Washington Commanders", section: "Action All-Pros" },
  { number: "14", name: "CeeDee Lamb", team: "Dallas Cowboys", section: "Action All-Pros" },
  { number: "15", name: "A.J. Brown", team: "Philadelphia Eagles", section: "Action All-Pros" },
  { number: "16", name: "George Kittle", team: "San Francisco 49ers", section: "Action All-Pros" },
  { number: "17", name: "Nik Bonitto", team: "Denver Broncos", section: "Action All-Pros" },
  { number: "18", name: "Andrew Van Ginkel", team: "Minnesota Vikings", section: "Action All-Pros" },
  { number: "19", name: "Christian Gonzalez", team: "New England Patriots", section: "Action All-Pros" },
  { number: "20", name: "Brandon Aubrey", team: "Dallas Cowboys", section: "Action All-Pros" },
  { number: "1", name: "Deion Sanders", team: "Dallas Cowboys", section: "All-Time Gridiron Kings" },
  { number: "2", name: "Aaron Donald", team: "Los Angeles Rams", section: "All-Time Gridiron Kings" },
  { number: "3", name: "Brian Dawkins", team: "Philadelphia Eagles", section: "All-Time Gridiron Kings" },
  { number: "4", name: "Charles Woodson", team: "Green Bay Packers", section: "All-Time Gridiron Kings" },
  { number: "5", name: "Devin Hester", team: "Chicago Bears", section: "All-Time Gridiron Kings" },
  { number: "6", name: "Emmitt Smith", team: "Dallas Cowboys", section: "All-Time Gridiron Kings" },
  { number: "7", name: "Eli Manning", team: "New York Giants", section: "All-Time Gridiron Kings" },
  { number: "8", name: "Eric Dickerson", team: "Los Angeles Rams", section: "All-Time Gridiron Kings" },
  { number: "9", name: "John Elway", team: "Denver Broncos", section: "All-Time Gridiron Kings" },
  { number: "10", name: "Mike Alstott", team: "Tampa Bay Buccaneers", section: "All-Time Gridiron Kings" },
  { number: "11", name: "Ricky Williams", team: "Miami Dolphins", section: "All-Time Gridiron Kings" },
  { number: "12", name: "Randy Moss", team: "Minnesota Vikings", section: "All-Time Gridiron Kings" },
  { number: "13", name: "Larry Fitzgerald", team: "Arizona Cardinals", section: "All-Time Gridiron Kings" },
  { number: "14", name: "Calvin Johnson", team: "Detroit Lions", section: "All-Time Gridiron Kings" },
  { number: "15", name: "Peyton Manning", team: "Indianapolis Colts", section: "All-Time Gridiron Kings" },
  { number: "1", name: "Michael Penix Jr.", team: "Atlanta Falcons", section: "Best of Instant" },
  { number: "2", name: "Terry McLaurin", team: "Washington Commanders", section: "Best of Instant" },
  { number: "3", name: "Bryce Young", team: "Carolina Panthers", section: "Best of Instant" },
  { number: "4", name: "C.J. Stroud", team: "Houston Texans", section: "Best of Instant" },
  { number: "5", name: "Jayden Daniels", team: "Washington Commanders", section: "Best of Instant" },
  { number: "6", name: "Bo Nix", team: "Denver Broncos", section: "Best of Instant" },
  { number: "7", name: "Saquon Barkley", team: "Philadelphia Eagles", section: "Best of Instant" },
  { number: "8", name: "Caleb Williams", team: "Chicago Bears", section: "Best of Instant" },
  { number: "9", name: "Alvin Kamara", team: "New Orleans Saints", section: "Best of Instant" },
  { number: "10", name: "Malik Nabers", team: "New York Giants", section: "Best of Instant" },
  { number: "11", name: "Rome Odunze", team: "Chicago Bears", section: "Best of Instant" },
  { number: "12", name: "Xavier Legette", team: "Carolina Panthers", section: "Best of Instant" },
  { number: "13", name: "Bucky Irving", team: "Tampa Bay Buccaneers", section: "Best of Instant" },
  { number: "14", name: "Jordan Love", team: "Green Bay Packers", section: "Best of Instant" },
  { number: "15", name: "Troy Franklin", team: "Denver Broncos", section: "Best of Instant" },
  { number: "16", name: "Derrick Henry", team: "Baltimore Ravens", section: "Best of Instant" },
  { number: "17", name: "Jake Bates", team: "Detroit Lions", section: "Best of Instant" },
  { number: "18", name: "Ladd McConkey", team: "Los Angeles Chargers", section: "Best of Instant" },
  { number: "19", name: "Keon Coleman", team: "Buffalo Bills", section: "Best of Instant" },
  { number: "20", name: "Garrett Wilson", team: "New York Jets", section: "Best of Instant" },
  { number: "21", name: "Joe Burrow", team: "Cincinnati Bengals", section: "Best of Instant" },
  { number: "22", name: "Tee Higgins", team: "Cincinnati Bengals", section: "Best of Instant" },
  { number: "23", name: "Lamar Jackson", team: "Baltimore Ravens", section: "Best of Instant" },
  { number: "24", name: "Joe Milton III", team: "New England Patriots", section: "Best of Instant" },
  { number: "25", name: "Patrick Mahomes II", team: "Kansas City Chiefs", section: "Best of Instant" },
  { number: "26", name: "Will Shipley", team: "Philadelphia Eagles", section: "Best of Instant" },
  { number: "27", name: "Jalen Hurts", team: "Philadelphia Eagles", section: "Best of Instant" },
  { number: "1", name: "Shedeur Sanders", team: "Cleveland Browns", section: "Bomb Squad" },
  { number: "2", name: "J.J. McCarthy", team: "Minnesota Vikings", section: "Bomb Squad" },
  { number: "3", name: "Jalen Hurts", team: "Philadelphia Eagles", section: "Bomb Squad" },
  { number: "4", name: "DK Metcalf", team: "Pittsburgh Steelers", section: "Bomb Squad" },
  { number: "5", name: "Justin Herbert", team: "Los Angeles Chargers", section: "Bomb Squad" },
  { number: "6", name: "Zay Flowers", team: "Baltimore Ravens", section: "Bomb Squad" },
  { number: "7", name: "Travis Hunter", team: "Jacksonville Jaguars", section: "Bomb Squad" },
  { number: "8", name: "Will Howard", team: "Pittsburgh Steelers", section: "Bomb Squad" },
  { number: "9", name: "Tyler Warren", team: "Indianapolis Colts", section: "Bomb Squad" },
  { number: "10", name: "Nico Collins", team: "Houston Texans", section: "Bomb Squad" },
  { number: "11", name: "Ladd McConkey", team: "Los Angeles Chargers", section: "Bomb Squad" },
  { number: "12", name: "Tyler Shough", team: "New Orleans Saints", section: "Bomb Squad" },
  { number: "13", name: "Rome Odunze", team: "Chicago Bears", section: "Bomb Squad" },
  { number: "14", name: "Jordan Addison", team: "Minnesota Vikings", section: "Bomb Squad" },
  { number: "15", name: "Jalen Milroe", team: "Seattle Seahawks", section: "Bomb Squad" },
  { number: "16", name: "Tetairoa McMillan", team: "Carolina Panthers", section: "Bomb Squad" },
  { number: "17", name: "Sam Darnold", team: "Seattle Seahawks", section: "Bomb Squad" },
  { number: "18", name: "Jack Bech", team: "Las Vegas Raiders", section: "Bomb Squad" },
  { number: "19", name: "Cam Ward", team: "Tennessee Titans", section: "Bomb Squad" },
  { number: "20", name: "Matthew Golden", team: "Green Bay Packers", section: "Bomb Squad" },
  { number: "21", name: "Caleb Williams", team: "Chicago Bears", section: "Bomb Squad" },
  { number: "22", name: "Brock Purdy", team: "San Francisco 49ers", section: "Bomb Squad" },
  { number: "23", name: "Dillon Gabriel", team: "Cleveland Browns", section: "Bomb Squad" },
  { number: "24", name: "Bryce Young", team: "Carolina Panthers", section: "Bomb Squad" },
  { number: "25", name: "Joe Burrow", team: "Cincinnati Bengals", section: "Bomb Squad" },
  { number: "26", name: "Emeka Egbuka", team: "Tampa Bay Buccaneers", section: "Bomb Squad" },
  { number: "27", name: "Jaxson Dart", team: "New York Giants", section: "Bomb Squad" },
  { number: "28", name: "Lamar Jackson", team: "Baltimore Ravens", section: "Bomb Squad" },
  { number: "29", name: "Davante Adams", team: "Los Angeles Rams", section: "Bomb Squad" },
  { number: "30", name: "Jayden Daniels", team: "Washington Commanders", section: "Bomb Squad" },
  { number: "31", name: "Dan Marino", team: "Miami Dolphins", section: "Bomb Squad" },
  { number: "32", name: "Brett Favre", team: "Green Bay Packers", section: "Bomb Squad" },
  { number: "33", name: "Aaron Rodgers", team: "Pittsburgh Steelers", section: "Bomb Squad" },
  { number: "34", name: "Larry Fitzgerald", team: "Arizona Cardinals", section: "Bomb Squad" },
  { number: "35", name: "Calvin Johnson", team: "Detroit Lions", section: "Bomb Squad" },
  { number: "1", name: "Jalen Hurts", team: "Philadelphia Eagles", section: "Champ is Here" },
  { number: "2", name: "Saquon Barkley", team: "Philadelphia Eagles", section: "Champ is Here" },
  { number: "3", name: "A.J. Brown", team: "Philadelphia Eagles", section: "Champ is Here" },
  { number: "4", name: "DeVonta Smith", team: "Philadelphia Eagles", section: "Champ is Here" },
  { number: "5", name: "Jahan Dotson", team: "Philadelphia Eagles", section: "Champ is Here" },
  { number: "6", name: "Kenneth Gainwell", team: "Philadelphia Eagles", section: "Champ is Here" },
  { number: "7", name: "Dallas Goedert", team: "Philadelphia Eagles", section: "Champ is Here" },
  { number: "8", name: "Jake Elliott", team: "Philadelphia Eagles", section: "Champ is Here" },
  { number: "9", name: "Nick Sirianni", team: "Philadelphia Eagles", section: "Champ is Here" },
  { number: "10", name: "Zack Baun", team: "Philadelphia Eagles", section: "Champ is Here" },
  { number: "11", name: "Cooper DeJean", team: "Philadelphia Eagles", section: "Champ is Here" },
  { number: "12", name: "Quinyon Mitchell", team: "Philadelphia Eagles", section: "Champ is Here" },
  { number: "13", name: "Jeremiah Trotter Jr.", team: "Philadelphia Eagles", section: "Champ is Here" },
  { number: "14", name: "Jalen Carter", team: "Philadelphia Eagles", section: "Champ is Here" },
  { number: "15", name: "Nolan Smith", team: "Philadelphia Eagles", section: "Champ is Here" },
  { number: "16", name: "Reed Blankenship", team: "Philadelphia Eagles", section: "Champ is Here" },
  { number: "17", name: "Josh Sweat", team: "Philadelphia Eagles", section: "Champ is Here" },
  { number: "18", name: "Oren Burks", team: "Philadelphia Eagles", section: "Champ is Here" },
  { number: "19", name: "Jordan Davis", team: "Philadelphia Eagles", section: "Champ is Here" },
  { number: "20", name: "Milton Williams", team: "Philadelphia Eagles", section: "Champ is Here" },
  { number: "1", name: "Philadelphia Eagles", team: "Philadelphia Eagles", section: "Champions" },
  { number: "1", name: "Josh Allen", team: "Buffalo Bills", section: "Crunch Time" },
  { number: "2", name: "Caleb Williams", team: "Chicago Bears", section: "Crunch Time" },
  { number: "3", name: "Myles Garrett", team: "Cleveland Browns", section: "Crunch Time" },
  { number: "4", name: "Saquon Barkley", team: "Philadelphia Eagles", section: "Crunch Time" },
  { number: "5", name: "Ja'Marr Chase", team: "Cincinnati Bengals", section: "Crunch Time" },
  { number: "6", name: "Christian McCaffrey", team: "San Francisco 49ers", section: "Crunch Time" },
  { number: "7", name: "Brock Bowers", team: "Las Vegas Raiders", section: "Crunch Time" },
  { number: "8", name: "Brian Thomas Jr.", team: "Jacksonville Jaguars", section: "Crunch Time" },
  { number: "9", name: "Ashton Jeanty", team: "Las Vegas Raiders", section: "Crunch Time" },
  { number: "10", name: "Travis Hunter", team: "Jacksonville Jaguars", section: "Crunch Time" },
  { number: "11", name: "Cam Ward", team: "Tennessee Titans", section: "Crunch Time" },
  { number: "12", name: "Matthew Golden", team: "Green Bay Packers", section: "Crunch Time" },
  { number: "13", name: "Omarion Hampton", team: "Los Angeles Chargers", section: "Crunch Time" },
  { number: "14", name: "Jaxson Dart", team: "New York Giants", section: "Crunch Time" },
  { number: "15", name: "Jalen Milroe", team: "Seattle Seahawks", section: "Crunch Time" },
  { number: "1", name: "Dak Prescott", team: "Dallas Cowboys", section: "Dominators" },
  { number: "2", name: "Dexter Lawrence", team: "New York Giants", section: "Dominators" },
  { number: "3", name: "A.J. Brown", team: "Philadelphia Eagles", section: "Dominators" },
  { number: "4", name: "Jalen Hurts", team: "Philadelphia Eagles", section: "Dominators" },
  { number: "5", name: "Brian Robinson Jr.", team: "Washington Commanders", section: "Dominators" },
  { number: "6", name: "Rome Odunze", team: "Chicago Bears", section: "Dominators" },
  { number: "7", name: "Amon-Ra St. Brown", team: "Detroit Lions", section: "Dominators" },
  { number: "8", name: "David Montgomery", team: "Detroit Lions", section: "Dominators" },
  { number: "9", name: "Josh Jacobs", team: "Green Bay Packers", section: "Dominators" },
  { number: "10", name: "Bijan Robinson", team: "Atlanta Falcons", section: "Dominators" },
  { number: "11", name: "Chuba Hubbard", team: "Carolina Panthers", section: "Dominators" },
  { number: "12", name: "Derek Carr", team: "New Orleans Saints", section: "Dominators" },
  { number: "13", name: "Baker Mayfield", team: "Tampa Bay Buccaneers", section: "Dominators" },
  { number: "14", name: "Chris Godwin", team: "Tampa Bay Buccaneers", section: "Dominators" },
  { number: "15", name: "James Conner", team: "Arizona Cardinals", section: "Dominators" },
  { number: "16", name: "Davante Adams", team: "Los Angeles Rams", section: "Dominators" },
  { number: "17", name: "Jared Verse", team: "Los Angeles Rams", section: "Dominators" },
  { number: "18", name: "Christian McCaffrey", team: "San Francisco 49ers", section: "Dominators" },
  { number: "19", name: "Jordan Addison", team: "Minnesota Vikings", section: "Dominators" },
  { number: "20", name: "Jaxon Smith-Njigba", team: "Seattle Seahawks", section: "Dominators" },
  { number: "21", name: "James Cook", team: "Buffalo Bills", section: "Dominators" },
  { number: "22", name: "Khalil Shakir", team: "Buffalo Bills", section: "Dominators" },
  { number: "23", name: "Tyreek Hill", team: "Miami Dolphins", section: "Dominators" },
  { number: "24", name: "Christian Gonzalez", team: "New England Patriots", section: "Dominators" },
  { number: "25", name: "Garrett Wilson", team: "New York Jets", section: "Dominators" },
  { number: "26", name: "Kyle Hamilton", team: "Baltimore Ravens", section: "Dominators" },
  { number: "27", name: "Lamar Jackson", team: "Baltimore Ravens", section: "Dominators" },
  { number: "28", name: "Joe Burrow", team: "Cincinnati Bengals", section: "Dominators" },
  { number: "29", name: "Jerry Jeudy", team: "Cleveland Browns", section: "Dominators" },
  { number: "30", name: "Minkah Fitzpatrick", team: "Pittsburgh Steelers", section: "Dominators" },
  { number: "31", name: "C.J. Stroud", team: "Houston Texans", section: "Dominators" },
  { number: "32", name: "Will Anderson Jr.", team: "Houston Texans", section: "Dominators" },
  { number: "33", name: "Michael Pittman Jr.", team: "Indianapolis Colts", section: "Dominators" },
  { number: "34", name: "Trevor Lawrence", team: "Jacksonville Jaguars", section: "Dominators" },
  { number: "35", name: "Jeffery Simmons", team: "Tennessee Titans", section: "Dominators" },
  { number: "36", name: "Nik Bonitto", team: "Denver Broncos", section: "Dominators" },
  { number: "37", name: "Travis Kelce", team: "Kansas City Chiefs", section: "Dominators" },
  { number: "38", name: "Xavier Worthy", team: "Kansas City Chiefs", section: "Dominators" },
  { number: "39", name: "Maxx Crosby", team: "Las Vegas Raiders", section: "Dominators" },
  { number: "40", name: "Justin Herbert", team: "Los Angeles Chargers", section: "Dominators" },
  { number: "1", name: "Lamar Jackson", team: "Baltimore Ravens", section: "Downtown!" },
  { number: "2", name: "Brian Thomas Jr.", team: "Jacksonville Jaguars", section: "Downtown!" },
  { number: "3", name: "Derrick Henry", team: "Baltimore Ravens", section: "Downtown!" },
  { number: "4", name: "Calvin Johnson", team: "Detroit Lions", section: "Downtown!" },
  { number: "5", name: "Archie Manning", team: "New Orleans Saints", section: "Downtown!" },
  { number: "6", name: "Matthew Stafford", team: "Los Angeles Rams", section: "Downtown!" },
  { number: "7", name: "Saquon Barkley", team: "Philadelphia Eagles", section: "Downtown!" },
  { number: "8", name: "Patrick Mahomes II", team: "Kansas City Chiefs", section: "Downtown!" },
  { number: "9", name: "CeeDee Lamb", team: "Dallas Cowboys", section: "Downtown!" },
  { number: "10", name: "De'Von Achane", team: "Miami Dolphins", section: "Downtown!" },
  { number: "11", name: "Ashton Jeanty", team: "Las Vegas Raiders", section: "Downtown!" },
  { number: "12", name: "Cam Ward", team: "Tennessee Titans", section: "Downtown!" },
  { number: "13", name: "Travis Hunter", team: "Jacksonville Jaguars", section: "Downtown!" },
  { number: "14", name: "Jaxson Dart", team: "New York Giants", section: "Downtown!" },
  { number: "15", name: "Tetairoa McMillan", team: "Carolina Panthers", section: "Downtown!" },
  { number: "16", name: "Omarion Hampton", team: "Los Angeles Chargers", section: "Downtown!" },
  { number: "17", name: "Shedeur Sanders", team: "Cleveland Browns", section: "Downtown!" },
  { number: "18", name: "Matthew Golden", team: "Green Bay Packers", section: "Downtown!" },
  { number: "19", name: "Tyler Shough", team: "New Orleans Saints", section: "Downtown!" },
  { number: "20", name: "Abdul Carter", team: "New York Giants", section: "Downtown!" },
  { number: "1", name: "Joe Burrow", team: "Cincinnati Bengals", section: "Horizontal Downtown!" },
  { number: "2", name: "Ja'Marr Chase", team: "Cincinnati Bengals", section: "Horizontal Downtown!" },
  { number: "3", name: "Jalen Hurts", team: "Philadelphia Eagles", section: "Horizontal Downtown!" },
  { number: "4", name: "Amon-Ra St. Brown", team: "Detroit Lions", section: "Horizontal Downtown!" },
  { number: "5", name: "Larry Fitzgerald", team: "Arizona Cardinals", section: "Horizontal Downtown!" },
  { number: "6", name: "Joe Montana", team: "Kansas City Chiefs", section: "Horizontal Downtown!" },
  { number: "7", name: "Ladd McConkey", team: "Los Angeles Chargers", section: "Horizontal Downtown!" },
  { number: "8", name: "Jayden Daniels", team: "Washington Commanders", section: "Horizontal Downtown!" },
  { number: "9", name: "Odell Beckham Jr.", team: "New York Giants", section: "Horizontal Downtown!" },
  { number: "10", name: "Josh Allen", team: "Buffalo Bills", section: "Horizontal Downtown!" },
  { number: "11", name: "Cam Ward", team: "Tennessee Titans", section: "Horizontal Downtown!" },
  { number: "12", name: "Jaxson Dart", team: "New York Giants", section: "Horizontal Downtown!" },
  { number: "13", name: "Travis Hunter", team: "Jacksonville Jaguars", section: "Horizontal Downtown!" },
  { number: "14", name: "Ashton Jeanty", team: "Las Vegas Raiders", section: "Horizontal Downtown!" },
  { number: "15", name: "TreVeyon Henderson", team: "New England Patriots", section: "Horizontal Downtown!" },
  { number: "16", name: "Colston Loveland", team: "Chicago Bears", section: "Horizontal Downtown!" },
  { number: "17", name: "Quinshon Judkins", team: "Cleveland Browns", section: "Horizontal Downtown!" },
  { number: "18", name: "Tyler Warren", team: "Indianapolis Colts", section: "Horizontal Downtown!" },
  { number: "19", name: "Cam Skattebo", team: "New York Giants", section: "Horizontal Downtown!" },
  { number: "20", name: "Jalen Milroe", team: "Seattle Seahawks", section: "Horizontal Downtown!" },
  { number: "1", name: "Jayden Daniels", team: "Washington Commanders", section: "Galactic" },
  { number: "2", name: "Malik Nabers", team: "New York Giants", section: "Galactic" },
  { number: "3", name: "Jahmyr Gibbs", team: "Detroit Lions", section: "Galactic" },
  { number: "4", name: "Jalen Hurts", team: "Philadelphia Eagles", section: "Galactic" },
  { number: "5", name: "Ja'Marr Chase", team: "Cincinnati Bengals", section: "Galactic" },
  { number: "6", name: "Brian Thomas Jr.", team: "Jacksonville Jaguars", section: "Galactic" },
  { number: "7", name: "Bo Nix", team: "Denver Broncos", section: "Galactic" },
  { number: "8", name: "Nico Collins", team: "Houston Texans", section: "Galactic" },
  { number: "9", name: "Christian McCaffrey", team: "San Francisco 49ers", section: "Galactic" },
  { number: "10", name: "Puka Nacua", team: "Los Angeles Rams", section: "Galactic" },
  { number: "11", name: "Brock Bowers", team: "Las Vegas Raiders", section: "Galactic" },
  { number: "12", name: "Tyreek Hill", team: "Miami Dolphins", section: "Galactic" },
  { number: "13", name: "Lamar Jackson", team: "Baltimore Ravens", section: "Galactic" },
  { number: "14", name: "James Cook", team: "Buffalo Bills", section: "Galactic" },
  { number: "15", name: "Bijan Robinson", team: "Atlanta Falcons", section: "Galactic" },
  { number: "1", name: "CeeDee Lamb", team: "Dallas Cowboys", section: "Gridiron Kings" },
  { number: "2", name: "Patrick Mahomes II", team: "Kansas City Chiefs", section: "Gridiron Kings" },
  { number: "3", name: "Josh Allen", team: "Buffalo Bills", section: "Gridiron Kings" },
  { number: "4", name: "Lamar Jackson", team: "Baltimore Ravens", section: "Gridiron Kings" },
  { number: "5", name: "Christian McCaffrey", team: "San Francisco 49ers", section: "Gridiron Kings" },
  { number: "6", name: "Jordan Love", team: "Green Bay Packers", section: "Gridiron Kings" },
  { number: "7", name: "Caleb Williams", team: "Chicago Bears", section: "Gridiron Kings" },
  { number: "8", name: "Saquon Barkley", team: "Philadelphia Eagles", section: "Gridiron Kings" },
  { number: "9", name: "Myles Garrett", team: "Cleveland Browns", section: "Gridiron Kings" },
  { number: "10", name: "Aidan Hutchinson", team: "Detroit Lions", section: "Gridiron Kings" },
  { number: "11", name: "Jalen Hurts", team: "Philadelphia Eagles", section: "Gridiron Kings" },
  { number: "12", name: "Mike Evans", team: "Tampa Bay Buccaneers", section: "Gridiron Kings" },
  { number: "13", name: "Joe Burrow", team: "Cincinnati Bengals", section: "Gridiron Kings" },
  { number: "14", name: "Derrick Henry", team: "Baltimore Ravens", section: "Gridiron Kings" },
  { number: "15", name: "Justin Jefferson", team: "Minnesota Vikings", section: "Gridiron Kings" },
  { number: "1", name: "Justin Jefferson", team: "Minnesota Vikings", section: "Gridiron Marvels" },
  { number: "2", name: "Puka Nacua", team: "Los Angeles Rams", section: "Gridiron Marvels" },
  { number: "3", name: "Justin Herbert", team: "Los Angeles Chargers", section: "Gridiron Marvels" },
  { number: "4", name: "Caleb Williams", team: "Chicago Bears", section: "Gridiron Marvels" },
  { number: "5", name: "Baker Mayfield", team: "Tampa Bay Buccaneers", section: "Gridiron Marvels" },
  { number: "6", name: "Josh Jacobs", team: "Green Bay Packers", section: "Gridiron Marvels" },
  { number: "7", name: "Maxx Crosby", team: "Las Vegas Raiders", section: "Gridiron Marvels" },
  { number: "8", name: "Nico Collins", team: "Houston Texans", section: "Gridiron Marvels" },
  { number: "9", name: "Tua Tagovailoa", team: "Miami Dolphins", section: "Gridiron Marvels" },
  { number: "10", name: "A.J. Brown", team: "Philadelphia Eagles", section: "Gridiron Marvels" },
  { number: "11", name: "Jaxson Dart", team: "New York Giants", section: "Gridiron Marvels" },
  { number: "12", name: "Shedeur Sanders", team: "Cleveland Browns", section: "Gridiron Marvels" },
  { number: "13", name: "Ashton Jeanty", team: "Las Vegas Raiders", section: "Gridiron Marvels" },
  { number: "14", name: "Cam Ward", team: "Tennessee Titans", section: "Gridiron Marvels" },
  { number: "15", name: "Travis Hunter", team: "Jacksonville Jaguars", section: "Gridiron Marvels" },
  { number: "16", name: "Tetairoa McMillan", team: "Carolina Panthers", section: "Gridiron Marvels" },
  { number: "17", name: "Emeka Egbuka", team: "Tampa Bay Buccaneers", section: "Gridiron Marvels" },
  { number: "18", name: "Tyler Warren", team: "Indianapolis Colts", section: "Gridiron Marvels" },
  { number: "19", name: "Tyler Shough", team: "New Orleans Saints", section: "Gridiron Marvels" },
  { number: "20", name: "Abdul Carter", team: "New York Giants", section: "Gridiron Marvels" },
  { number: "1", name: "Eric Allen", team: "Philadelphia Eagles", section: "Inducted" },
  { number: "2", name: "Antonio Gates", team: "San Diego Chargers", section: "Inducted" },
  { number: "3", name: "Brett Favre", team: "Green Bay Packers", section: "Inducted" },
  { number: "301", name: "Travis Hunter", team: "Jacksonville Jaguars", section: "Red Power" },
  { number: "302", name: "Cam Skattebo", team: "New York Giants", section: "Red Power" },
  { number: "303", name: "Omarion Hampton", team: "Los Angeles Chargers", section: "Red Power" },
  { number: "304", name: "Tyler Shough", team: "New Orleans Saints", section: "Red Power" },
  { number: "305", name: "Ashton Jeanty", team: "Las Vegas Raiders", section: "Red Power" },
  { number: "306", name: "Shedeur Sanders", team: "Cleveland Browns", section: "Red Power" },
  { number: "307", name: "Jalen Milroe", team: "Seattle Seahawks", section: "Red Power" },
  { number: "308", name: "Jaydon Blue", team: "Dallas Cowboys", section: "Red Power" },
  { number: "309", name: "Will Howard", team: "Pittsburgh Steelers", section: "Red Power" },
  { number: "310", name: "Colston Loveland", team: "Chicago Bears", section: "Red Power" },
  { number: "311", name: "Matthew Golden", team: "Green Bay Packers", section: "Red Power" },
  { number: "312", name: "RJ Harvey", team: "Denver Broncos", section: "Red Power" },
  { number: "313", name: "Tez Johnson", team: "Tampa Bay Buccaneers", section: "Red Power" },
  { number: "314", name: "Tetairoa McMillan", team: "Carolina Panthers", section: "Red Power" },
  { number: "315", name: "Abdul Carter", team: "New York Giants", section: "Red Power" },
  { number: "316", name: "Dillon Gabriel", team: "Cleveland Browns", section: "Red Power" },
  { number: "317", name: "Elijah Arroyo", team: "Seattle Seahawks", section: "Red Power" },
  { number: "318", name: "Savion Williams", team: "Green Bay Packers", section: "Red Power" },
  { number: "319", name: "Mykel Williams", team: "San Francisco 49ers", section: "Red Power" },
  { number: "320", name: "Jack Bech", team: "Las Vegas Raiders", section: "Red Power" },
  { number: "321", name: "Jalen Royals", team: "Kansas City Chiefs", section: "Red Power" },
  { number: "322", name: "Kaleb Johnson", team: "Pittsburgh Steelers", section: "Red Power" },
  { number: "323", name: "Terrance Ferguson", team: "Los Angeles Rams", section: "Red Power" },
  { number: "324", name: "Jaylin Noel", team: "Houston Texans", section: "Red Power" },
  { number: "325", name: "Kyle McCord", team: "Philadelphia Eagles", section: "Red Power" },
  { number: "326", name: "Trevor Etienne", team: "Carolina Panthers", section: "Red Power" },
  { number: "327", name: "Kyle Williams", team: "New England Patriots", section: "Red Power" },
  { number: "328", name: "Mason Taylor", team: "New York Jets", section: "Red Power" },
  { number: "329", name: "Tre Harris", team: "Los Angeles Chargers", section: "Red Power" },
  { number: "330", name: "Quinshon Judkins", team: "Cleveland Browns", section: "Red Power" },
  { number: "331", name: "Tai Felton", team: "Minnesota Vikings", section: "Red Power" },
  { number: "332", name: "TreVeyon Henderson", team: "New England Patriots", section: "Red Power" },
  { number: "333", name: "Bhayshul Tuten", team: "Jacksonville Jaguars", section: "Red Power" },
  { number: "334", name: "Jayden Higgins", team: "Houston Texans", section: "Red Power" },
  { number: "335", name: "Jaylin Lane", team: "Washington Commanders", section: "Red Power" },
  { number: "336", name: "Pat Bryant", team: "Denver Broncos", section: "Red Power" },
  { number: "337", name: "Tyler Warren", team: "Indianapolis Colts", section: "Red Power" },
  { number: "338", name: "Isaac TeSlaa", team: "Detroit Lions", section: "Red Power" },
  { number: "339", name: "Elic Ayomanor", team: "Tennessee Titans", section: "Red Power" },
  { number: "340", name: "Mason Graham", team: "Cleveland Browns", section: "Red Power" },
  { number: "341", name: "Riley Leonard", team: "Indianapolis Colts", section: "Red Power" },
  { number: "342", name: "Quinn Ewers", team: "Miami Dolphins", section: "Red Power" },
  { number: "343", name: "Jihaad Campbell", team: "Philadelphia Eagles", section: "Red Power" },
  { number: "344", name: "Jalon Walker", team: "Atlanta Falcons", section: "Red Power" },
  { number: "345", name: "Will Campbell", team: "New England Patriots", section: "Red Power" },
  { number: "346", name: "Malaki Starks", team: "Baltimore Ravens", section: "Red Power" },
  { number: "347", name: "Graham Mertz", team: "Houston Texans", section: "Red Power" },
  { number: "348", name: "Nick Emmanwori", team: "Seattle Seahawks", section: "Red Power" },
  { number: "349", name: "Dont'e Thornton Jr.", team: "Las Vegas Raiders", section: "Red Power" },
  { number: "350", name: "Cam Ward", team: "Tennessee Titans", section: "Red Power" },
  { number: "351", name: "T.J. Sanders", team: "Buffalo Bills", section: "Red Power" },
  { number: "352", name: "Jarquez Hunter", team: "Los Angeles Rams", section: "Red Power" },
  { number: "353", name: "Ashton Gillotte", team: "Kansas City Chiefs", section: "Red Power" },
  { number: "354", name: "Tyler Booker", team: "Dallas Cowboys", section: "Red Power" },
  { number: "355", name: "Alfred Collins", team: "San Francisco 49ers", section: "Red Power" },
  { number: "356", name: "Jordan Watkins", team: "San Francisco 49ers", section: "Red Power" },
  { number: "357", name: "Jackson Hawes", team: "Buffalo Bills", section: "Red Power" },
  { number: "358", name: "Armand Membou", team: "New York Jets", section: "Red Power" },
  { number: "359", name: "Devin Neal", team: "New Orleans Saints", section: "Red Power" },
  { number: "360", name: "Tyleik Williams", team: "Detroit Lions", section: "Red Power" },
  { number: "361", name: "Benjamin Morrison", team: "Tampa Bay Buccaneers", section: "Red Power" },
  { number: "362", name: "Maxwell Hairston", team: "Buffalo Bills", section: "Red Power" },
  { number: "363", name: "James Pearce Jr.", team: "Atlanta Falcons", section: "Red Power" },
  { number: "364", name: "DJ Giddens", team: "Indianapolis Colts", section: "Red Power" },
  { number: "365", name: "Jahdae Barron", team: "Denver Broncos", section: "Red Power" },
  { number: "366", name: "Grey Zabel", team: "Seattle Seahawks", section: "Red Power" },
  { number: "367", name: "KeAndre Lambert-Smith", team: "Los Angeles Chargers", section: "Red Power" },
  { number: "368", name: "Josh Simmons", team: "Kansas City Chiefs", section: "Red Power" },
  { number: "369", name: "Trey Amos", team: "Washington Commanders", section: "Red Power" },
  { number: "370", name: "Kenneth Grant", team: "Miami Dolphins", section: "Red Power" },
  { number: "371", name: "Gunnar Helm", team: "Tennessee Titans", section: "Red Power" },
  { number: "372", name: "Kelvin Banks Jr.", team: "New Orleans Saints", section: "Red Power" },
  { number: "373", name: "Harold Fannin Jr.", team: "Cleveland Browns", section: "Red Power" },
  { number: "374", name: "Jordan James", team: "San Francisco 49ers", section: "Red Power" },
  { number: "375", name: "Emeka Egbuka", team: "Tampa Bay Buccaneers", section: "Red Power" },
  { number: "376", name: "Josaiah Stewart", team: "Los Angeles Rams", section: "Red Power" },
  { number: "377", name: "Woody Marks", team: "Houston Texans", section: "Red Power" },
  { number: "378", name: "Kalel Mullings", team: "Tennessee Titans", section: "Red Power" },
  { number: "379", name: "Darius Alexander", team: "New York Giants", section: "Red Power" },
  { number: "380", name: "Andrew Mukuba", team: "Philadelphia Eagles", section: "Red Power" },
  { number: "381", name: "Donovan Jackson", team: "Minnesota Vikings", section: "Red Power" },
  { number: "382", name: "Tyler Loop", team: "Baltimore Ravens", section: "Red Power" },
  { number: "383", name: "Nic Scourton", team: "Carolina Panthers", section: "Red Power" },
  { number: "384", name: "Oluwafemi Oladejo", team: "Tennessee Titans", section: "Red Power" },
  { number: "385", name: "Demetrius Knight Jr.", team: "Cincinnati Bengals", section: "Red Power" },
  { number: "386", name: "Arian Smith", team: "New York Jets", section: "Red Power" },
  { number: "387", name: "Chimere Dike", team: "Tennessee Titans", section: "Red Power" },
  { number: "388", name: "Tory Horton", team: "Seattle Seahawks", section: "Red Power" },
  { number: "389", name: "Dylan Sampson", team: "Cleveland Browns", section: "Red Power" },
  { number: "390", name: "Jack Sawyer", team: "Pittsburgh Steelers", section: "Red Power" },
  { number: "391", name: "Derrick Harmon", team: "Pittsburgh Steelers", section: "Red Power" },
  { number: "392", name: "Carson Schwesinger", team: "Cleveland Browns", section: "Red Power" },
  { number: "393", name: "Shemar Stewart", team: "Cincinnati Bengals", section: "Red Power" },
  { number: "394", name: "Ollie Gordon II", team: "Miami Dolphins", section: "Red Power" },
  { number: "395", name: "Luther Burden III", team: "Chicago Bears", section: "Red Power" },
  { number: "396", name: "Will Johnson", team: "Arizona Cardinals", section: "Red Power" },
  { number: "397", name: "Mike Green", team: "Baltimore Ravens", section: "Red Power" },
  { number: "398", name: "JT Tuimoloau", team: "Indianapolis Colts", section: "Red Power" },
  { number: "399", name: "Xavier Watts", team: "Atlanta Falcons", section: "Red Power" },
  { number: "400", name: "Jaxson Dart", team: "New York Giants", section: "Red Power" },
  { number: "1", name: "Matthew Stafford/Puka Nacua", team: "Los Angeles Rams", section: "Galactic" },
  { number: "2", name: "David Montgomery/Jahmyr Gibbs", team: "Detroit Lions", section: "Galactic" },
  { number: "3", name: "CeeDee Lamb/Dak Prescott", team: "Dallas Cowboys", section: "Galactic" },
  { number: "4", name: "Justin Jefferson/Jordan Addison", team: "Minnesota Vikings", section: "Galactic" },
  { number: "5", name: "Trevor Lawrence/Brian Thomas Jr.", team: "Jacksonville Jaguars", section: "Galactic" },
  { number: "6", name: "Khalil Shakir/Josh Allen", team: "Buffalo Bills", section: "Galactic" },
  { number: "7", name: "Bijan Robinson /Michael Penix Jr.", team: "Atlanta Falcons", section: "Galactic" },
  { number: "8", name: "Jayden Daniels/Terry McLaurin", team: "Washington Commanders", section: "Galactic" },
  { number: "9", name: "Malik Nabers/Tyrone Tracy Jr.", team: "New York Giants", section: "Galactic" },
  { number: "10", name: "Ja'Marr Chase/Tee Higgins", team: "Cincinnati Bengals", section: "Galactic" },
  { number: "11", name: "C.J. Stroud /Nico Collins", team: "Houston Texans", section: "Galactic" },
  { number: "12", name: "Fred Warner/Nick Bosa", team: "San Francisco 49ers", section: "Galactic" },
  { number: "13", name: "Ladd McConkey/Justin Herbert", team: "Los Angeles Chargers", section: "Galactic" },
  { number: "14", name: "Kenneth Walker III/Jaxon Smith-Njigba", team: "Seattle Seahawks", section: "Galactic" },
  { number: "15", name: "Courtland Sutton/Bo Nix", team: "Denver Broncos", section: "Galactic" },
  { number: "16", name: "Saquon Barkley/Jalen Hurts", team: "Philadelphia Eagles", section: "Galactic" },
  { number: "17", name: "Caleb Williams/Rome Odunze", team: "Chicago Bears", section: "Galactic" },
  { number: "18", name: "Marvin Harrison Jr./Trey McBride", team: "Arizona Cardinals", section: "Galactic" },
  { number: "19", name: "Jaylen Waddle/Tyreek Hill", team: "Miami Dolphins", section: "Galactic" },
  { number: "20", name: "Derrick Henry/Lamar Jackson", team: "Baltimore Ravens", section: "Galactic" },
  { number: "1", name: "Jaxson Dart", team: "New York Giants", section: "Rated Rookies Retro" },
  { number: "2", name: "Cam Ward", team: "Tennessee Titans", section: "Rated Rookies Retro" },
  { number: "3", name: "Tetairoa McMillan", team: "Carolina Panthers", section: "Rated Rookies Retro" },
  { number: "4", name: "Travis Hunter", team: "Jacksonville Jaguars", section: "Rated Rookies Retro" },
  { number: "5", name: "Quinshon Judkins", team: "Cleveland Browns", section: "Rated Rookies Retro" },
  { number: "6", name: "Isaac TeSlaa", team: "Detroit Lions", section: "Rated Rookies Retro" },
  { number: "7", name: "Savion Williams", team: "Green Bay Packers", section: "Rated Rookies Retro" },
  { number: "8", name: "Jayden Higgins", team: "Houston Texans", section: "Rated Rookies Retro" },
  { number: "9", name: "Tyler Warren", team: "Indianapolis Colts", section: "Rated Rookies Retro" },
  { number: "10", name: "Ashton Jeanty", team: "Las Vegas Raiders", section: "Rated Rookies Retro" },
  { number: "11", name: "Shedeur Sanders", team: "Cleveland Browns", section: "Rated Rookies Retro" },
  { number: "12", name: "Tre Harris", team: "Los Angeles Chargers", section: "Rated Rookies Retro" },
  { number: "13", name: "Quinn Ewers", team: "Miami Dolphins", section: "Rated Rookies Retro" },
  { number: "14", name: "Tyler Shough", team: "New Orleans Saints", section: "Rated Rookies Retro" },
  { number: "15", name: "Will Howard", team: "Pittsburgh Steelers", section: "Rated Rookies Retro" },
  { number: "16", name: "Jalen Milroe", team: "Seattle Seahawks", section: "Rated Rookies Retro" },
  { number: "17", name: "Mykel Williams", team: "San Francisco 49ers", section: "Rated Rookies Retro" },
  { number: "18", name: "Colston Loveland", team: "Chicago Bears", section: "Rated Rookies Retro" },
  { number: "19", name: "Kaleb Johnson", team: "Pittsburgh Steelers", section: "Rated Rookies Retro" },
  { number: "20", name: "TreVeyon Henderson", team: "New England Patriots", section: "Rated Rookies Retro" },
  { number: "1", name: "Jihaad Campbell", team: "Philadelphia Eagles", section: "Rated Rookies Throwback" },
  { number: "2", name: "Shedeur Sanders", team: "Cleveland Browns", section: "Rated Rookies Throwback" },
  { number: "3", name: "Travis Hunter", team: "Jacksonville Jaguars", section: "Rated Rookies Throwback" },
  { number: "4", name: "Quinn Ewers", team: "Miami Dolphins", section: "Rated Rookies Throwback" },
  { number: "5", name: "Tyleik Williams", team: "Detroit Lions", section: "Rated Rookies Throwback" },
  { number: "6", name: "Ashton Jeanty", team: "Las Vegas Raiders", section: "Rated Rookies Throwback" },
  { number: "7", name: "Maxwell Hairston", team: "Buffalo Bills", section: "Rated Rookies Throwback" },
  { number: "8", name: "Colston Loveland", team: "Chicago Bears", section: "Rated Rookies Throwback" },
  { number: "9", name: "Matthew Golden", team: "Green Bay Packers", section: "Rated Rookies Throwback" },
  { number: "10", name: "Kyle McCord", team: "Philadelphia Eagles", section: "Rated Rookies Throwback" },
  { number: "11", name: "Malaki Starks", team: "Baltimore Ravens", section: "Rated Rookies Throwback" },
  { number: "12", name: "Tyler Warren", team: "Indianapolis Colts", section: "Rated Rookies Throwback" },
  { number: "13", name: "James Pearce Jr.", team: "Atlanta Falcons", section: "Rated Rookies Throwback" },
  { number: "14", name: "Omarion Hampton", team: "Los Angeles Chargers", section: "Rated Rookies Throwback" },
  { number: "15", name: "Dillon Gabriel", team: "Cleveland Browns", section: "Rated Rookies Throwback" },
  { number: "16", name: "RJ Harvey", team: "Denver Broncos", section: "Rated Rookies Throwback" },
  { number: "17", name: "Derrick Harmon", team: "Pittsburgh Steelers", section: "Rated Rookies Throwback" },
  { number: "18", name: "Jalen Milroe", team: "Seattle Seahawks", section: "Rated Rookies Throwback" },
  { number: "19", name: "TreVeyon Henderson", team: "New England Patriots", section: "Rated Rookies Throwback" },
  { number: "20", name: "Mykel Williams", team: "San Francisco 49ers", section: "Rated Rookies Throwback" },
  { number: "21", name: "Tyler Shough", team: "New Orleans Saints", section: "Rated Rookies Throwback" },
  { number: "22", name: "Isaac TeSlaa", team: "Detroit Lions", section: "Rated Rookies Throwback" },
  { number: "23", name: "Walter Nolen", team: "Arizona Cardinals", section: "Rated Rookies Throwback" },
  { number: "24", name: "Jahdae Barron", team: "Denver Broncos", section: "Rated Rookies Throwback" },
  { number: "25", name: "Cam Ward", team: "Tennessee Titans", section: "Rated Rookies Throwback" },
  { number: "26", name: "Quinshon Judkins", team: "Cleveland Browns", section: "Rated Rookies Throwback" },
  { number: "27", name: "Kenneth Grant", team: "Miami Dolphins", section: "Rated Rookies Throwback" },
  { number: "28", name: "Mason Taylor", team: "New York Jets", section: "Rated Rookies Throwback" },
  { number: "29", name: "Jalon Walker", team: "Atlanta Falcons", section: "Rated Rookies Throwback" },
  { number: "30", name: "Will Howard", team: "Pittsburgh Steelers", section: "Rated Rookies Throwback" },
  { number: "31", name: "Emeka Egbuka", team: "Tampa Bay Buccaneers", section: "Rated Rookies Throwback" },
  { number: "32", name: "Tetairoa McMillan", team: "Carolina Panthers", section: "Rated Rookies Throwback" },
  { number: "33", name: "Riley Leonard", team: "Indianapolis Colts", section: "Rated Rookies Throwback" },
  { number: "34", name: "Tre Harris", team: "Los Angeles Chargers", section: "Rated Rookies Throwback" },
  { number: "35", name: "Shemar Stewart", team: "Cincinnati Bengals", section: "Rated Rookies Throwback" },
  { number: "36", name: "Cam Skattebo", team: "New York Giants", section: "Rated Rookies Throwback" },
  { number: "37", name: "Jayden Higgins", team: "Houston Texans", section: "Rated Rookies Throwback" },
  { number: "38", name: "Bhayshul Tuten", team: "Jacksonville Jaguars", section: "Rated Rookies Throwback" },
  { number: "39", name: "Pat Bryant", team: "Denver Broncos", section: "Rated Rookies Throwback" },
  { number: "40", name: "Mason Graham", team: "Cleveland Browns", section: "Rated Rookies Throwback" },
  { number: "41", name: "Jaxson Dart", team: "New York Giants", section: "Rated Rookies Throwback" },
  { number: "42", name: "Luther Burden III", team: "Chicago Bears", section: "Rated Rookies Throwback" },
  { number: "43", name: "Savion Williams", team: "Green Bay Packers", section: "Rated Rookies Throwback" },
  { number: "44", name: "Elijah Arroyo", team: "Seattle Seahawks", section: "Rated Rookies Throwback" },
  { number: "45", name: "Jaylin Noel", team: "Houston Texans", section: "Rated Rookies Throwback" },
  { number: "46", name: "Kaleb Johnson", team: "Pittsburgh Steelers", section: "Rated Rookies Throwback" },
  { number: "47", name: "Jack Bech", team: "Las Vegas Raiders", section: "Rated Rookies Throwback" },
  { number: "48", name: "Kyle Williams", team: "New England Patriots", section: "Rated Rookies Throwback" },
  { number: "49", name: "Abdul Carter", team: "New York Giants", section: "Rated Rookies Throwback" },
  { number: "50", name: "Jalen Royals", team: "Kansas City Chiefs", section: "Rated Rookies Throwback" },
  { number: "1", name: "Travis Hunter", team: "Jacksonville Jaguars", section: "Red Hot Rookies" },
  { number: "2", name: "Kaleb Johnson", team: "Pittsburgh Steelers", section: "Red Hot Rookies" },
  { number: "3", name: "Jaxson Dart", team: "New York Giants", section: "Red Hot Rookies" },
  { number: "4", name: "Tetairoa McMillan", team: "Carolina Panthers", section: "Red Hot Rookies" },
  { number: "5", name: "Tyler Shough", team: "New Orleans Saints", section: "Red Hot Rookies" },
  { number: "6", name: "Colston Loveland", team: "Chicago Bears", section: "Red Hot Rookies" },
  { number: "7", name: "Shedeur Sanders", team: "Cleveland Browns", section: "Red Hot Rookies" },
  { number: "8", name: "Ashton Jeanty", team: "Las Vegas Raiders", section: "Red Hot Rookies" },
  { number: "9", name: "Cam Ward", team: "Tennessee Titans", section: "Red Hot Rookies" },
  { number: "10", name: "Emeka Egbuka", team: "Tampa Bay Buccaneers", section: "Red Hot Rookies" },
  { number: "1", name: "Dak Prescott", team: "Dallas Cowboys", section: "Retro 1995" },
  { number: "2", name: "Shedeur Sanders", team: "Cleveland Browns", section: "Retro 1995" },
  { number: "3", name: "Rome Odunze", team: "Chicago Bears", section: "Retro 1995" },
  { number: "4", name: "Tyler Warren", team: "Indianapolis Colts", section: "Retro 1995" },
  { number: "5", name: "Travis Hunter", team: "Jacksonville Jaguars", section: "Retro 1995" },
  { number: "6", name: "Derrick Henry", team: "Baltimore Ravens", section: "Retro 1995" },
  { number: "7", name: "Matthew Golden", team: "Green Bay Packers", section: "Retro 1995" },
  { number: "8", name: "Ashton Jeanty", team: "Las Vegas Raiders", section: "Retro 1995" },
  { number: "9", name: "Kyren Williams", team: "Los Angeles Rams", section: "Retro 1995" },
  { number: "10", name: "J.J. McCarthy", team: "Minnesota Vikings", section: "Retro 1995" },
  { number: "11", name: "Justin Herbert", team: "Los Angeles Chargers", section: "Retro 1995" },
  { number: "12", name: "Isaac TeSlaa", team: "Detroit Lions", section: "Retro 1995" },
  { number: "13", name: "Saquon Barkley", team: "Philadelphia Eagles", section: "Retro 1995" },
  { number: "14", name: "Breece Hall", team: "New York Jets", section: "Retro 1995" },
  { number: "15", name: "Tyler Shough", team: "New Orleans Saints", section: "Retro 1995" },
  { number: "16", name: "Josh Allen", team: "Buffalo Bills", section: "Retro 1995" },
  { number: "17", name: "Jaxon Smith-Njigba", team: "Seattle Seahawks", section: "Retro 1995" },
  { number: "18", name: "Colston Loveland", team: "Chicago Bears", section: "Retro 1995" },
  { number: "19", name: "Dillon Gabriel", team: "Cleveland Browns", section: "Retro 1995" },
  { number: "20", name: "Nick Bosa", team: "San Francisco 49ers", section: "Retro 1995" },
  { number: "21", name: "Patrick Mahomes II", team: "Kansas City Chiefs", section: "Retro 1995" },
  { number: "22", name: "Brian Thomas Jr.", team: "Jacksonville Jaguars", section: "Retro 1995" },
  { number: "23", name: "Tetairoa McMillan", team: "Carolina Panthers", section: "Retro 1995" },
  { number: "24", name: "Marvin Harrison Jr.", team: "Arizona Cardinals", section: "Retro 1995" },
  { number: "25", name: "Sam Darnold", team: "Seattle Seahawks", section: "Retro 1995" },
  { number: "26", name: "Aidan Hutchinson", team: "Detroit Lions", section: "Retro 1995" },
  { number: "27", name: "Joe Burrow", team: "Cincinnati Bengals", section: "Retro 1995" },
  { number: "28", name: "Tyreek Hill", team: "Miami Dolphins", section: "Retro 1995" },
  { number: "29", name: "TreVeyon Henderson", team: "New England Patriots", section: "Retro 1995" },
  { number: "30", name: "Bijan Robinson", team: "Atlanta Falcons", section: "Retro 1995" },
  { number: "31", name: "Will Howard", team: "Pittsburgh Steelers", section: "Retro 1995" },
  { number: "32", name: "Bo Nix", team: "Denver Broncos", section: "Retro 1995" },
  { number: "33", name: "Jaxson Dart", team: "New York Giants", section: "Retro 1995" },
  { number: "34", name: "Emeka Egbuka", team: "Tampa Bay Buccaneers", section: "Retro 1995" },
  { number: "35", name: "Travis Kelce", team: "Kansas City Chiefs", section: "Retro 1995" },
  { number: "36", name: "Cam Ward", team: "Tennessee Titans", section: "Retro 1995" },
  { number: "37", name: "Malik Nabers", team: "New York Giants", section: "Retro 1995" },
  { number: "38", name: "Lamar Jackson", team: "Baltimore Ravens", section: "Retro 1995" },
  { number: "39", name: "Jayden Daniels", team: "Washington Commanders", section: "Retro 1995" },
  { number: "40", name: "C.J. Stroud", team: "Houston Texans", section: "Retro 1995" },
  { number: "1", name: "Patrick Mahomes II", team: "Kansas City Chiefs", section: "Retro 2005" },
  { number: "2", name: "Matthew Golden", team: "Green Bay Packers", section: "Retro 2005" },
  { number: "3", name: "CeeDee Lamb", team: "Dallas Cowboys", section: "Retro 2005" },
  { number: "4", name: "Ashton Jeanty", team: "Las Vegas Raiders", section: "Retro 2005" },
  { number: "5", name: "Jalen Milroe", team: "Seattle Seahawks", section: "Retro 2005" },
  { number: "6", name: "Jalen Hurts", team: "Philadelphia Eagles", section: "Retro 2005" },
  { number: "7", name: "Tyler Shough", team: "New Orleans Saints", section: "Retro 2005" },
  { number: "8", name: "Travis Hunter", team: "Jacksonville Jaguars", section: "Retro 2005" },
  { number: "9", name: "Jayden Higgins", team: "Houston Texans", section: "Retro 2005" },
  { number: "10", name: "Shedeur Sanders", team: "Cleveland Browns", section: "Retro 2005" },
  { number: "11", name: "Tyler Warren", team: "Indianapolis Colts", section: "Retro 2005" },
  { number: "12", name: "Michael Penix Jr.", team: "Atlanta Falcons", section: "Retro 2005" },
  { number: "13", name: "Justin Jefferson", team: "Minnesota Vikings", section: "Retro 2005" },
  { number: "14", name: "Garrett Wilson", team: "New York Jets", section: "Retro 2005" },
  { number: "15", name: "Tetairoa McMillan", team: "Carolina Panthers", section: "Retro 2005" },
  { number: "16", name: "A.J. Brown", team: "Philadelphia Eagles", section: "Retro 2005" },
  { number: "17", name: "Abdul Carter", team: "New York Giants", section: "Retro 2005" },
  { number: "18", name: "Trevor Lawrence", team: "Jacksonville Jaguars", section: "Retro 2005" },
  { number: "19", name: "Cam Ward", team: "Tennessee Titans", section: "Retro 2005" },
  { number: "20", name: "Quinshon Judkins", team: "Cleveland Browns", section: "Retro 2005" },
  { number: "21", name: "Omarion Hampton", team: "Los Angeles Chargers", section: "Retro 2005" },
  { number: "22", name: "RJ Harvey", team: "Denver Broncos", section: "Retro 2005" },
  { number: "23", name: "J.J. McCarthy", team: "Minnesota Vikings", section: "Retro 2005" },
  { number: "24", name: "Puka Nacua", team: "Los Angeles Rams", section: "Retro 2005" },
  { number: "25", name: "Jordan Love", team: "Green Bay Packers", section: "Retro 2005" },
  { number: "26", name: "Ja'Marr Chase", team: "Cincinnati Bengals", section: "Retro 2005" },
  { number: "27", name: "Jayden Daniels", team: "Washington Commanders", section: "Retro 2005" },
  { number: "28", name: "Brock Purdy", team: "San Francisco 49ers", section: "Retro 2005" },
  { number: "29", name: "Drake Maye", team: "New England Patriots", section: "Retro 2005" },
  { number: "30", name: "Lamar Jackson", team: "Baltimore Ravens", section: "Retro 2005" },
  { number: "31", name: "Trey McBride", team: "Arizona Cardinals", section: "Retro 2005" },
  { number: "32", name: "Luther Burden III", team: "Chicago Bears", section: "Retro 2005" },
  { number: "33", name: "Jahmyr Gibbs", team: "Detroit Lions", section: "Retro 2005" },
  { number: "34", name: "Jaxson Dart", team: "New York Giants", section: "Retro 2005" },
  { number: "35", name: "De'Von Achane", team: "Miami Dolphins", section: "Retro 2005" },
  { number: "36", name: "Maxx Crosby", team: "Las Vegas Raiders", section: "Retro 2005" },
  { number: "37", name: "T.J. Watt", team: "Pittsburgh Steelers", section: "Retro 2005" },
  { number: "38", name: "Caleb Williams", team: "Chicago Bears", section: "Retro 2005" },
  { number: "39", name: "Emeka Egbuka", team: "Tampa Bay Buccaneers", section: "Retro 2005" },
  { number: "40", name: "Josh Allen", team: "Buffalo Bills", section: "Retro 2005" },
  { number: "1", name: "C.J. Stroud", team: "Houston Texans", section: "Retro 2005" },
  { number: "2", name: "Derrick Henry", team: "Baltimore Ravens", section: "Retro 2005" },
  { number: "3", name: "James Cook", team: "Buffalo Bills", section: "Retro 2005" },
  { number: "4", name: "Saquon Barkley", team: "Philadelphia Eagles", section: "Retro 2005" },
  { number: "5", name: "Jayden Daniels", team: "Washington Commanders", section: "Retro 2005" },
  { number: "6", name: "Matthew Stafford", team: "Los Angeles Rams", section: "Retro 2005" },
  { number: "1", name: "Travis Kelce", team: "Kansas City Chiefs", section: "Road to the Super Bowl Divisional Round" },
  { number: "2", name: "Brian Robinson Jr.", team: "Washington Commanders", section: "Road to the Super Bowl Divisional Round" },
  { number: "3", name: "Jake Elliott", team: "Philadelphia Eagles", section: "Road to the Super Bowl Divisional Round" },
  { number: "4", name: "Josh Allen", team: "Buffalo Bills", section: "Road to the Super Bowl Divisional Round" },
  { number: "1", name: "Zack Baun", team: "Philadelphia Eagles", section: "Road to the Super Bowl Conference Championship" },
  { number: "2", name: "Patrick Mahomes II", team: "Kansas City Chiefs", section: "Road to the Super Bowl Conference Championship" },
  { number: "1", name: "Jalen Hurts", team: "Philadelphia Eagles", section: "Road to the Super Bowl Championship" },
  { number: "1", name: "Ashton Jeanty", team: "Las Vegas Raiders", section: "Rookie Gridiron Kings" },
  { number: "2", name: "Travis Hunter", team: "Jacksonville Jaguars", section: "Rookie Gridiron Kings" },
  { number: "3", name: "Omarion Hampton", team: "Los Angeles Chargers", section: "Rookie Gridiron Kings" },
  { number: "4", name: "Tyler Shough", team: "New Orleans Saints", section: "Rookie Gridiron Kings" },
  { number: "5", name: "Matthew Golden", team: "Green Bay Packers", section: "Rookie Gridiron Kings" },
  { number: "6", name: "Dillon Gabriel", team: "Cleveland Browns", section: "Rookie Gridiron Kings" },
  { number: "7", name: "Jayden Higgins", team: "Houston Texans", section: "Rookie Gridiron Kings" },
  { number: "8", name: "Will Howard", team: "Pittsburgh Steelers", section: "Rookie Gridiron Kings" },
  { number: "9", name: "Abdul Carter", team: "New York Giants", section: "Rookie Gridiron Kings" },
  { number: "10", name: "Riley Leonard", team: "Indianapolis Colts", section: "Rookie Gridiron Kings" },
  { number: "11", name: "Jack Bech", team: "Las Vegas Raiders", section: "Rookie Gridiron Kings" },
  { number: "12", name: "Shedeur Sanders", team: "Cleveland Browns", section: "Rookie Gridiron Kings" },
  { number: "13", name: "Tai Felton", team: "Minnesota Vikings", section: "Rookie Gridiron Kings" },
  { number: "14", name: "Jalen Milroe", team: "Seattle Seahawks", section: "Rookie Gridiron Kings" },
  { number: "15", name: "Tetairoa McMillan", team: "Carolina Panthers", section: "Rookie Gridiron Kings" },
  { number: "16", name: "Kyle McCord", team: "Philadelphia Eagles", section: "Rookie Gridiron Kings" },
  { number: "17", name: "Luther Burden III", team: "Chicago Bears", section: "Rookie Gridiron Kings" },
  { number: "18", name: "Jaxson Dart", team: "New York Giants", section: "Rookie Gridiron Kings" },
  { number: "19", name: "Emeka Egbuka", team: "Tampa Bay Buccaneers", section: "Rookie Gridiron Kings" },
  { number: "20", name: "Cam Ward", team: "Tennessee Titans", section: "Rookie Gridiron Kings" },
  { number: "1", name: "Will Howard", team: "Pittsburgh Steelers", section: "Galactic" },
  { number: "2", name: "Elic Ayomanor", team: "Tennessee Titans", section: "Galactic" },
  { number: "3", name: "TreVeyon Henderson", team: "New England Patriots", section: "Galactic" },
  { number: "4", name: "Tetairoa McMillan", team: "Carolina Panthers", section: "Galactic" },
  { number: "5", name: "Quinn Ewers", team: "Miami Dolphins", section: "Galactic" },
  { number: "6", name: "Jaylin Noel", team: "Houston Texans", section: "Galactic" },
  { number: "7", name: "Pat Bryant", team: "Denver Broncos", section: "Galactic" },
  { number: "8", name: "Jaydon Blue", team: "Dallas Cowboys", section: "Galactic" },
  { number: "9", name: "Shedeur Sanders", team: "Cleveland Browns", section: "Galactic" },
  { number: "10", name: "Emeka Egbuka", team: "Tampa Bay Buccaneers", section: "Galactic" },
  { number: "11", name: "Abdul Carter", team: "New York Giants", section: "Galactic" },
  { number: "12", name: "Jalen Royals", team: "Kansas City Chiefs", section: "Galactic" },
  { number: "13", name: "Mason Taylor", team: "New York Jets", section: "Galactic" },
  { number: "14", name: "Cam Skattebo", team: "New York Giants", section: "Galactic" },
  { number: "15", name: "Bhayshul Tuten", team: "Jacksonville Jaguars", section: "Galactic" },
  { number: "16", name: "Tyler Warren", team: "Indianapolis Colts", section: "Galactic" },
  { number: "17", name: "Jalen Milroe", team: "Seattle Seahawks", section: "Galactic" },
  { number: "18", name: "Savion Williams", team: "Green Bay Packers", section: "Galactic" },
  { number: "19", name: "Kalel Mullings", team: "Tennessee Titans", section: "Galactic" },
  { number: "20", name: "Cam Ward", team: "Tennessee Titans", section: "Galactic" },
  { number: "21", name: "Riley Leonard", team: "Indianapolis Colts", section: "Galactic" },
  { number: "22", name: "Isaac TeSlaa", team: "Detroit Lions", section: "Galactic" },
  { number: "23", name: "Kyle McCord", team: "Philadelphia Eagles", section: "Galactic" },
  { number: "24", name: "Kyle Williams", team: "New England Patriots", section: "Galactic" },
  { number: "25", name: "Jack Bech", team: "Las Vegas Raiders", section: "Galactic" },
  { number: "26", name: "Tre Harris", team: "Los Angeles Chargers", section: "Galactic" },
  { number: "27", name: "Elijah Arroyo", team: "Seattle Seahawks", section: "Galactic" },
  { number: "28", name: "Trevor Etienne", team: "Carolina Panthers", section: "Galactic" },
  { number: "29", name: "Tyler Shough", team: "New Orleans Saints", section: "Galactic" },
  { number: "30", name: "Jaxson Dart", team: "New York Giants", section: "Galactic" },
  { number: "31", name: "Quinshon Judkins", team: "Cleveland Browns", section: "Galactic" },
  { number: "32", name: "Travis Hunter", team: "Jacksonville Jaguars", section: "Galactic" },
  { number: "33", name: "Jayden Higgins", team: "Houston Texans", section: "Galactic" },
  { number: "34", name: "Matthew Golden", team: "Green Bay Packers", section: "Galactic" },
  { number: "35", name: "Omarion Hampton", team: "Los Angeles Chargers", section: "Galactic" },
  { number: "36", name: "Colston Loveland", team: "Chicago Bears", section: "Galactic" },
  { number: "37", name: "Ashton Jeanty", team: "Las Vegas Raiders", section: "Galactic" },
  { number: "38", name: "Dillon Gabriel", team: "Cleveland Browns", section: "Galactic" },
  { number: "39", name: "Mykel Williams", team: "San Francisco 49ers", section: "Galactic" },
  { number: "40", name: "Luther Burden III", team: "Chicago Bears", section: "Galactic" },
  { number: "1", name: "Jalen Hurts", team: "Philadelphia Eagles", section: "Super Bowl MVP" },
  { number: "1", name: "Micah Parsons", team: "Dallas Cowboys", section: "The Elite Series" },
  { number: "2", name: "Malik Nabers", team: "New York Giants", section: "The Elite Series" },
  { number: "3", name: "Cooper DeJean", team: "Philadelphia Eagles", section: "The Elite Series" },
  { number: "4", name: "Jayden Daniels", team: "Washington Commanders", section: "The Elite Series" },
  { number: "5", name: "Caleb Williams", team: "Chicago Bears", section: "The Elite Series" },
  { number: "6", name: "Jahmyr Gibbs", team: "Detroit Lions", section: "The Elite Series" },
  { number: "7", name: "Jordan Love", team: "Green Bay Packers", section: "The Elite Series" },
  { number: "8", name: "J.J. McCarthy", team: "Minnesota Vikings", section: "The Elite Series" },
  { number: "9", name: "Michael Penix Jr.", team: "Atlanta Falcons", section: "The Elite Series" },
  { number: "10", name: "Bryce Young", team: "Carolina Panthers", section: "The Elite Series" },
  { number: "11", name: "Alvin Kamara", team: "New Orleans Saints", section: "The Elite Series" },
  { number: "12", name: "Bucky Irving", team: "Tampa Bay Buccaneers", section: "The Elite Series" },
  { number: "13", name: "Trey McBride", team: "Arizona Cardinals", section: "The Elite Series" },
  { number: "14", name: "Puka Nacua", team: "Los Angeles Rams", section: "The Elite Series" },
  { number: "15", name: "Nick Bosa", team: "San Francisco 49ers", section: "The Elite Series" },
  { number: "16", name: "Josh Allen", team: "Buffalo Bills", section: "The Elite Series" },
  { number: "17", name: "De'Von Achane", team: "Miami Dolphins", section: "The Elite Series" },
  { number: "18", name: "Drake Maye", team: "New England Patriots", section: "The Elite Series" },
  { number: "19", name: "Derrick Henry", team: "Baltimore Ravens", section: "The Elite Series" },
  { number: "20", name: "Chase Brown", team: "Cincinnati Bengals", section: "The Elite Series" },
  { number: "21", name: "T.J. Watt", team: "Pittsburgh Steelers", section: "The Elite Series" },
  { number: "22", name: "Nico Collins", team: "Houston Texans", section: "The Elite Series" },
  { number: "23", name: "Jonathan Taylor", team: "Indianapolis Colts", section: "The Elite Series" },
  { number: "24", name: "Brian Thomas Jr.", team: "Jacksonville Jaguars", section: "The Elite Series" },
  { number: "25", name: "Tony Pollard", team: "Tennessee Titans", section: "The Elite Series" },
  { number: "26", name: "Myles Garrett", team: "Cleveland Browns", section: "The Elite Series" },
  { number: "27", name: "Bo Nix", team: "Denver Broncos", section: "The Elite Series" },
  { number: "28", name: "Patrick Mahomes II", team: "Kansas City Chiefs", section: "The Elite Series" },
  { number: "29", name: "Brock Bowers", team: "Las Vegas Raiders", section: "The Elite Series" },
  { number: "30", name: "Ladd McConkey", team: "Los Angeles Chargers", section: "The Elite Series" },
  { number: "1", name: "Mykel Williams", team: "San Francisco 49ers", section: "The Elite Series Rookies" },
  { number: "2", name: "Travis Hunter", team: "Jacksonville Jaguars", section: "The Elite Series Rookies" },
  { number: "3", name: "Matthew Golden", team: "Green Bay Packers", section: "The Elite Series Rookies" },
  { number: "4", name: "Cam Ward", team: "Tennessee Titans", section: "The Elite Series Rookies" },
  { number: "5", name: "Abdul Carter", team: "New York Giants", section: "The Elite Series Rookies" },
  { number: "6", name: "Will Howard", team: "Pittsburgh Steelers", section: "The Elite Series Rookies" },
  { number: "7", name: "Shedeur Sanders", team: "Cleveland Browns", section: "The Elite Series Rookies" },
  { number: "8", name: "Ashton Jeanty", team: "Las Vegas Raiders", section: "The Elite Series Rookies" },
  { number: "9", name: "Omarion Hampton", team: "Los Angeles Chargers", section: "The Elite Series Rookies" },
  { number: "10", name: "Colston Loveland", team: "Chicago Bears", section: "The Elite Series Rookies" },
  { number: "11", name: "Tez Johnson", team: "Tampa Bay Buccaneers", section: "The Elite Series Rookies" },
  { number: "12", name: "Jalen Milroe", team: "Seattle Seahawks", section: "The Elite Series Rookies" },
  { number: "13", name: "TreVeyon Henderson", team: "New England Patriots", section: "The Elite Series Rookies" },
  { number: "14", name: "Dillon Gabriel", team: "Cleveland Browns", section: "The Elite Series Rookies" },
  { number: "15", name: "Tetairoa McMillan", team: "Carolina Panthers", section: "The Elite Series Rookies" },
  { number: "16", name: "RJ Harvey", team: "Denver Broncos", section: "The Elite Series Rookies" },
  { number: "17", name: "Jaylin Noel", team: "Houston Texans", section: "The Elite Series Rookies" },
  { number: "18", name: "Jaydon Blue", team: "Dallas Cowboys", section: "The Elite Series Rookies" },
  { number: "19", name: "Quinshon Judkins", team: "Cleveland Browns", section: "The Elite Series Rookies" },
  { number: "20", name: "Bhayshul Tuten", team: "Jacksonville Jaguars", section: "The Elite Series Rookies" },
  { number: "21", name: "Kyle Williams", team: "New England Patriots", section: "The Elite Series Rookies" },
  { number: "22", name: "Kalel Mullings", team: "Tennessee Titans", section: "The Elite Series Rookies" },
  { number: "23", name: "Tyler Warren", team: "Indianapolis Colts", section: "The Elite Series Rookies" },
  { number: "24", name: "Elic Ayomanor", team: "Tennessee Titans", section: "The Elite Series Rookies" },
  { number: "25", name: "Jaylin Lane", team: "Washington Commanders", section: "The Elite Series Rookies" },
  { number: "26", name: "Mason Graham", team: "Cleveland Browns", section: "The Elite Series Rookies" },
  { number: "27", name: "Terrance Ferguson", team: "Los Angeles Rams", section: "The Elite Series Rookies" },
  { number: "28", name: "Pat Bryant", team: "Denver Broncos", section: "The Elite Series Rookies" },
  { number: "29", name: "Emeka Egbuka", team: "Tampa Bay Buccaneers", section: "The Elite Series Rookies" },
  { number: "30", name: "Jaxson Dart", team: "New York Giants", section: "The Elite Series Rookies" },
  { number: "1", name: "Peyton Manning", team: "Indianapolis Colts", section: "The Legends Series" },
  { number: "2", name: "Eric Allen", team: "Philadelphia Eagles", section: "The Legends Series" },
  { number: "3", name: "DeAngelo Hall", team: "Atlanta Falcons", section: "The Legends Series" },
  { number: "4", name: "Jim Hart", team: "St. Louis Cardinals", section: "The Legends Series" },
  { number: "5", name: "Jeremy Shockey", team: "New York Giants", section: "The Legends Series" },
  { number: "6", name: "Mike Singletary", team: "Chicago Bears", section: "The Legends Series" },
  { number: "7", name: "A.J. Green", team: "Cincinnati Bengals", section: "The Legends Series" },
  { number: "8", name: "Paul Warfield", team: "Cleveland Browns", section: "The Legends Series" },
  { number: "9", name: "Drew Pearson", team: "Dallas Cowboys", section: "The Legends Series" },
  { number: "10", name: "Rick Upchurch", team: "Denver Broncos", section: "The Legends Series" },
  { number: "11", name: "Mason Crosby", team: "Green Bay Packers", section: "The Legends Series" },
  { number: "12", name: "Jeff Saturday", team: "Indianapolis Colts", section: "The Legends Series" },
  { number: "13", name: "Jan Stenerud", team: "Kansas City Chiefs", section: "The Legends Series" },
  { number: "14", name: "Raghib \"Rocket\" Ismail", team: "Los Angeles Raiders", section: "The Legends Series" },
  { number: "15", name: "Kellen Winslow", team: "San Diego Chargers", section: "The Legends Series" },
  { number: "16", name: "Joey Porter", team: "Pittsburgh Steelers", section: "The Legends Series" },
  { number: "17", name: "Rodney Harrison", team: "New England Patriots", section: "The Legends Series" },
  { number: "18", name: "Jimmy Graham", team: "New Orleans Saints", section: "The Legends Series" },
  { number: "19", name: "Gerald McCoy", team: "Tampa Bay Buccaneers", section: "The Legends Series" },
  { number: "20", name: "John Brodie", team: "San Francisco 49ers", section: "The Legends Series" },
  { number: "1", name: "Cam Ward", team: "Tennessee Titans", section: "The Rookies" },
  { number: "2", name: "Jaxson Dart", team: "New York Giants", section: "The Rookies" },
  { number: "3", name: "Travis Hunter", team: "Jacksonville Jaguars", section: "The Rookies" },
  { number: "4", name: "Abdul Carter", team: "New York Giants", section: "The Rookies" },
  { number: "5", name: "Shedeur Sanders", team: "Cleveland Browns", section: "The Rookies" },
  { number: "6", name: "Quinn Ewers", team: "Miami Dolphins", section: "The Rookies" },
  { number: "7", name: "Ashton Jeanty", team: "Las Vegas Raiders", section: "The Rookies" },
  { number: "8", name: "Omarion Hampton", team: "Los Angeles Chargers", section: "The Rookies" },
  { number: "9", name: "Tyler Warren", team: "Indianapolis Colts", section: "The Rookies" },
  { number: "10", name: "Will Howard", team: "Pittsburgh Steelers", section: "The Rookies" },
  { number: "11", name: "Jayden Higgins", team: "Houston Texans", section: "The Rookies" },
  { number: "12", name: "Jalen Milroe", team: "Seattle Seahawks", section: "The Rookies" },
  { number: "13", name: "Pat Bryant", team: "Denver Broncos", section: "The Rookies" },
  { number: "14", name: "Colston Loveland", team: "Chicago Bears", section: "The Rookies" },
  { number: "15", name: "Jack Bech", team: "Las Vegas Raiders", section: "The Rookies" },
  { number: "16", name: "TreVeyon Henderson", team: "New England Patriots", section: "The Rookies" },
  { number: "17", name: "Tyler Shough", team: "New Orleans Saints", section: "The Rookies" },
  { number: "18", name: "Matthew Golden", team: "Green Bay Packers", section: "The Rookies" },
  { number: "19", name: "Cam Skattebo", team: "New York Giants", section: "The Rookies" },
  { number: "20", name: "Kalel Mullings", team: "Tennessee Titans", section: "The Rookies" },
  { number: "21", name: "Chimere Dike", team: "Tennessee Titans", section: "The Rookies" },
  { number: "22", name: "Elijah Arroyo", team: "Seattle Seahawks", section: "The Rookies" },
  { number: "23", name: "Kyle McCord", team: "Philadelphia Eagles", section: "The Rookies" },
  { number: "24", name: "Mason Taylor", team: "New York Jets", section: "The Rookies" },
  { number: "25", name: "Kyle Williams", team: "New England Patriots", section: "The Rookies" },
  { number: "26", name: "Quinshon Judkins", team: "Cleveland Browns", section: "The Rookies" },
  { number: "27", name: "Jalen Royals", team: "Kansas City Chiefs", section: "The Rookies" },
  { number: "28", name: "Riley Leonard", team: "Indianapolis Colts", section: "The Rookies" },
  { number: "29", name: "Tre Harris", team: "Los Angeles Chargers", section: "The Rookies" },
  { number: "30", name: "Jaylin Noel", team: "Houston Texans", section: "The Rookies" },
  { number: "31", name: "Emeka Egbuka", team: "Tampa Bay Buccaneers", section: "The Rookies" },
  { number: "32", name: "RJ Harvey", team: "Denver Broncos", section: "The Rookies" },
  { number: "33", name: "Dillon Gabriel", team: "Cleveland Browns", section: "The Rookies" },
  { number: "34", name: "Tetairoa McMillan", team: "Carolina Panthers", section: "The Rookies" },
  { number: "35", name: "Isaac TeSlaa", team: "Detroit Lions", section: "The Rookies" },
  { number: "36", name: "Savion Williams", team: "Green Bay Packers", section: "The Rookies" },
  { number: "37", name: "Elic Ayomanor", team: "Tennessee Titans", section: "The Rookies" },
  { number: "38", name: "Jaylin Lane", team: "Washington Commanders", section: "The Rookies" },
  { number: "39", name: "Tai Felton", team: "Minnesota Vikings", section: "The Rookies" },
  { number: "40", name: "Luther Burden III", team: "Chicago Bears", section: "The Rookies" },
  { number: "1", name: "Rome Odunze", team: "Chicago Bears", section: "Unleashed" },
  { number: "2", name: "Jayden Daniels", team: "Washington Commanders", section: "Unleashed" },
  { number: "3", name: "Bo Nix", team: "Denver Broncos", section: "Unleashed" },
  { number: "4", name: "Brock Bowers", team: "Las Vegas Raiders", section: "Unleashed" },
  { number: "5", name: "Malik Nabers", team: "New York Giants", section: "Unleashed" },
  { number: "6", name: "Tee Higgins", team: "Cincinnati Bengals", section: "Unleashed" },
  { number: "7", name: "Marvin Harrison Jr.", team: "Arizona Cardinals", section: "Unleashed" },
  { number: "8", name: "Tank Bigsby", team: "Jacksonville Jaguars", section: "Unleashed" },
  { number: "9", name: "Chuba Hubbard", team: "Carolina Panthers", section: "Unleashed" },
  { number: "10", name: "Drake Maye", team: "New England Patriots", section: "Unleashed" },
  { number: "11", name: "Jared Verse", team: "Los Angeles Rams", section: "Unleashed" },
  { number: "12", name: "Jahmyr Gibbs", team: "Detroit Lions", section: "Unleashed" },
  { number: "13", name: "Michael Penix Jr.", team: "Atlanta Falcons", section: "Unleashed" },
  { number: "14", name: "Jordan Addison", team: "Minnesota Vikings", section: "Unleashed" },
  { number: "15", name: "Jalen Hurts", team: "Philadelphia Eagles", section: "Unleashed" },
  { number: "16", name: "Zay Flowers", team: "Baltimore Ravens", section: "Unleashed" },
  { number: "17", name: "Xavier Worthy", team: "Kansas City Chiefs", section: "Unleashed" },
  { number: "18", name: "Jonathan Taylor", team: "Indianapolis Colts", section: "Unleashed" },
  { number: "19", name: "James Cook", team: "Buffalo Bills", section: "Unleashed" },
  { number: "20", name: "Nico Collins", team: "Houston Texans", section: "Unleashed" },
  { number: "21", name: "De'Von Achane", team: "Miami Dolphins", section: "Unleashed" },
  { number: "22", name: "George Kittle", team: "San Francisco 49ers", section: "Unleashed" },
  { number: "23", name: "Jaxon Smith-Njigba", team: "Seattle Seahawks", section: "Unleashed" },
  { number: "24", name: "Bucky Irving", team: "Tampa Bay Buccaneers", section: "Unleashed" },
  { number: "25", name: "Caleb Williams", team: "Chicago Bears", section: "Unleashed" },
  { number: "1", name: "Omarion Hampton", team: "Los Angeles Chargers", section: "Galactic" },
  { number: "2", name: "Shedeur Sanders", team: "Cleveland Browns", section: "Galactic" },
  { number: "3", name: "Travis Hunter", team: "Jacksonville Jaguars", section: "Galactic" },
  { number: "4", name: "TreVeyon Henderson", team: "New England Patriots", section: "Galactic" },
  { number: "5", name: "Kalel Mullings", team: "Tennessee Titans", section: "Galactic" },
  { number: "6", name: "Luther Burden III", team: "Chicago Bears", section: "Galactic" },
  { number: "7", name: "Tetairoa McMillan", team: "Carolina Panthers", section: "Galactic" },
  { number: "8", name: "Jack Bech", team: "Las Vegas Raiders", section: "Galactic" },
  { number: "9", name: "Dillon Gabriel", team: "Cleveland Browns", section: "Galactic" },
  { number: "10", name: "Tyler Warren", team: "Indianapolis Colts", section: "Galactic" },
  { number: "11", name: "Abdul Carter", team: "New York Giants", section: "Galactic" },
  { number: "12", name: "Jalen Milroe", team: "Seattle Seahawks", section: "Galactic" },
  { number: "13", name: "Jaxson Dart", team: "New York Giants", section: "Galactic" },
  { number: "14", name: "Matthew Golden", team: "Green Bay Packers", section: "Galactic" },
  { number: "15", name: "Jayden Higgins", team: "Houston Texans", section: "Galactic" },
  { number: "16", name: "Quinshon Judkins", team: "Cleveland Browns", section: "Galactic" },
  { number: "17", name: "Cam Ward", team: "Tennessee Titans", section: "Galactic" },
  { number: "18", name: "Tyler Shough", team: "New Orleans Saints", section: "Galactic" },
  { number: "19", name: "Colston Loveland", team: "Chicago Bears", section: "Galactic" },
  { number: "20", name: "RJ Harvey", team: "Denver Broncos", section: "Galactic" },
  { number: "21", name: "Tre Harris", team: "Los Angeles Chargers", section: "Galactic" },
  { number: "22", name: "Mykel Williams", team: "San Francisco 49ers", section: "Galactic" },
  { number: "23", name: "Cam Skattebo", team: "New York Giants", section: "Galactic" },
  { number: "24", name: "Ashton Jeanty", team: "Las Vegas Raiders", section: "Galactic" },
  { number: "25", name: "Emeka Egbuka", team: "Tampa Bay Buccaneers", section: "Galactic" },
  { number: "1", name: "Cam Ward", team: "Tennessee Titans", section: "White Hot Rookies" },
  { number: "2", name: "Ashton Jeanty", team: "Las Vegas Raiders", section: "White Hot Rookies" },
  { number: "3", name: "Matthew Golden", team: "Green Bay Packers", section: "White Hot Rookies" },
  { number: "4", name: "Abdul Carter", team: "New York Giants", section: "White Hot Rookies" },
  { number: "5", name: "Travis Hunter", team: "Jacksonville Jaguars", section: "White Hot Rookies" },
  { number: "6", name: "Jalen Milroe", team: "Seattle Seahawks", section: "White Hot Rookies" },
  { number: "7", name: "Tyler Warren", team: "Indianapolis Colts", section: "White Hot Rookies" },
  { number: "8", name: "Omarion Hampton", team: "Los Angeles Chargers", section: "White Hot Rookies" },
  { number: "9", name: "Luther Burden III", team: "Chicago Bears", section: "White Hot Rookies" },
  { number: "10", name: "Jaxson Dart", team: "New York Giants", section: "White Hot Rookies" },
];