export type Prizm2025InsertsEntry = {
  number: string;
  name: string;
  team?: string;
  section: string;
};

export const PRIZM_2025_INSERTS: Prizm2025InsertsEntry[] = [
  { number: "1", name: "Saquon Barkley", team: "Philadelphia Eagles", section: "All Purpose Prizms Silver" },
  { number: "2", name: "Derrick Henry", team: "Baltimore Ravens", section: "All Purpose Prizms Silver" },
  { number: "3", name: "Jahmyr Gibbs", team: "Detroit Lions", section: "All Purpose Prizms Silver" },
  { number: "4", name: "Bijan Robinson", team: "Atlanta Falcons", section: "All Purpose Prizms Silver" },
  { number: "5", name: "Ja'Marr Chase", team: "Cincinnati Bengals", section: "All Purpose Prizms Silver" },
  { number: "6", name: "Josh Jacobs", team: "Green Bay Packers", section: "All Purpose Prizms Silver" },
  { number: "7", name: "Jonathan Taylor", team: "Indianapolis Colts", section: "All Purpose Prizms Silver" },
  { number: "8", name: "Aaron Jones", team: "Minnesota Vikings", section: "All Purpose Prizms Silver" },
  { number: "9", name: "KaVontae Turpin", team: "Dallas Cowboys", section: "All Purpose Prizms Silver" },
  { number: "10", name: "Bucky Irving", team: "Tampa Bay Buccaneers", section: "All Purpose Prizms Silver" },
  { number: "11", name: "Emmitt Smith", team: "Dallas Cowboys", section: "All Purpose Prizms Silver" },
  { number: "12", name: "Brian Mitchell", team: "Washington Redskins", section: "All Purpose Prizms Silver" },
  { number: "13", name: "Tim Brown", team: "Oakland Raiders", section: "All Purpose Prizms Silver" },
  { number: "14", name: "Cordarrelle Patterson", team: "Minnesota Vikings", section: "All Purpose Prizms Silver" },
  { number: "15", name: "Adrian Peterson", team: "Minnesota Vikings", section: "All Purpose Prizms Silver" },
  { number: "16", name: "Larry Fitzgerald", team: "Arizona Cardinals", section: "All Purpose Prizms Silver" },
  { number: "17", name: "Chris Johnson", team: "Tennessee Titans", section: "All Purpose Prizms Silver" },
  { number: "18", name: "Calvin Johnson", team: "Detroit Lions", section: "All Purpose Prizms Silver" },
  { number: "19", name: "Devin Hester", team: "Chicago Bears", section: "All Purpose Prizms Silver" },
  { number: "20", name: "Lamar Jackson", team: "Baltimore Ravens", section: "All Purpose Prizms Silver" },
  { number: "1", name: "Bijan Robinson", team: "Atlanta Falcons", section: "Color Blast" },
  { number: "2", name: "Derrick Henry", team: "Baltimore Ravens", section: "Color Blast" },
  { number: "3", name: "Tetairoa McMillan", team: "Carolina Panthers", section: "Color Blast" },
  { number: "4", name: "Ja'Marr Chase", team: "Cincinnati Bengals", section: "Color Blast" },
  { number: "5", name: "Joe Burrow", team: "Cincinnati Bengals", section: "Color Blast" },
  { number: "6", name: "Dillon Gabriel", team: "Cleveland Browns", section: "Color Blast" },
  { number: "7", name: "Quinshon Judkins", team: "Cleveland Browns", section: "Color Blast" },
  { number: "8", name: "Shedeur Sanders", team: "Cleveland Browns", section: "Color Blast" },
  { number: "9", name: "CeeDee Lamb", team: "Dallas Cowboys", section: "Color Blast" },
  { number: "10", name: "RJ Harvey", team: "Denver Broncos", section: "Color Blast" },
  { number: "11", name: "Jared Goff", team: "Detroit Lions", section: "Color Blast" },
  { number: "12", name: "Matthew Golden", team: "Green Bay Packers", section: "Color Blast" },
  { number: "13", name: "Jayden Higgins", team: "Houston Texans", section: "Color Blast" },
  { number: "14", name: "Tyler Warren", team: "Indianapolis Colts", section: "Color Blast" },
  { number: "15", name: "Travis Hunter", team: "Jacksonville Jaguars", section: "Color Blast" },
  { number: "16", name: "Ashton Jeanty", team: "Las Vegas Raiders", section: "Color Blast" },
  { number: "17", name: "Justin Herbert", team: "Los Angeles Chargers", section: "Color Blast" },
  { number: "18", name: "Puka Nacua", team: "Los Angeles Rams", section: "Color Blast" },
  { number: "19", name: "Sean Taylor", team: "Washington Redskins", section: "Color Blast" },
  { number: "20", name: "TreVeyon Henderson", team: "New England Patriots", section: "Color Blast" },
  { number: "21", name: "Tyler Shough", team: "New Orleans Saints", section: "Color Blast" },
  { number: "22", name: "Jaxson Dart", team: "New York Giants", section: "Color Blast" },
  { number: "23", name: "Cam Skattebo", team: "New York Giants", section: "Color Blast" },
  { number: "24", name: "Justin Fields", team: "New York Jets", section: "Color Blast" },
  { number: "25", name: "Jalen Hurts", team: "Philadelphia Eagles", section: "Color Blast" },
  { number: "26", name: "Kaleb Johnson", team: "Pittsburgh Steelers", section: "Color Blast" },
  { number: "27", name: "Christian McCaffrey", team: "San Francisco 49ers", section: "Color Blast" },
  { number: "28", name: "Jalen Milroe", team: "Seattle Seahawks", section: "Color Blast" },
  { number: "29", name: "Bucky Irving", team: "Tampa Bay Buccaneers", section: "Color Blast" },
  { number: "30", name: "Cam Ward", team: "Tennessee Titans", section: "Color Blast" },
  { number: "1", name: "Jordan Love/Matthew Golden", team: "Green Bay Packers", section: "Color Blast Duals" },
  { number: "2", name: "Justin Herbert/Omarion Hampton", team: "Los Angeles Chargers", section: "Color Blast Duals" },
  { number: "3", name: "Calvin Ridley/Cam Ward", team: "Tennessee Titans", section: "Color Blast Duals" },
  { number: "4", name: "Brian Thomas Jr./Travis Hunter", team: "Jacksonville Jaguars", section: "Color Blast Duals" },
  { number: "5", name: "Abdul Carter/Jaxson Dart", team: "New York Giants", section: "Color Blast Duals" },
  { number: "6", name: "Derrick Henry/Lamar Jackson", team: "Baltimore Ravens", section: "Color Blast Duals" },
  { number: "7", name: "Patrick Mahomes II/Travis Kelce", team: "Kansas City Chiefs", section: "Color Blast Duals" },
  { number: "8", name: "Quinshon Judkins/Shedeur Sanders", team: "Cleveland Browns", section: "Color Blast Duals" },
  { number: "9", name: "Ashton Jeanty/Jack Bech", team: "Las Vegas Raiders", section: "Color Blast Duals" },
  { number: "10", name: "Ja'Marr Chase/Joe Burrow", team: "Cincinnati Bengals", section: "Color Blast Duals" },
  { number: "1", name: "Cam Skattebo", team: "New York Giants", section: "Emergent" },
  { number: "2", name: "Cam Ward", team: "Tennessee Titans", section: "Emergent" },
  { number: "3", name: "Emeka Egbuka", team: "Tampa Bay Buccaneers", section: "Emergent" },
  { number: "4", name: "Jalen Milroe", team: "Seattle Seahawks", section: "Emergent" },
  { number: "5", name: "Kaleb Johnson", team: "Pittsburgh Steelers", section: "Emergent" },
  { number: "6", name: "Jaxson Dart", team: "New York Giants", section: "Emergent" },
  { number: "7", name: "Abdul Carter", team: "New York Giants", section: "Emergent" },
  { number: "8", name: "Tyler Shough", team: "New Orleans Saints", section: "Emergent" },
  { number: "9", name: "Omarion Hampton", team: "Los Angeles Chargers", section: "Emergent" },
  { number: "10", name: "Ashton Jeanty", team: "Las Vegas Raiders", section: "Emergent" },
  { number: "11", name: "Jack Bech", team: "Las Vegas Raiders", section: "Emergent" },
  { number: "12", name: "Travis Hunter", team: "Jacksonville Jaguars", section: "Emergent" },
  { number: "13", name: "Tyler Warren", team: "Indianapolis Colts", section: "Emergent" },
  { number: "14", name: "Jayden Higgins", team: "Houston Texans", section: "Emergent" },
  { number: "15", name: "Matthew Golden", team: "Green Bay Packers", section: "Emergent" },
  { number: "16", name: "RJ Harvey", team: "Denver Broncos", section: "Emergent" },
  { number: "17", name: "Shedeur Sanders", team: "Cleveland Browns", section: "Emergent" },
  { number: "18", name: "Dillon Gabriel", team: "Cleveland Browns", section: "Emergent" },
  { number: "19", name: "Luther Burden III", team: "Chicago Bears", section: "Emergent" },
  { number: "20", name: "Colston Loveland", team: "Chicago Bears", section: "Emergent" },
  { number: "1", name: "Cam Ward", team: "Tennessee Titans", section: "Fireworks" },
  { number: "2", name: "Emeka Egbuka", team: "Tampa Bay Buccaneers", section: "Fireworks" },
  { number: "3", name: "Sam Darnold", team: "Seattle Seahawks", section: "Fireworks" },
  { number: "4", name: "Kaleb Johnson", team: "Pittsburgh Steelers", section: "Fireworks" },
  { number: "5", name: "Jalen Hurts", team: "Philadelphia Eagles", section: "Fireworks" },
  { number: "6", name: "Jaxson Dart", team: "New York Giants", section: "Fireworks" },
  { number: "7", name: "Abdul Carter", team: "New York Giants", section: "Fireworks" },
  { number: "8", name: "Jordan Addison", team: "Minnesota Vikings", section: "Fireworks" },
  { number: "9", name: "Tua Tagovailoa", team: "Miami Dolphins", section: "Fireworks" },
  { number: "10", name: "Ashton Jeanty", team: "Las Vegas Raiders", section: "Fireworks" },
  { number: "11", name: "Brock Bowers", team: "Las Vegas Raiders", section: "Fireworks" },
  { number: "12", name: "Tyler Warren", team: "Indianapolis Colts", section: "Fireworks" },
  { number: "13", name: "Travis Hunter", team: "Jacksonville Jaguars", section: "Fireworks" },
  { number: "14", name: "Brian Thomas Jr.", team: "Jacksonville Jaguars", section: "Fireworks" },
  { number: "15", name: "Matthew Golden", team: "Green Bay Packers", section: "Fireworks" },
  { number: "16", name: "Amon-Ra St. Brown", team: "Detroit Lions", section: "Fireworks" },
  { number: "17", name: "Omarion Hampton", team: "Los Angeles Chargers", section: "Fireworks" },
  { number: "18", name: "Micah Parsons", team: "Dallas Cowboys", section: "Fireworks" },
  { number: "19", name: "Quinshon Judkins", team: "Cleveland Browns", section: "Fireworks" },
  { number: "20", name: "Luther Burden III", team: "Chicago Bears", section: "Fireworks" },
  { number: "21", name: "Tetairoa McMillan", team: "Carolina Panthers", section: "Fireworks" },
  { number: "22", name: "Lamar Jackson", team: "Baltimore Ravens", section: "Fireworks" },
  { number: "23", name: "Josh Allen", team: "Buffalo Bills", section: "Fireworks" },
  { number: "24", name: "TreVeyon Henderson", team: "New England Patriots", section: "Fireworks" },
  { number: "25", name: "Joe Burrow", team: "Cincinnati Bengals", section: "Fireworks" },
  { number: "1", name: "Jayden Daniels", team: "Washington Commanders", section: "Fractal" },
  { number: "2", name: "Lamar Jackson", team: "Baltimore Ravens", section: "Fractal" },
  { number: "3", name: "Malik Nabers", team: "New York Giants", section: "Fractal" },
  { number: "4", name: "Caleb Williams", team: "Chicago Bears", section: "Fractal" },
  { number: "5", name: "Patrick Mahomes II", team: "Kansas City Chiefs", section: "Fractal" },
  { number: "6", name: "Brock Bowers", team: "Las Vegas Raiders", section: "Fractal" },
  { number: "7", name: "Drake Maye", team: "New England Patriots", section: "Fractal" },
  { number: "8", name: "Joe Burrow", team: "Cincinnati Bengals", section: "Fractal" },
  { number: "9", name: "Brian Thomas Jr.", team: "Jacksonville Jaguars", section: "Fractal" },
  { number: "10", name: "Michael Penix Jr.", team: "Atlanta Falcons", section: "Fractal" },
  { number: "11", name: "Cam Ward", team: "Tennessee Titans", section: "Fractal" },
  { number: "12", name: "Marvin Harrison Jr.", team: "Arizona Cardinals", section: "Fractal" },
  { number: "13", name: "Bo Nix", team: "Denver Broncos", section: "Fractal" },
  { number: "14", name: "Josh Allen", team: "Buffalo Bills", section: "Fractal" },
  { number: "15", name: "J.J. McCarthy", team: "Minnesota Vikings", section: "Fractal" },
  { number: "1", name: "Saquon Barkley", team: "Philadelphia Eagles", section: "Global Reach" },
  { number: "2", name: "Jayden Reed", team: "Green Bay Packers", section: "Global Reach" },
  { number: "3", name: "Andrew Van Ginkel", team: "Minnesota Vikings", section: "Global Reach" },
  { number: "4", name: "Will Reichard", team: "Minnesota Vikings", section: "Global Reach" },
  { number: "5", name: "Caleb Williams", team: "Chicago Bears", section: "Global Reach" },
  { number: "6", name: "Cole Kmet", team: "Chicago Bears", section: "Global Reach" },
  { number: "7", name: "Tank Bigsby", team: "Jacksonville Jaguars", section: "Global Reach" },
  { number: "8", name: "Brian Thomas Jr.", team: "Jacksonville Jaguars", section: "Global Reach" },
  { number: "9", name: "Chuba Hubbard", team: "Carolina Panthers", section: "Global Reach" },
  { number: "10", name: "Tyrone Tracy Jr.", team: "New York Giants", section: "Global Reach" },
  { number: "1", name: "Nik Bonitto", team: "Denver Broncos", section: "Lockdown! Prizms Silver" },
  { number: "2", name: "Tyrann Mathieu", team: "New Orleans Saints", section: "Lockdown! Prizms Silver" },
  { number: "3", name: "Dexter Lawrence", team: "New York Giants", section: "Lockdown! Prizms Silver" },
  { number: "4", name: "Patrick Surtain II", team: "Denver Broncos", section: "Lockdown! Prizms Silver" },
  { number: "5", name: "Cooper DeJean", team: "Philadelphia Eagles", section: "Lockdown! Prizms Silver" },
  { number: "6", name: "Chris Jones", team: "Kansas City Chiefs", section: "Lockdown! Prizms Silver" },
  { number: "7", name: "Kyle Hamilton", team: "Baltimore Ravens", section: "Lockdown! Prizms Silver" },
  { number: "8", name: "Roquan Smith", team: "Baltimore Ravens", section: "Lockdown! Prizms Silver" },
  { number: "9", name: "Greg Rousseau", team: "Buffalo Bills", section: "Lockdown! Prizms Silver" },
  { number: "10", name: "Christian Gonzalez", team: "New England Patriots", section: "Lockdown! Prizms Silver" },
  { number: "11", name: "Patrick Queen", team: "Pittsburgh Steelers", section: "Lockdown! Prizms Silver" },
  { number: "12", name: "Will Anderson Jr.", team: "Houston Texans", section: "Lockdown! Prizms Silver" },
  { number: "13", name: "Josh Hines-Allen", team: "Jacksonville Jaguars", section: "Lockdown! Prizms Silver" },
  { number: "14", name: "Marshon Lattimore", team: "Washington Commanders", section: "Lockdown! Prizms Silver" },
  { number: "15", name: "Derwin James Jr.", team: "Los Angeles Chargers", section: "Lockdown! Prizms Silver" },
  { number: "16", name: "Jared Verse", team: "Los Angeles Rams", section: "Lockdown! Prizms Silver" },
  { number: "17", name: "Jalen Carter", team: "Philadelphia Eagles", section: "Lockdown! Prizms Silver" },
  { number: "18", name: "Fred Warner", team: "San Francisco 49ers", section: "Lockdown! Prizms Silver" },
  { number: "1", name: "Jayden Daniels", team: "Washington Commanders", section: "Manga - Horizontal" },
  { number: "2", name: "Saquon Barkley", team: "Philadelphia Eagles", section: "Manga - Horizontal" },
  { number: "3", name: "Micah Parsons", team: "Dallas Cowboys", section: "Manga - Horizontal" },
  { number: "4", name: "Maxx Crosby", team: "Las Vegas Raiders", section: "Manga - Horizontal" },
  { number: "5", name: "Bo Nix", team: "Denver Broncos", section: "Manga - Horizontal" },
  { number: "6", name: "Randy Moss", team: "Minnesota Vikings", section: "Manga - Horizontal" },
  { number: "7", name: "Sean Taylor", team: "Washington Redskins", section: "Manga - Horizontal" },
  { number: "8", name: "Joe Montana", team: "San Francisco 49ers", section: "Manga - Horizontal" },
  { number: "9", name: "Joe Namath", team: "New York Jets", section: "Manga - Horizontal" },
  { number: "10", name: "Cam Ward", team: "Tennessee Titans", section: "Manga - Horizontal" },
  { number: "11", name: "Ashton Jeanty", team: "Las Vegas Raiders", section: "Manga - Horizontal" },
  { number: "12", name: "Travis Hunter", team: "Jacksonville Jaguars", section: "Manga - Horizontal" },
  { number: "13", name: "Tetairoa McMillan", team: "Carolina Panthers", section: "Manga - Horizontal" },
  { number: "14", name: "Jaxson Dart", team: "New York Giants", section: "Manga - Horizontal" },
  { number: "15", name: "Matthew Golden", team: "Green Bay Packers", section: "Manga - Horizontal" },
  { number: "1", name: "Patrick Mahomes II", team: "Kansas City Chiefs", section: "Manga - Vertical" },
  { number: "2", name: "Jalen Hurts", team: "Philadelphia Eagles", section: "Manga - Vertical" },
  { number: "3", name: "Lamar Jackson", team: "Baltimore Ravens", section: "Manga - Vertical" },
  { number: "4", name: "Calvin Johnson", team: "Detroit Lions", section: "Manga - Vertical" },
  { number: "5", name: "Emmitt Smith", team: "Dallas Cowboys", section: "Manga - Vertical" },
  { number: "6", name: "Larry Fitzgerald", team: "Arizona Cardinals", section: "Manga - Vertical" },
  { number: "7", name: "Justin Jefferson", team: "Minnesota Vikings", section: "Manga - Vertical" },
  { number: "8", name: "Ja'Marr Chase", team: "Cincinnati Bengals", section: "Manga - Vertical" },
  { number: "9", name: "Joe Burrow", team: "Cincinnati Bengals", section: "Manga - Vertical" },
  { number: "10", name: "Josh Allen", team: "Buffalo Bills", section: "Manga - Vertical" },
  { number: "11", name: "Tyler Shough", team: "New Orleans Saints", section: "Manga - Vertical" },
  { number: "12", name: "Shedeur Sanders", team: "Cleveland Browns", section: "Manga - Vertical" },
  { number: "13", name: "Omarion Hampton", team: "Los Angeles Chargers", section: "Manga - Vertical" },
  { number: "14", name: "Luther Burden III", team: "Chicago Bears", section: "Manga - Vertical" },
  { number: "15", name: "Emeka Egbuka", team: "Tampa Bay Buccaneers", section: "Manga - Vertical" },
  { number: "1", name: "Trevor Lawrence", team: "Jacksonville Jaguars", section: "Prizm Break" },
  { number: "2", name: "Jayden Daniels", team: "Washington Commanders", section: "Prizm Break" },
  { number: "3", name: "Caleb Williams", team: "Chicago Bears", section: "Prizm Break" },
  { number: "4", name: "Brock Bowers", team: "Las Vegas Raiders", section: "Prizm Break" },
  { number: "5", name: "Malik Nabers", team: "New York Giants", section: "Prizm Break" },
  { number: "6", name: "Drake Maye", team: "New England Patriots", section: "Prizm Break" },
  { number: "7", name: "Brian Thomas Jr.", team: "Jacksonville Jaguars", section: "Prizm Break" },
  { number: "8", name: "Patrick Mahomes II", team: "Kansas City Chiefs", section: "Prizm Break" },
  { number: "9", name: "Saquon Barkley", team: "Philadelphia Eagles", section: "Prizm Break" },
  { number: "10", name: "Davante Adams", team: "Los Angeles Rams", section: "Prizm Break" },
  { number: "1", name: "Lamar Jackson", team: "Baltimore Ravens", section: "Prizm Flashback Prizms Silver" },
  { number: "2", name: "Joe Burrow", team: "Cincinnati Bengals", section: "Prizm Flashback Prizms Silver" },
  { number: "3", name: "Jayden Daniels", team: "Washington Commanders", section: "Prizm Flashback Prizms Silver" },
  { number: "4", name: "Saquon Barkley", team: "Philadelphia Eagles", section: "Prizm Flashback Prizms Silver" },
  { number: "5", name: "Amon-Ra St. Brown", team: "Detroit Lions", section: "Prizm Flashback Prizms Silver" },
  { number: "6", name: "Bo Nix", team: "Denver Broncos", section: "Prizm Flashback Prizms Silver" },
  { number: "7", name: "Caleb Williams", team: "Chicago Bears", section: "Prizm Flashback Prizms Silver" },
  { number: "8", name: "Drake Maye", team: "New England Patriots", section: "Prizm Flashback Prizms Silver" },
  { number: "9", name: "Ja'Marr Chase", team: "Cincinnati Bengals", section: "Prizm Flashback Prizms Silver" },
  { number: "10", name: "Malik Nabers", team: "New York Giants", section: "Prizm Flashback Prizms Silver" },
  { number: "1", name: "Cam Ward", team: "Tennessee Titans", section: "Prizm Flashback Rookie Prizms Silver" },
  { number: "2", name: "Travis Hunter", team: "Jacksonville Jaguars", section: "Prizm Flashback Rookie Prizms Silver" },
  { number: "3", name: "Abdul Carter", team: "New York Giants", section: "Prizm Flashback Rookie Prizms Silver" },
  { number: "4", name: "Tetairoa McMillan", team: "Carolina Panthers", section: "Prizm Flashback Rookie Prizms Silver" },
  { number: "5", name: "Colston Loveland", team: "Chicago Bears", section: "Prizm Flashback Rookie Prizms Silver" },
  { number: "6", name: "Tyler Warren", team: "Indianapolis Colts", section: "Prizm Flashback Rookie Prizms Silver" },
  { number: "7", name: "Emeka Egbuka", team: "Tampa Bay Buccaneers", section: "Prizm Flashback Rookie Prizms Silver" },
  { number: "8", name: "Matthew Golden", team: "Green Bay Packers", section: "Prizm Flashback Rookie Prizms Silver" },
  { number: "9", name: "Omarion Hampton", team: "Los Angeles Chargers", section: "Prizm Flashback Rookie Prizms Silver" },
  { number: "10", name: "Jaxson Dart", team: "New York Giants", section: "Prizm Flashback Rookie Prizms Silver" },
  { number: "1", name: "Trey McBride", team: "Arizona Cardinals", section: "Prizmania" },
  { number: "2", name: "Michael Vick", team: "Atlanta Falcons", section: "Prizmania" },
  { number: "3", name: "Derrick Henry", team: "Baltimore Ravens", section: "Prizmania" },
  { number: "4", name: "Josh Allen", team: "Buffalo Bills", section: "Prizmania" },
  { number: "5", name: "Tetairoa McMillan", team: "Carolina Panthers", section: "Prizmania" },
  { number: "6", name: "Joe Burrow", team: "Cincinnati Bengals", section: "Prizmania" },
  { number: "7", name: "Shedeur Sanders", team: "Cleveland Browns", section: "Prizmania" },
  { number: "8", name: "Dak Prescott", team: "Dallas Cowboys", section: "Prizmania" },
  { number: "9", name: "RJ Harvey", team: "Denver Broncos", section: "Prizmania" },
  { number: "10", name: "Jared Goff", team: "Detroit Lions", section: "Prizmania" },
  { number: "11", name: "Matthew Golden", team: "Green Bay Packers", section: "Prizmania" },
  { number: "12", name: "Nico Collins", team: "Houston Texans", section: "Prizmania" },
  { number: "13", name: "Jonathan Taylor", team: "Indianapolis Colts", section: "Prizmania" },
  { number: "14", name: "Travis Hunter", team: "Jacksonville Jaguars", section: "Prizmania" },
  { number: "15", name: "Travis Kelce", team: "Kansas City Chiefs", section: "Prizmania" },
  { number: "16", name: "Ashton Jeanty", team: "Las Vegas Raiders", section: "Prizmania" },
  { number: "17", name: "Brock Bowers", team: "Las Vegas Raiders", section: "Prizmania" },
  { number: "18", name: "Omarion Hampton", team: "Los Angeles Chargers", section: "Prizmania" },
  { number: "19", name: "Puka Nacua", team: "Los Angeles Rams", section: "Prizmania" },
  { number: "20", name: "Tyreek Hill", team: "Miami Dolphins", section: "Prizmania" },
  { number: "21", name: "Justin Jefferson", team: "Minnesota Vikings", section: "Prizmania" },
  { number: "22", name: "Tyler Shough", team: "New Orleans Saints", section: "Prizmania" },
  { number: "23", name: "Jaxson Dart", team: "New York Giants", section: "Prizmania" },
  { number: "24", name: "Jalen Hurts", team: "Philadelphia Eagles", section: "Prizmania" },
  { number: "25", name: "Saquon Barkley", team: "Philadelphia Eagles", section: "Prizmania" },
  { number: "26", name: "Ben Roethlisberger", team: "Pittsburgh Steelers", section: "Prizmania" },
  { number: "27", name: "Brock Purdy", team: "San Francisco 49ers", section: "Prizmania" },
  { number: "28", name: "Emeka Egbuka", team: "Tampa Bay Buccaneers", section: "Prizmania" },
  { number: "29", name: "Cam Ward", team: "Tennessee Titans", section: "Prizmania" },
  { number: "30", name: "Jalen Milroe", team: "Seattle Seahawks", section: "Prizmania" },
  { number: "1", name: "Tetairoa McMillan", team: "Carolina Panthers", section: "Prizmatic" },
  { number: "2", name: "Randy Moss", team: "Minnesota Vikings", section: "Prizmatic" },
  { number: "3", name: "Jayden Higgins", team: "Houston Texans", section: "Prizmatic" },
  { number: "4", name: "Cam Ward", team: "Tennessee Titans", section: "Prizmatic" },
  { number: "5", name: "Joe Montana", team: "San Francisco 49ers", section: "Prizmatic" },
  { number: "6", name: "Jaxson Dart", team: "New York Giants", section: "Prizmatic" },
  { number: "7", name: "Ashton Jeanty", team: "Las Vegas Raiders", section: "Prizmatic" },
  { number: "8", name: "Emmitt Smith", team: "Dallas Cowboys", section: "Prizmatic" },
  { number: "9", name: "Omarion Hampton", team: "Los Angeles Chargers", section: "Prizmatic" },
  { number: "10", name: "Abdul Carter", team: "New York Giants", section: "Prizmatic" },
  { number: "11", name: "Sean Taylor", team: "Washington Redskins", section: "Prizmatic" },
  { number: "12", name: "Travis Hunter", team: "Jacksonville Jaguars", section: "Prizmatic" },
  { number: "13", name: "Emeka Egbuka", team: "Tampa Bay Buccaneers", section: "Prizmatic" },
  { number: "14", name: "Larry Fitzgerald", team: "Arizona Cardinals", section: "Prizmatic" },
  { number: "15", name: "Tyler Warren", team: "Indianapolis Colts", section: "Prizmatic" },
  { number: "16", name: "Tyler Shough", team: "New Orleans Saints", section: "Prizmatic" },
  { number: "17", name: "Calvin Johnson", team: "Detroit Lions", section: "Prizmatic" },
  { number: "18", name: "Luther Burden III", team: "Chicago Bears", section: "Prizmatic" },
  { number: "19", name: "Barry Sanders", team: "Detroit Lions", section: "Prizmatic" },
  { number: "20", name: "Colston Loveland", team: "Chicago Bears", section: "Prizmatic" },
];