export type Prizm2025MemorabiliaEntry = {
  number: string;
  name: string;
  team?: string;
  section: string;
};

export const PRIZM_2025_MEMORABILIA: Prizm2025MemorabiliaEntry[] = [
  { number: "1", name: "Marvin Harrison Jr.", team: "Arizona Cardinals", section: "Premier Jerseys" },
  { number: "2", name: "Trey McBride", team: "Arizona Cardinals", section: "Premier Jerseys" },
  { number: "3", name: "Bijan Robinson", team: "Atlanta Falcons", section: "Premier Jerseys" },
  { number: "4", name: "Michael Penix Jr.", team: "Atlanta Falcons", section: "Premier Jerseys" },
  { number: "5", name: "Lamar Jackson", team: "Baltimore Ravens", section: "Premier Jerseys" },
  { number: "6", name: "Derrick Henry", team: "Baltimore Ravens", section: "Premier Jerseys" },
  { number: "7", name: "Josh Allen", team: "Buffalo Bills", section: "Premier Jerseys" },
  { number: "8", name: "James Cook", team: "Buffalo Bills", section: "Premier Jerseys" },
  { number: "9", name: "Bryce Young", team: "Carolina Panthers", section: "Premier Jerseys" },
  { number: "10", name: "Caleb Williams", team: "Chicago Bears", section: "Premier Jerseys" },
  { number: "11", name: "Joe Burrow", team: "Cincinnati Bengals", section: "Premier Jerseys" },
  { number: "12", name: "Ja'Marr Chase", team: "Cincinnati Bengals", section: "Premier Jerseys" },
  { number: "13", name: "Myles Garrett", team: "Cleveland Browns", section: "Premier Jerseys" },
  { number: "14", name: "Micah Parsons", team: "Dallas Cowboys", section: "Premier Jerseys" },
  { number: "15", name: "CeeDee Lamb", team: "Dallas Cowboys", section: "Premier Jerseys" },
  { number: "16", name: "Bo Nix", team: "Denver Broncos", section: "Premier Jerseys" },
  { number: "17", name: "Amon-Ra St. Brown", team: "Detroit Lions", section: "Premier Jerseys" },
  { number: "18", name: "Jahmyr Gibbs", team: "Detroit Lions", section: "Premier Jerseys" },
  { number: "19", name: "Josh Jacobs", team: "Green Bay Packers", section: "Premier Jerseys" },
  { number: "20", name: "Nico Collins", team: "Houston Texans", section: "Premier Jerseys" },
  { number: "21", name: "C.J. Stroud", team: "Houston Texans", section: "Premier Jerseys" },
  { number: "22", name: "Jonathan Taylor", team: "Indianapolis Colts", section: "Premier Jerseys" },
  { number: "23", name: "Brian Thomas Jr.", team: "Jacksonville Jaguars", section: "Premier Jerseys" },
  { number: "24", name: "Patrick Mahomes II", team: "Kansas City Chiefs", section: "Premier Jerseys" },
  { number: "25", name: "Xavier Worthy", team: "Kansas City Chiefs", section: "Premier Jerseys" },
  { number: "26", name: "Brock Bowers", team: "Las Vegas Raiders", section: "Premier Jerseys" },
  { number: "27", name: "Justin Herbert", team: "Los Angeles Chargers", section: "Premier Jerseys" },
  { number: "28", name: "Davante Adams", team: "Los Angeles Rams", section: "Premier Jerseys" },
  { number: "29", name: "Matthew Stafford", team: "Los Angeles Rams", section: "Premier Jerseys" },
  { number: "30", name: "De'Von Achane", team: "Miami Dolphins", section: "Premier Jerseys" },
  { number: "31", name: "Tyreek Hill", team: "Miami Dolphins", section: "Premier Jerseys" },
  { number: "32", name: "Justin Jefferson", team: "Minnesota Vikings", section: "Premier Jerseys" },
  { number: "33", name: "J.J. McCarthy", team: "Minnesota Vikings", section: "Premier Jerseys" },
  { number: "34", name: "Drake Maye", team: "New England Patriots", section: "Premier Jerseys" },
  { number: "35", name: "Alvin Kamara", team: "New Orleans Saints", section: "Premier Jerseys" },
  { number: "36", name: "Malik Nabers", team: "New York Giants", section: "Premier Jerseys" },
  { number: "37", name: "Justin Fields", team: "New York Jets", section: "Premier Jerseys" },
  { number: "38", name: "Garrett Wilson", team: "New York Jets", section: "Premier Jerseys" },
  { number: "39", name: "Saquon Barkley", team: "Philadelphia Eagles", section: "Premier Jerseys" },
  { number: "40", name: "Jalen Hurts", team: "Philadelphia Eagles", section: "Premier Jerseys" },
  { number: "41", name: "DK Metcalf", team: "Pittsburgh Steelers", section: "Premier Jerseys" },
  { number: "42", name: "T.J. Watt", team: "Pittsburgh Steelers", section: "Premier Jerseys" },
  { number: "43", name: "Christian McCaffrey", team: "San Francisco 49ers", section: "Premier Jerseys" },
  { number: "44", name: "Brock Purdy", team: "San Francisco 49ers", section: "Premier Jerseys" },
  { number: "45", name: "Jaxon Smith-Njigba", team: "Seattle Seahawks", section: "Premier Jerseys" },
  { number: "46", name: "Baker Mayfield", team: "Tampa Bay Buccaneers", section: "Premier Jerseys" },
  { number: "47", name: "Bucky Irving", team: "Tampa Bay Buccaneers", section: "Premier Jerseys" },
  { number: "48", name: "Tony Pollard", team: "Tennessee Titans", section: "Premier Jerseys" },
  { number: "49", name: "Jayden Daniels", team: "Washington Commanders", section: "Premier Jerseys" },
  { number: "50", name: "Terry McLaurin", team: "Washington Commanders", section: "Premier Jerseys" },
  { number: "1", name: "Walter Nolen", team: "Arizona Cardinals", section: "Rookie Gear" },
  { number: "2", name: "Jalon Walker", team: "Atlanta Falcons", section: "Rookie Gear" },
  { number: "3", name: "Malaki Starks", team: "Baltimore Ravens", section: "Rookie Gear" },
  { number: "4", name: "T.J. Sanders", team: "Buffalo Bills", section: "Rookie Gear" },
  { number: "5", name: "Trevor Etienne", team: "Carolina Panthers", section: "Rookie Gear" },
  { number: "6", name: "Tetairoa McMillan", team: "Carolina Panthers", section: "Rookie Gear" },
  { number: "7", name: "Luther Burden III", team: "Chicago Bears", section: "Rookie Gear" },
  { number: "8", name: "Colston Loveland", team: "Chicago Bears", section: "Rookie Gear" },
  { number: "9", name: "Shemar Stewart", team: "Cincinnati Bengals", section: "Rookie Gear" },
  { number: "10", name: "Quinshon Judkins", team: "Cleveland Browns", section: "Rookie Gear" },
  { number: "11", name: "Dillon Gabriel", team: "Cleveland Browns", section: "Rookie Gear" },
  { number: "12", name: "Mason Graham", team: "Cleveland Browns", section: "Rookie Gear" },
  { number: "13", name: "Jaydon Blue", team: "Dallas Cowboys", section: "Rookie Gear" },
  { number: "14", name: "Jahdae Barron", team: "Denver Broncos", section: "Rookie Gear" },
  { number: "15", name: "RJ Harvey", team: "Denver Broncos", section: "Rookie Gear" },
  { number: "16", name: "Pat Bryant", team: "Denver Broncos", section: "Rookie Gear" },
  { number: "17", name: "Isaac TeSlaa", team: "Detroit Lions", section: "Rookie Gear" },
  { number: "18", name: "Savion Williams", team: "Green Bay Packers", section: "Rookie Gear" },
  { number: "19", name: "Matthew Golden", team: "Green Bay Packers", section: "Rookie Gear" },
  { number: "20", name: "Jaylin Noel", team: "Houston Texans", section: "Rookie Gear" },
  { number: "21", name: "Jayden Higgins", team: "Houston Texans", section: "Rookie Gear" },
  { number: "22", name: "Riley Leonard", team: "Indianapolis Colts", section: "Rookie Gear" },
  { number: "23", name: "Tyler Warren", team: "Indianapolis Colts", section: "Rookie Gear" },
  { number: "24", name: "Travis Hunter", team: "Jacksonville Jaguars", section: "Rookie Gear" },
  { number: "25", name: "Bhayshul Tuten", team: "Jacksonville Jaguars", section: "Rookie Gear" },
  { number: "26", name: "Jalen Royals", team: "Kansas City Chiefs", section: "Rookie Gear" },
  { number: "27", name: "Ashton Jeanty", team: "Las Vegas Raiders", section: "Rookie Gear" },
  { number: "28", name: "Jack Bech", team: "Las Vegas Raiders", section: "Rookie Gear" },
  { number: "29", name: "Omarion Hampton", team: "Los Angeles Chargers", section: "Rookie Gear" },
  { number: "30", name: "Tre Harris", team: "Los Angeles Chargers", section: "Rookie Gear" },
  { number: "31", name: "Terrance Ferguson", team: "Los Angeles Rams", section: "Rookie Gear" },
  { number: "32", name: "Kenneth Grant", team: "Miami Dolphins", section: "Rookie Gear" },
  { number: "33", name: "Tai Felton", team: "Minnesota Vikings", section: "Rookie Gear" },
  { number: "34", name: "Kyle Williams", team: "New England Patriots", section: "Rookie Gear" },
  { number: "35", name: "TreVeyon Henderson", team: "New England Patriots", section: "Rookie Gear" },
  { number: "36", name: "Tyler Shough", team: "New Orleans Saints", section: "Rookie Gear" },
  { number: "37", name: "Cam Skattebo", team: "New York Giants", section: "Rookie Gear" },
  { number: "38", name: "Abdul Carter", team: "New York Giants", section: "Rookie Gear" },
  { number: "39", name: "Jaxson Dart", team: "New York Giants", section: "Rookie Gear" },
  { number: "40", name: "Mason Taylor", team: "New York Jets", section: "Rookie Gear" },
  { number: "41", name: "Kyle McCord", team: "Philadelphia Eagles", section: "Rookie Gear" },
  { number: "42", name: "Will Howard", team: "Pittsburgh Steelers", section: "Rookie Gear" },
  { number: "43", name: "Kaleb Johnson", team: "Pittsburgh Steelers", section: "Rookie Gear" },
  { number: "44", name: "Mykel Williams", team: "San Francisco 49ers", section: "Rookie Gear" },
  { number: "45", name: "Elijah Arroyo", team: "Seattle Seahawks", section: "Rookie Gear" },
  { number: "46", name: "Jalen Milroe", team: "Seattle Seahawks", section: "Rookie Gear" },
  { number: "47", name: "Emeka Egbuka", team: "Tampa Bay Buccaneers", section: "Rookie Gear" },
  { number: "48", name: "Cam Ward", team: "Tennessee Titans", section: "Rookie Gear" },
  { number: "49", name: "Chimere Dike", team: "Tennessee Titans", section: "Rookie Gear" },
  { number: "50", name: "Jaylin Lane", team: "Washington Commanders", section: "Rookie Gear" },
];