export type Prizm2025Entry = {
  number: string;
  name: string;
  team?: string;
  section: string;
};

export const PRIZM_2025_CHECKLIST: Prizm2025Entry[] = [
  { number: "1", name: "Javonte Williams", team: "Dallas Cowboys", section: "Base Set Checklist" },
  { number: "2", name: "Brian Thomas Jr.", team: "Jacksonville Jaguars", section: "Base Set Checklist" },
  { number: "3", name: "Christian Kirk", team: "Houston Texans", section: "Base Set Checklist" },
  { number: "4", name: "Josh Sweat", team: "Arizona Cardinals", section: "Base Set Checklist" },
  { number: "5", name: "Bryce Young", team: "Carolina Panthers", section: "Base Set Checklist" },
  { number: "6", name: "Brock Bowers", team: "Las Vegas Raiders", section: "Base Set Checklist" },
  { number: "7", name: "Aaron Jones", team: "Minnesota Vikings", section: "Base Set Checklist" },
  { number: "8", name: "Rome Odunze", team: "Chicago Bears", section: "Base Set Checklist" },
  { number: "9", name: "Greg Rousseau", team: "Buffalo Bills", section: "Base Set Checklist" },
  { number: "10", name: "Jared Goff", team: "Detroit Lions", section: "Base Set Checklist" },
  { number: "11", name: "Kaden Elliss", team: "Atlanta Falcons", section: "Base Set Checklist" },
  { number: "12", name: "DK Metcalf", team: "Pittsburgh Steelers", section: "Base Set Checklist" },
  { number: "13", name: "Tee Higgins", team: "Cincinnati Bengals", section: "Base Set Checklist" },
  { number: "14", name: "Earnest Byner", team: "Cleveland Browns", section: "Base Set Checklist" },
  { number: "15", name: "Craig Morton", team: "Denver Broncos", section: "Base Set Checklist" },
  { number: "16", name: "Cooper Kupp", team: "Seattle Seahawks", section: "Base Set Checklist" },
  { number: "17", name: "Eric Allen", team: "Philadelphia Eagles", section: "Base Set Checklist" },
  { number: "18", name: "Ladd McConkey", team: "Los Angeles Chargers", section: "Base Set Checklist" },
  { number: "19", name: "Jordan Addison", team: "Minnesota Vikings", section: "Base Set Checklist" },
  { number: "20", name: "Chop Robinson", team: "Miami Dolphins", section: "Base Set Checklist" },
  { number: "21", name: "Matthew Stafford", team: "Los Angeles Rams", section: "Base Set Checklist" },
  { number: "22", name: "Nnamdi Madubuike", team: "Baltimore Ravens", section: "Base Set Checklist" },
  { number: "23", name: "Michael Pittman Jr.", team: "Indianapolis Colts", section: "Base Set Checklist" },
  { number: "24", name: "L'Jarius Sneed", team: "Tennessee Titans", section: "Base Set Checklist" },
  { number: "25", name: "Jayden Reed", team: "Green Bay Packers", section: "Base Set Checklist" },
  { number: "26", name: "Patrick Mahomes II", team: "Kansas City Chiefs", section: "Base Set Checklist" },
  { number: "27", name: "James Cook", team: "Buffalo Bills", section: "Base Set Checklist" },
  { number: "28", name: "Marvin Harrison Jr.", team: "Arizona Cardinals", section: "Base Set Checklist" },
  { number: "29", name: "Jason Sehorn", team: "New York Giants", section: "Base Set Checklist" },
  { number: "30", name: "Jared Verse", team: "Los Angeles Rams", section: "Base Set Checklist" },
  { number: "31", name: "Jakobi Meyers", team: "Las Vegas Raiders", section: "Base Set Checklist" },
  { number: "32", name: "Najee Harris", team: "Los Angeles Chargers", section: "Base Set Checklist" },
  { number: "33", name: "Hunter Henry", team: "New England Patriots", section: "Base Set Checklist" },
  { number: "34", name: "Ray-Ray McCloud", team: "Atlanta Falcons", section: "Base Set Checklist" },
  { number: "35", name: "Tarheeb Still", team: "Los Angeles Chargers", section: "Base Set Checklist" },
  { number: "36", name: "Jake Ferguson", team: "Dallas Cowboys", section: "Base Set Checklist" },
  { number: "37", name: "Leonard Fournette", team: "Jacksonville Jaguars", section: "Base Set Checklist" },
  { number: "38", name: "LeGarrette Blount", team: "Tampa Bay Buccaneers", section: "Base Set Checklist" },
  { number: "39", name: "Vernon Davis", team: "San Francisco 49ers", section: "Base Set Checklist" },
  { number: "40", name: "Christian Wilkins", team: "Las Vegas Raiders", section: "Base Set Checklist" },
  { number: "41", name: "Kerby Joseph", team: "Detroit Lions", section: "Base Set Checklist" },
  { number: "42", name: "Ray Lewis", team: "Baltimore Ravens", section: "Base Set Checklist" },
  { number: "43", name: "Josh Hines-Allen", team: "Jacksonville Jaguars", section: "Base Set Checklist" },
  { number: "44", name: "Jaylon Johnson", team: "Chicago Bears", section: "Base Set Checklist" },
  { number: "45", name: "Willis McGahee", team: "Buffalo Bills", section: "Base Set Checklist" },
  { number: "46", name: "Dwayne Bowe", team: "Kansas City Chiefs", section: "Base Set Checklist" },
  { number: "47", name: "Aaron Glenn", team: "New York Jets", section: "Base Set Checklist" },
  { number: "48", name: "Danielle Hunter", team: "Houston Texans", section: "Base Set Checklist" },
  { number: "49", name: "Adonai Mitchell", team: "Indianapolis Colts", section: "Base Set Checklist" },
  { number: "50", name: "Breece Hall", team: "New York Jets", section: "Base Set Checklist" },
  { number: "51", name: "Jonnu Smith", team: "Miami Dolphins", section: "Base Set Checklist" },
  { number: "52", name: "Warren Moon", team: "Kansas City Chiefs", section: "Base Set Checklist" },
  { number: "53", name: "Eric Moulds", team: "Houston Texans", section: "Base Set Checklist" },
  { number: "54", name: "Devaughn Vele", team: "Denver Broncos", section: "Base Set Checklist" },
  { number: "55", name: "Jalen Coker", team: "Carolina Panthers", section: "Base Set Checklist" },
  { number: "56", name: "Michael Penix Jr.", team: "Atlanta Falcons", section: "Base Set Checklist" },
  { number: "57", name: "Dak Prescott", team: "Dallas Cowboys", section: "Base Set Checklist" },
  { number: "58", name: "Tua Tagovailoa", team: "Miami Dolphins", section: "Base Set Checklist" },
  { number: "59", name: "Kamren Kinchens", team: "Los Angeles Rams", section: "Base Set Checklist" },
  { number: "60", name: "Ozzie Newsome", team: "Cleveland Browns", section: "Base Set Checklist" },
  { number: "61", name: "Geno Stone", team: "Cincinnati Bengals", section: "Base Set Checklist" },
  { number: "62", name: "Joe Burrow", team: "Cincinnati Bengals", section: "Base Set Checklist" },
  { number: "63", name: "Andrew Van Ginkel", team: "Minnesota Vikings", section: "Base Set Checklist" },
  { number: "64", name: "Zach Ertz", team: "Washington Commanders", section: "Base Set Checklist" },
  { number: "65", name: "Dawson Knox", team: "Buffalo Bills", section: "Base Set Checklist" },
  { number: "66", name: "Xavier McKinney", team: "Green Bay Packers", section: "Base Set Checklist" },
  { number: "67", name: "Travis Kelce", team: "Kansas City Chiefs", section: "Base Set Checklist" },
  { number: "68", name: "Travis Etienne Jr.", team: "Jacksonville Jaguars", section: "Base Set Checklist" },
  { number: "69", name: "Trey Benson", team: "Arizona Cardinals", section: "Base Set Checklist" },
  { number: "70", name: "DeVonta Smith", team: "Philadelphia Eagles", section: "Base Set Checklist" },
  { number: "71", name: "George Pickens", team: "Dallas Cowboys", section: "Base Set Checklist" },
  { number: "72", name: "Jim Kelly", team: "Buffalo Bills", section: "Base Set Checklist" },
  { number: "73", name: "Myles Garrett", team: "Cleveland Browns", section: "Base Set Checklist" },
  { number: "74", name: "Jahmyr Gibbs", team: "Detroit Lions", section: "Base Set Checklist" },
  { number: "75", name: "Marshall Faulk", team: "Indianapolis Colts", section: "Base Set Checklist" },
  { number: "76", name: "Derrick Brown", team: "Carolina Panthers", section: "Base Set Checklist" },
  { number: "77", name: "Ivan Pace Jr.", team: "Minnesota Vikings", section: "Base Set Checklist" },
  { number: "78", name: "Lamar Jackson", team: "Baltimore Ravens", section: "Base Set Checklist" },
  { number: "79", name: "Mike Gesicki", team: "Cincinnati Bengals", section: "Base Set Checklist" },
  { number: "80", name: "T'Vondre Sweat", team: "Tennessee Titans", section: "Base Set Checklist" },
  { number: "81", name: "Justin Jefferson", team: "Minnesota Vikings", section: "Base Set Checklist" },
  { number: "82", name: "Jordan Love", team: "Green Bay Packers", section: "Base Set Checklist" },
  { number: "83", name: "Eric Dickerson", team: "Los Angeles Raiders", section: "Base Set Checklist" },
  { number: "84", name: "Rhamondre Stevenson", team: "New England Patriots", section: "Base Set Checklist" },
  { number: "85", name: "Arik Armstead", team: "Jacksonville Jaguars", section: "Base Set Checklist" },
  { number: "86", name: "Raghib \"Rocket\" Ismail", team: "Carolina Panthers", section: "Base Set Checklist" },
  { number: "87", name: "Kyler Murray", team: "Arizona Cardinals", section: "Base Set Checklist" },
  { number: "88", name: "Dave Krieg", team: "Seattle Seahawks", section: "Base Set Checklist" },
  { number: "89", name: "Dan Fouts", team: "San Diego Chargers", section: "Base Set Checklist" },
  { number: "90", name: "Denzel Ward", team: "Cleveland Browns", section: "Base Set Checklist" },
  { number: "91", name: "Zaire Franklin", team: "Indianapolis Colts", section: "Base Set Checklist" },
  { number: "92", name: "DJ Moore", team: "Chicago Bears", section: "Base Set Checklist" },
  { number: "93", name: "Terrell Suggs", team: "Baltimore Ravens", section: "Base Set Checklist" },
  { number: "94", name: "George Kittle", team: "San Francisco 49ers", section: "Base Set Checklist" },
  { number: "95", name: "Micah McFadden", team: "New York Giants", section: "Base Set Checklist" },
  { number: "96", name: "Bijan Robinson", team: "Atlanta Falcons", section: "Base Set Checklist" },
  { number: "97", name: "Patrick Surtain II", team: "Denver Broncos", section: "Base Set Checklist" },
  { number: "98", name: "Micah Parsons", team: "Dallas Cowboys", section: "Base Set Checklist" },
  { number: "99", name: "Ricky Pearsall", team: "San Francisco 49ers", section: "Base Set Checklist" },
  { number: "100", name: "Braelon Allen", team: "New York Jets", section: "Base Set Checklist" },
  { number: "101", name: "Cade Stover", team: "Houston Texans", section: "Base Set Checklist" },
  { number: "102", name: "Hines Ward", team: "Pittsburgh Steelers", section: "Base Set Checklist" },
  { number: "103", name: "Geno Smith", team: "Las Vegas Raiders", section: "Base Set Checklist" },
  { number: "104", name: "Davante Adams", team: "Los Angeles Rams", section: "Base Set Checklist" },
  { number: "105", name: "Sean Taylor", team: "Washington Redskins", section: "Base Set Checklist" },
  { number: "106", name: "Zay Flowers", team: "Baltimore Ravens", section: "Base Set Checklist" },
  { number: "107", name: "Chris Chambers", team: "Miami Dolphins", section: "Base Set Checklist" },
  { number: "108", name: "Jonathan Taylor", team: "Indianapolis Colts", section: "Base Set Checklist" },
  { number: "109", name: "Joe Mixon", team: "Houston Texans", section: "Base Set Checklist" },
  { number: "110", name: "Mike Vrabel", team: "New England Patriots", section: "Base Set Checklist" },
  { number: "111", name: "Calvin Johnson", team: "Detroit Lions", section: "Base Set Checklist" },
  { number: "112", name: "Cole Kmet", team: "Chicago Bears", section: "Base Set Checklist" },
  { number: "113", name: "Chris Jones", team: "Kansas City Chiefs", section: "Base Set Checklist" },
  { number: "114", name: "Antoine Winfield Jr.", team: "Tampa Bay Buccaneers", section: "Base Set Checklist" },
  { number: "115", name: "Rich Gannon", team: "Oakland Raiders", section: "Base Set Checklist" },
  { number: "116", name: "Khalil Shakir", team: "Buffalo Bills", section: "Base Set Checklist" },
  { number: "117", name: "Gerald Riggs", team: "Atlanta Falcons", section: "Base Set Checklist" },
  { number: "118", name: "Xavier Legette", team: "Carolina Panthers", section: "Base Set Checklist" },
  { number: "119", name: "Charles Woodson", team: "Green Bay Packers", section: "Base Set Checklist" },
  { number: "120", name: "Dwight Freeney", team: "Indianapolis Colts", section: "Base Set Checklist" },
  { number: "121", name: "Torry Holt", team: "Jacksonville Jaguars", section: "Base Set Checklist" },
  { number: "122", name: "Sam LaPorta", team: "Detroit Lions", section: "Base Set Checklist" },
  { number: "123", name: "Vita Vea", team: "Tampa Bay Buccaneers", section: "Base Set Checklist" },
  { number: "124", name: "Caleb Williams", team: "Chicago Bears", section: "Base Set Checklist" },
  { number: "125", name: "Budda Baker", team: "Arizona Cardinals", section: "Base Set Checklist" },
  { number: "126", name: "Isiah Pacheco", team: "Kansas City Chiefs", section: "Base Set Checklist" },
  { number: "127", name: "Tucker Kraft", team: "Green Bay Packers", section: "Base Set Checklist" },
  { number: "128", name: "Randy White", team: "Dallas Cowboys", section: "Base Set Checklist" },
  { number: "129", name: "Jordyn Brooks", team: "Miami Dolphins", section: "Base Set Checklist" },
  { number: "130", name: "Chase Brown", team: "Cincinnati Bengals", section: "Base Set Checklist" },
  { number: "131", name: "Younghoe Koo", team: "Atlanta Falcons", section: "Base Set Checklist" },
  { number: "132", name: "Minkah Fitzpatrick", team: "Miami Dolphins", section: "Base Set Checklist" },
  { number: "133", name: "Deebo Samuel", team: "Washington Commanders", section: "Base Set Checklist" },
  { number: "134", name: "Kimani Vidal", team: "Los Angeles Chargers", section: "Base Set Checklist" },
  { number: "135", name: "Josey Jewell", team: "Carolina Panthers", section: "Base Set Checklist" },
  { number: "136", name: "Brenton Strange", team: "Jacksonville Jaguars", section: "Base Set Checklist" },
  { number: "137", name: "KaVontae Turpin", team: "Dallas Cowboys", section: "Base Set Checklist" },
  { number: "138", name: "Kyren Williams", team: "Los Angeles Rams", section: "Base Set Checklist" },
  { number: "139", name: "Golden Tate III", team: "Detroit Lions", section: "Base Set Checklist" },
  { number: "140", name: "Frank Gore", team: "Buffalo Bills", section: "Base Set Checklist" },
  { number: "141", name: "Brian Robinson Jr.", team: "Washington Commanders", section: "Base Set Checklist" },
  { number: "142", name: "Bo Nix", team: "Denver Broncos", section: "Base Set Checklist" },
  { number: "143", name: "C.J. Stroud", team: "Houston Texans", section: "Base Set Checklist" },
  { number: "144", name: "Braden Fiske", team: "Los Angeles Rams", section: "Base Set Checklist" },
  { number: "145", name: "Michael Wilson", team: "Arizona Cardinals", section: "Base Set Checklist" },
  { number: "146", name: "Jerry Jeudy", team: "Cleveland Browns", section: "Base Set Checklist" },
  { number: "147", name: "Brian Burns", team: "New York Giants", section: "Base Set Checklist" },
  { number: "148", name: "Ka'imi Fairbairn", team: "Houston Texans", section: "Base Set Checklist" },
  { number: "149", name: "James Lofton", team: "Green Bay Packers", section: "Base Set Checklist" },
  { number: "150", name: "De'Von Achane", team: "Miami Dolphins", section: "Base Set Checklist" },
  { number: "151", name: "Cade Otton", team: "Tampa Bay Buccaneers", section: "Base Set Checklist" },
  { number: "152", name: "Carl Pickens", team: "Cincinnati Bengals", section: "Base Set Checklist" },
  { number: "153", name: "Christian Watson", team: "Green Bay Packers", section: "Base Set Checklist" },
  { number: "154", name: "CeeDee Lamb", team: "Dallas Cowboys", section: "Base Set Checklist" },
  { number: "155", name: "David Njoku", team: "Cleveland Browns", section: "Base Set Checklist" },
  { number: "156", name: "Christian McCaffrey", team: "San Francisco 49ers", section: "Base Set Checklist" },
  { number: "157", name: "Steve Spurrier", team: "San Francisco 49ers", section: "Base Set Checklist" },
  { number: "158", name: "Ricky Williams", team: "Baltimore Ravens", section: "Base Set Checklist" },
  { number: "159", name: "Jeremiah Owusu-Koramoah", team: "Cleveland Browns", section: "Base Set Checklist" },
  { number: "160", name: "Brett Favre", team: "Minnesota Vikings", section: "Base Set Checklist" },
  { number: "161", name: "Khalil Mack", team: "Los Angeles Chargers", section: "Base Set Checklist" },
  { number: "162", name: "Tre Tucker", team: "Las Vegas Raiders", section: "Base Set Checklist" },
  { number: "163", name: "Courtland Sutton", team: "Denver Broncos", section: "Base Set Checklist" },
  { number: "164", name: "David Montgomery", team: "Detroit Lions", section: "Base Set Checklist" },
  { number: "165", name: "Drake Maye", team: "New England Patriots", section: "Base Set Checklist" },
  { number: "166", name: "Archie Manning", team: "Houston Oilers", section: "Base Set Checklist" },
  { number: "167", name: "Josh Allen", team: "Buffalo Bills", section: "Base Set Checklist" },
  { number: "168", name: "Derrick Henry", team: "Baltimore Ravens", section: "Base Set Checklist" },
  { number: "169", name: "Bucky Irving", team: "Tampa Bay Buccaneers", section: "Base Set Checklist" },
  { number: "170", name: "Cooper DeJean", team: "Philadelphia Eagles", section: "Base Set Checklist" },
  { number: "171", name: "James Conner", team: "Arizona Cardinals", section: "Base Set Checklist" },
  { number: "172", name: "Jaylen Waddle", team: "Miami Dolphins", section: "Base Set Checklist" },
  { number: "173", name: "T.J. Hockenson", team: "Minnesota Vikings", section: "Base Set Checklist" },
  { number: "174", name: "Chris Boswell", team: "Pittsburgh Steelers", section: "Base Set Checklist" },
  { number: "175", name: "Tank Bigsby", team: "Jacksonville Jaguars", section: "Base Set Checklist" },
  { number: "176", name: "Christian Gonzalez", team: "New England Patriots", section: "Base Set Checklist" },
  { number: "177", name: "Trent McDuffie", team: "Kansas City Chiefs", section: "Base Set Checklist" },
  { number: "178", name: "Garrett Wilson", team: "New York Jets", section: "Base Set Checklist" },
  { number: "179", name: "Troy Aikman", team: "Dallas Cowboys", section: "Base Set Checklist" },
  { number: "180", name: "Chad Johnson", team: "New England Patriots", section: "Base Set Checklist" },
  { number: "181", name: "Wes Welker", team: "New England Patriots", section: "Base Set Checklist" },
  { number: "182", name: "Stefon Diggs", team: "New England Patriots", section: "Base Set Checklist" },
  { number: "183", name: "Leonard Williams", team: "Seattle Seahawks", section: "Base Set Checklist" },
  { number: "184", name: "Marshon Lattimore", team: "Washington Commanders", section: "Base Set Checklist" },
  { number: "185", name: "Ken O'Brien", team: "New York Jets", section: "Base Set Checklist" },
  { number: "186", name: "Spencer Rattler", team: "New Orleans Saints", section: "Base Set Checklist" },
  { number: "187", name: "Amon-Ra St. Brown", team: "Detroit Lions", section: "Base Set Checklist" },
  { number: "188", name: "Josh Jacobs", team: "Green Bay Packers", section: "Base Set Checklist" },
  { number: "189", name: "Adam Thielen", team: "Carolina Panthers", section: "Base Set Checklist" },
  { number: "190", name: "Alvin Kamara", team: "New Orleans Saints", section: "Base Set Checklist" },
  { number: "191", name: "Kendre Miller", team: "New Orleans Saints", section: "Base Set Checklist" },
  { number: "192", name: "Chris Olave", team: "New Orleans Saints", section: "Base Set Checklist" },
  { number: "193", name: "Anthony Richardson", team: "Indianapolis Colts", section: "Base Set Checklist" },
  { number: "194", name: "Rashid Shaheed", team: "New Orleans Saints", section: "Base Set Checklist" },
  { number: "195", name: "Maxx Crosby", team: "Las Vegas Raiders", section: "Base Set Checklist" },
  { number: "196", name: "Tyrann Mathieu", team: "New Orleans Saints", section: "Base Set Checklist" },
  { number: "197", name: "Xavier Worthy", team: "Kansas City Chiefs", section: "Base Set Checklist" },
  { number: "198", name: "Drake London", team: "Atlanta Falcons", section: "Base Set Checklist" },
  { number: "199", name: "Cameron Jordan", team: "New Orleans Saints", section: "Base Set Checklist" },
  { number: "200", name: "Jeremy Shockey", team: "New Orleans Saints", section: "Base Set Checklist" },
  { number: "201", name: "Joe Horn", team: "New Orleans Saints", section: "Base Set Checklist" },
  { number: "202", name: "Russell Wilson", team: "New York Giants", section: "Base Set Checklist" },
  { number: "203", name: "Tyrone Tracy Jr.", team: "New York Giants", section: "Base Set Checklist" },
  { number: "204", name: "Jan Stenerud", team: "Kansas City Chiefs", section: "Base Set Checklist" },
  { number: "205", name: "Puka Nacua", team: "Los Angeles Rams", section: "Base Set Checklist" },
  { number: "206", name: "Malik Nabers", team: "New York Giants", section: "Base Set Checklist" },
  { number: "207", name: "Ron Jaworski", team: "Philadelphia Eagles", section: "Base Set Checklist" },
  { number: "208", name: "Ja'Marr Chase", team: "Cincinnati Bengals", section: "Base Set Checklist" },
  { number: "209", name: "Alec Pierce", team: "Indianapolis Colts", section: "Base Set Checklist" },
  { number: "210", name: "Aidan Hutchinson", team: "Detroit Lions", section: "Base Set Checklist" },
  { number: "211", name: "Theo Johnson", team: "New York Giants", section: "Base Set Checklist" },
  { number: "212", name: "Warren Sapp", team: "Oakland Raiders", section: "Base Set Checklist" },
  { number: "213", name: "Brad Johnson", team: "Tampa Bay Buccaneers", section: "Base Set Checklist" },
  { number: "214", name: "Cris Carter", team: "Miami Dolphins", section: "Base Set Checklist" },
  { number: "215", name: "Justin Herbert", team: "Los Angeles Chargers", section: "Base Set Checklist" },
  { number: "216", name: "Ed Reed", team: "Houston Texans", section: "Base Set Checklist" },
  { number: "217", name: "Kam Chancellor", team: "Seattle Seahawks", section: "Base Set Checklist" },
  { number: "218", name: "Justin Fields", team: "New York Jets", section: "Base Set Checklist" },
  { number: "219", name: "Nick Bosa", team: "San Francisco 49ers", section: "Base Set Checklist" },
  { number: "220", name: "Calvin Ridley", team: "Tennessee Titans", section: "Base Set Checklist" },
  { number: "221", name: "Jamien Sherwood", team: "New York Jets", section: "Base Set Checklist" },
  { number: "222", name: "Kyle Pitts", team: "Atlanta Falcons", section: "Base Set Checklist" },
  { number: "223", name: "Terry McLaurin", team: "Washington Commanders", section: "Base Set Checklist" },
  { number: "224", name: "Antonio Gibson", team: "New England Patriots", section: "Base Set Checklist" },
  { number: "225", name: "Mike Evans", team: "Tampa Bay Buccaneers", section: "Base Set Checklist" },
  { number: "226", name: "Audric Estime", team: "Denver Broncos", section: "Base Set Checklist" },
  { number: "227", name: "Jerome Ford", team: "Cleveland Browns", section: "Base Set Checklist" },
  { number: "228", name: "Jalen Hurts", team: "Philadelphia Eagles", section: "Base Set Checklist" },
  { number: "229", name: "Cris Dishman", team: "Houston Oilers", section: "Base Set Checklist" },
  { number: "230", name: "Nik Bonitto", team: "Denver Broncos", section: "Base Set Checklist" },
  { number: "231", name: "Nico Collins", team: "Houston Texans", section: "Base Set Checklist" },
  { number: "232", name: "Tony Pollard", team: "Tennessee Titans", section: "Base Set Checklist" },
  { number: "233", name: "Devin Hester", team: "Atlanta Falcons", section: "Base Set Checklist" },
  { number: "234", name: "Dallas Goedert", team: "Philadelphia Eagles", section: "Base Set Checklist" },
  { number: "235", name: "Jerome Bettis", team: "Los Angeles Rams", section: "Base Set Checklist" },
  { number: "236", name: "D'Andre Swift", team: "Chicago Bears", section: "Base Set Checklist" },
  { number: "237", name: "Chuba Hubbard", team: "Carolina Panthers", section: "Base Set Checklist" },
  { number: "238", name: "Trevor Lawrence", team: "Jacksonville Jaguars", section: "Base Set Checklist" },
  { number: "239", name: "Zack Baun", team: "Philadelphia Eagles", section: "Base Set Checklist" },
  { number: "240", name: "Vince Ferragamo", team: "Los Angeles Rams", section: "Base Set Checklist" },
  { number: "241", name: "Derwin James Jr.", team: "Los Angeles Chargers", section: "Base Set Checklist" },
  { number: "242", name: "Austin Ekeler", team: "Washington Commanders", section: "Base Set Checklist" },
  { number: "243", name: "Pat Freiermuth", team: "Pittsburgh Steelers", section: "Base Set Checklist" },
  { number: "244", name: "Chris Godwin", team: "Tampa Bay Buccaneers", section: "Base Set Checklist" },
  { number: "245", name: "Tremaine Edmunds", team: "Chicago Bears", section: "Base Set Checklist" },
  { number: "246", name: "Kyle Van Noy", team: "Baltimore Ravens", section: "Base Set Checklist" },
  { number: "247", name: "T.J. Houshmandzadeh", team: "Cincinnati Bengals", section: "Base Set Checklist" },
  { number: "248", name: "Mike Rozier", team: "Houston Oilers", section: "Base Set Checklist" },
  { number: "249", name: "Tyreek Hill", team: "Miami Dolphins", section: "Base Set Checklist" },
  { number: "250", name: "Tyler Nubin", team: "New York Giants", section: "Base Set Checklist" },
  { number: "251", name: "Clay Matthews (Jr.)", team: "Cleveland Browns", section: "Base Set Checklist" },
  { number: "252", name: "Carnell Lake", team: "Pittsburgh Steelers", section: "Base Set Checklist" },
  { number: "253", name: "A.J. Brown", team: "Philadelphia Eagles", section: "Base Set Checklist" },
  { number: "254", name: "Jaxon Smith-Njigba", team: "Seattle Seahawks", section: "Base Set Checklist" },
  { number: "255", name: "Brock Purdy", team: "San Francisco 49ers", section: "Base Set Checklist" },
  { number: "256", name: "Dave Casper", team: "Minnesota Vikings", section: "Base Set Checklist" },
  { number: "257", name: "Lance Briggs", team: "Chicago Bears", section: "Base Set Checklist" },
  { number: "258", name: "Jauan Jennings", team: "San Francisco 49ers", section: "Base Set Checklist" },
  { number: "259", name: "Mark Andrews", team: "Baltimore Ravens", section: "Base Set Checklist" },
  { number: "260", name: "Tony Dorsett", team: "Denver Broncos", section: "Base Set Checklist" },
  { number: "261", name: "Bobby Wagner", team: "Washington Commanders", section: "Base Set Checklist" },
  { number: "262", name: "Christian Benford", team: "Buffalo Bills", section: "Base Set Checklist" },
  { number: "263", name: "T.J. Watt", team: "Pittsburgh Steelers", section: "Base Set Checklist" },
  { number: "264", name: "Keyshawn Johnson", team: "Carolina Panthers", section: "Base Set Checklist" },
  { number: "265", name: "Austin Hooper", team: "New England Patriots", section: "Base Set Checklist" },
  { number: "266", name: "Drew Brees", team: "San Diego Chargers", section: "Base Set Checklist" },
  { number: "267", name: "Jeff Garcia", team: "San Francisco 49ers", section: "Base Set Checklist" },
  { number: "268", name: "Jeffery Simmons", team: "Tennessee Titans", section: "Base Set Checklist" },
  { number: "269", name: "Sam Darnold", team: "Seattle Seahawks", section: "Base Set Checklist" },
  { number: "270", name: "Tyjae Spears", team: "Tennessee Titans", section: "Base Set Checklist" },
  { number: "271", name: "Daniel Carlson", team: "Las Vegas Raiders", section: "Base Set Checklist" },
  { number: "272", name: "Kenneth Walker III", team: "Seattle Seahawks", section: "Base Set Checklist" },
  { number: "273", name: "Rashod Bateman", team: "Baltimore Ravens", section: "Base Set Checklist" },
  { number: "274", name: "Trey McBride", team: "Arizona Cardinals", section: "Base Set Checklist" },
  { number: "275", name: "Keon Coleman", team: "Buffalo Bills", section: "Base Set Checklist" },
  { number: "276", name: "Jameson Williams", team: "Detroit Lions", section: "Base Set Checklist" },
  { number: "277", name: "Evan Engram", team: "Denver Broncos", section: "Base Set Checklist" },
  { number: "278", name: "Jayden Daniels", team: "Washington Commanders", section: "Base Set Checklist" },
  { number: "279", name: "J.J. McCarthy", team: "Minnesota Vikings", section: "Base Set Checklist" },
  { number: "280", name: "DaRon Bland", team: "Dallas Cowboys", section: "Base Set Checklist" },
  { number: "281", name: "Deommodore Lenoir", team: "San Francisco 49ers", section: "Base Set Checklist" },
  { number: "282", name: "Ernest Jones", team: "Seattle Seahawks", section: "Base Set Checklist" },
  { number: "283", name: "Baker Mayfield", team: "Tampa Bay Buccaneers", section: "Base Set Checklist" },
  { number: "284", name: "Joe Theismann", team: "Washington Redskins", section: "Base Set Checklist" },
  { number: "285", name: "Odell Beckham Jr.", team: "New York Giants", section: "Base Set Checklist" },
  { number: "286", name: "Kwity Paye", team: "Indianapolis Colts", section: "Base Set Checklist" },
  { number: "287", name: "Marquise Brown", team: "Kansas City Chiefs", section: "Base Set Checklist" },
  { number: "288", name: "Kordell Stewart", team: "Pittsburgh Steelers", section: "Base Set Checklist" },
  { number: "289", name: "Steven Jackson", team: "St. Louis Rams", section: "Base Set Checklist" },
  { number: "290", name: "Brandon McManus", team: "Green Bay Packers", section: "Base Set Checklist" },
  { number: "291", name: "Trey Hendrickson", team: "Cincinnati Bengals", section: "Base Set Checklist" },
  { number: "292", name: "Quinnen Williams", team: "New York Jets", section: "Base Set Checklist" },
  { number: "293", name: "Jaylen Warren", team: "Pittsburgh Steelers", section: "Base Set Checklist" },
  { number: "294", name: "DeSean Jackson", team: "Philadelphia Eagles", section: "Base Set Checklist" },
  { number: "295", name: "Wayne Chrebet", team: "New York Jets", section: "Base Set Checklist" },
  { number: "296", name: "Julius Peppers", team: "Chicago Bears", section: "Base Set Checklist" },
  { number: "297", name: "AJ Barner", team: "Seattle Seahawks", section: "Base Set Checklist" },
  { number: "298", name: "Saquon Barkley", team: "Philadelphia Eagles", section: "Base Set Checklist" },
  { number: "299", name: "Larry Fitzgerald", team: "Arizona Cardinals", section: "Base Set Checklist" },
  { number: "300", name: "Tim Tebow", team: "Denver Broncos", section: "Base Set Checklist" },
  { number: "301", name: "Travis Hunter", team: "Jacksonville Jaguars", section: "Base - Rookies" },
  { number: "302", name: "Shedeur Sanders", team: "Cleveland Browns", section: "Base - Rookies" },
  { number: "303", name: "RJ Harvey", team: "Denver Broncos", section: "Base - Rookies" },
  { number: "304", name: "Mykel Williams", team: "San Francisco 49ers", section: "Base - Rookies" },
  { number: "305", name: "Bhayshul Tuten", team: "Jacksonville Jaguars", section: "Base - Rookies" },
  { number: "306", name: "Savion Williams", team: "Green Bay Packers", section: "Base - Rookies" },
  { number: "307", name: "Quinn Ewers", team: "Miami Dolphins", section: "Base - Rookies" },
  { number: "308", name: "Brashard Smith", team: "Kansas City Chiefs", section: "Base - Rookies" },
  { number: "309", name: "Elijah Arroyo", team: "Seattle Seahawks", section: "Base - Rookies" },
  { number: "310", name: "Malaki Starks", team: "Baltimore Ravens", section: "Base - Rookies" },
  { number: "311", name: "Tetairoa McMillan", team: "Carolina Panthers", section: "Base - Rookies" },
  { number: "312", name: "Will Campbell", team: "New England Patriots", section: "Base - Rookies" },
  { number: "313", name: "Quinshon Judkins", team: "Cleveland Browns", section: "Base - Rookies" },
  { number: "314", name: "Donovan Ezeiruaku", team: "Dallas Cowboys", section: "Base - Rookies" },
  { number: "315", name: "Ashton Jeanty", team: "Las Vegas Raiders", section: "Base - Rookies" },
  { number: "316", name: "Isaac TeSlaa", team: "Detroit Lions", section: "Base - Rookies" },
  { number: "317", name: "Jalen Milroe", team: "Seattle Seahawks", section: "Base - Rookies" },
  { number: "318", name: "Walter Nolen", team: "Arizona Cardinals", section: "Base - Rookies" },
  { number: "319", name: "Colston Loveland", team: "Chicago Bears", section: "Base - Rookies" },
  { number: "320", name: "Nick Emmanwori", team: "Seattle Seahawks", section: "Base - Rookies" },
  { number: "321", name: "Elic Ayomanor", team: "Tennessee Titans", section: "Base - Rookies" },
  { number: "322", name: "Tyler Booker", team: "Dallas Cowboys", section: "Base - Rookies" },
  { number: "323", name: "Jordan James", team: "San Francisco 49ers", section: "Base - Rookies" },
  { number: "324", name: "JT Tuimoloau", team: "Indianapolis Colts", section: "Base - Rookies" },
  { number: "325", name: "Jaydon Blue", team: "Dallas Cowboys", section: "Base - Rookies" },
  { number: "326", name: "Matthew Golden", team: "Green Bay Packers", section: "Base - Rookies" },
  { number: "327", name: "Tyler Shough", team: "New Orleans Saints", section: "Base - Rookies" },
  { number: "328", name: "Tyleik Williams", team: "Detroit Lions", section: "Base - Rookies" },
  { number: "329", name: "Mason Taylor", team: "New York Jets", section: "Base - Rookies" },
  { number: "330", name: "Andrew Mukuba", team: "Philadelphia Eagles", section: "Base - Rookies" },
  { number: "331", name: "Luther Burden III", team: "Chicago Bears", section: "Base - Rookies" },
  { number: "332", name: "Jaxson Dart", team: "New York Giants", section: "Base - Rookies" },
  { number: "333", name: "Ollie Gordon II", team: "Miami Dolphins", section: "Base - Rookies" },
  { number: "334", name: "Jihaad Campbell", team: "Philadelphia Eagles", section: "Base - Rookies" },
  { number: "335", name: "Tahj Brooks", team: "Cincinnati Bengals", section: "Base - Rookies" },
  { number: "336", name: "Kyle Williams", team: "New England Patriots", section: "Base - Rookies" },
  { number: "337", name: "Josh Simmons", team: "Kansas City Chiefs", section: "Base - Rookies" },
  { number: "338", name: "T.J. Sanders", team: "Buffalo Bills", section: "Base - Rookies" },
  { number: "339", name: "Tyler Warren", team: "Indianapolis Colts", section: "Base - Rookies" },
  { number: "340", name: "Kevin Winston Jr.", team: "Tennessee Titans", section: "Base - Rookies" },
  { number: "341", name: "Jalen Royals", team: "Kansas City Chiefs", section: "Base - Rookies" },
  { number: "342", name: "Riley Leonard", team: "Indianapolis Colts", section: "Base - Rookies" },
  { number: "343", name: "TreVeyon Henderson", team: "New England Patriots", section: "Base - Rookies" },
  { number: "344", name: "Shemar Stewart", team: "Cincinnati Bengals", section: "Base - Rookies" },
  { number: "345", name: "Trevor Etienne", team: "Carolina Panthers", section: "Base - Rookies" },
  { number: "346", name: "Jack Bech", team: "Las Vegas Raiders", section: "Base - Rookies" },
  { number: "347", name: "Kelvin Banks Jr.", team: "New Orleans Saints", section: "Base - Rookies" },
  { number: "348", name: "Kyle Monangai", team: "Chicago Bears", section: "Base - Rookies" },
  { number: "349", name: "KeAndre Lambert-Smith", team: "Los Angeles Chargers", section: "Base - Rookies" },
  { number: "350", name: "Jahdae Barron", team: "Denver Broncos", section: "Base - Rookies" },
  { number: "351", name: "Emeka Egbuka", team: "Tampa Bay Buccaneers", section: "Base - Rookies" },
  { number: "352", name: "Cam Ward", team: "Tennessee Titans", section: "Base - Rookies" },
  { number: "353", name: "Jarquez Hunter", team: "Los Angeles Rams", section: "Base - Rookies" },
  { number: "354", name: "Mason Graham", team: "Cleveland Browns", section: "Base - Rookies" },
  { number: "355", name: "Omarion Hampton", team: "Los Angeles Chargers", section: "Base - Rookies" },
  { number: "356", name: "Jaylin Lane", team: "Washington Commanders", section: "Base - Rookies" },
  { number: "357", name: "Armand Membou", team: "New York Jets", section: "Base - Rookies" },
  { number: "358", name: "Donovan Jackson", team: "Minnesota Vikings", section: "Base - Rookies" },
  { number: "359", name: "Gunnar Helm", team: "Tennessee Titans", section: "Base - Rookies" },
  { number: "360", name: "Maxwell Hairston", team: "Buffalo Bills", section: "Base - Rookies" },
  { number: "361", name: "Tai Felton", team: "Minnesota Vikings", section: "Base - Rookies" },
  { number: "362", name: "Cam Miller", team: "Las Vegas Raiders", section: "Base - Rookies" },
  { number: "363", name: "Cam Skattebo", team: "New York Giants", section: "Base - Rookies" },
  { number: "364", name: "James Pearce Jr.", team: "Atlanta Falcons", section: "Base - Rookies" },
  { number: "365", name: "Dylan Sampson", team: "Cleveland Browns", section: "Base - Rookies" },
  { number: "366", name: "Pat Bryant", team: "Denver Broncos", section: "Base - Rookies" },
  { number: "367", name: "Will Howard", team: "Pittsburgh Steelers", section: "Base - Rookies" },
  { number: "368", name: "Derrick Harmon", team: "Pittsburgh Steelers", section: "Base - Rookies" },
  { number: "369", name: "Dont'e Thornton Jr.", team: "Las Vegas Raiders", section: "Base - Rookies" },
  { number: "370", name: "Will Johnson", team: "Arizona Cardinals", section: "Base - Rookies" },
  { number: "371", name: "Tre Harris", team: "Los Angeles Chargers", section: "Base - Rookies" },
  { number: "372", name: "Dillon Gabriel", team: "Cleveland Browns", section: "Base - Rookies" },
  { number: "373", name: "Damien Martinez", team: "Seattle Seahawks", section: "Base - Rookies" },
  { number: "374", name: "Kenneth Grant", team: "Miami Dolphins", section: "Base - Rookies" },
  { number: "375", name: "Kaleb Johnson", team: "Pittsburgh Steelers", section: "Base - Rookies" },
  { number: "376", name: "Jayden Higgins", team: "Houston Texans", section: "Base - Rookies" },
  { number: "377", name: "Kyle McCord", team: "Philadelphia Eagles", section: "Base - Rookies" },
  { number: "378", name: "Phil Mafah", team: "Dallas Cowboys", section: "Base - Rookies" },
  { number: "379", name: "Terrance Ferguson", team: "Los Angeles Rams", section: "Base - Rookies" },
  { number: "380", name: "Shavon Revel Jr.", team: "Dallas Cowboys", section: "Base - Rookies" },
  { number: "381", name: "Tez Johnson", team: "Tampa Bay Buccaneers", section: "Base - Rookies" },
  { number: "382", name: "Josh Conerly Jr.", team: "Washington Commanders", section: "Base - Rookies" },
  { number: "383", name: "DJ Giddens", team: "Indianapolis Colts", section: "Base - Rookies" },
  { number: "384", name: "Carson Schwesinger", team: "Cleveland Browns", section: "Base - Rookies" },
  { number: "385", name: "Kalel Mullings", team: "Tennessee Titans", section: "Base - Rookies" },
  { number: "386", name: "Jaylin Noel", team: "Houston Texans", section: "Base - Rookies" },
  { number: "387", name: "Grey Zabel", team: "Seattle Seahawks", section: "Base - Rookies" },
  { number: "388", name: "Alfred Collins", team: "San Francisco 49ers", section: "Base - Rookies" },
  { number: "389", name: "Jordan Watkins", team: "San Francisco 49ers", section: "Base - Rookies" },
  { number: "390", name: "Azareye'h Thomas", team: "New York Jets", section: "Base - Rookies" },
  { number: "391", name: "Arian Smith", team: "New York Jets", section: "Base - Rookies" },
  { number: "392", name: "Graham Mertz", team: "Houston Texans", section: "Base - Rookies" },
  { number: "393", name: "Devin Neal", team: "New Orleans Saints", section: "Base - Rookies" },
  { number: "394", name: "Abdul Carter", team: "New York Giants", section: "Base - Rookies" },
  { number: "395", name: "Woody Marks", team: "Houston Texans", section: "Base - Rookies" },
  { number: "396", name: "Chimere Dike", team: "Tennessee Titans", section: "Base - Rookies" },
  { number: "397", name: "Kurtis Rourke", team: "San Francisco 49ers", section: "Base - Rookies" },
  { number: "398", name: "Jalon Walker", team: "Atlanta Falcons", section: "Base - Rookies" },
  { number: "399", name: "Harold Fannin Jr.", team: "Cleveland Browns", section: "Base - Rookies" },
  { number: "400", name: "Trey Amos", team: "Washington Commanders", section: "Base - Rookies" },
  { number: "401", name: "Tetairoa McMillan", team: "Carolina Panthers", section: "Rookie Variations Prizms Silver" },
  { number: "402", name: "Trevor Etienne", team: "Carolina Panthers", section: "Rookie Variations Prizms Silver" },
  { number: "403", name: "Colston Loveland", team: "Chicago Bears", section: "Rookie Variations Prizms Silver" },
  { number: "404", name: "Tez Johnson", team: "Tampa Bay Buccaneers", section: "Rookie Variations Prizms Silver" },
  { number: "405", name: "Shedeur Sanders", team: "Cleveland Browns", section: "Rookie Variations Prizms Silver" },
  { number: "406", name: "Dillon Gabriel", team: "Cleveland Browns", section: "Rookie Variations Prizms Silver" },
  { number: "407", name: "Quinshon Judkins", team: "Cleveland Browns", section: "Rookie Variations Prizms Silver" },
  { number: "408", name: "Jaydon Blue", team: "Dallas Cowboys", section: "Rookie Variations Prizms Silver" },
  { number: "409", name: "Pat Bryant", team: "Denver Broncos", section: "Rookie Variations Prizms Silver" },
  { number: "410", name: "RJ Harvey", team: "Denver Broncos", section: "Rookie Variations Prizms Silver" },
  { number: "411", name: "Isaac TeSlaa", team: "Detroit Lions", section: "Rookie Variations Prizms Silver" },
  { number: "412", name: "Matthew Golden", team: "Green Bay Packers", section: "Rookie Variations Prizms Silver" },
  { number: "413", name: "Savion Williams", team: "Green Bay Packers", section: "Rookie Variations Prizms Silver" },
  { number: "414", name: "Jayden Higgins", team: "Houston Texans", section: "Rookie Variations Prizms Silver" },
  { number: "415", name: "Jaylin Noel", team: "Houston Texans", section: "Rookie Variations Prizms Silver" },
  { number: "416", name: "Riley Leonard", team: "Indianapolis Colts", section: "Rookie Variations Prizms Silver" },
  { number: "417", name: "Tyler Warren", team: "Indianapolis Colts", section: "Rookie Variations Prizms Silver" },
  { number: "418", name: "Travis Hunter", team: "Jacksonville Jaguars", section: "Rookie Variations Prizms Silver" },
  { number: "419", name: "Jalen Royals", team: "Kansas City Chiefs", section: "Rookie Variations Prizms Silver" },
  { number: "420", name: "Jack Bech", team: "Las Vegas Raiders", section: "Rookie Variations Prizms Silver" },
  { number: "421", name: "Ashton Jeanty", team: "Las Vegas Raiders", section: "Rookie Variations Prizms Silver" },
  { number: "422", name: "Tre Harris", team: "Los Angeles Chargers", section: "Rookie Variations Prizms Silver" },
  { number: "423", name: "Omarion Hampton", team: "Los Angeles Chargers", section: "Rookie Variations Prizms Silver" },
  { number: "424", name: "Terrance Ferguson", team: "Los Angeles Rams", section: "Rookie Variations Prizms Silver" },
  { number: "425", name: "Quinn Ewers", team: "Miami Dolphins", section: "Rookie Variations Prizms Silver" },
  { number: "426", name: "Tai Felton", team: "Minnesota Vikings", section: "Rookie Variations Prizms Silver" },
  { number: "427", name: "TreVeyon Henderson", team: "New England Patriots", section: "Rookie Variations Prizms Silver" },
  { number: "428", name: "Kyle Williams", team: "New England Patriots", section: "Rookie Variations Prizms Silver" },
  { number: "429", name: "Tyler Shough", team: "New Orleans Saints", section: "Rookie Variations Prizms Silver" },
  { number: "430", name: "Jaxson Dart", team: "New York Giants", section: "Rookie Variations Prizms Silver" },
  { number: "431", name: "Abdul Carter", team: "New York Giants", section: "Rookie Variations Prizms Silver" },
  { number: "432", name: "Cam Skattebo", team: "New York Giants", section: "Rookie Variations Prizms Silver" },
  { number: "433", name: "Mason Taylor", team: "New York Jets", section: "Rookie Variations Prizms Silver" },
  { number: "434", name: "Kyle McCord", team: "Philadelphia Eagles", section: "Rookie Variations Prizms Silver" },
  { number: "435", name: "Will Howard", team: "Pittsburgh Steelers", section: "Rookie Variations Prizms Silver" },
  { number: "436", name: "Kaleb Johnson", team: "Pittsburgh Steelers", section: "Rookie Variations Prizms Silver" },
  { number: "437", name: "Mykel Williams", team: "San Francisco 49ers", section: "Rookie Variations Prizms Silver" },
  { number: "438", name: "Jalen Milroe", team: "Seattle Seahawks", section: "Rookie Variations Prizms Silver" },
  { number: "439", name: "Elijah Arroyo", team: "Seattle Seahawks", section: "Rookie Variations Prizms Silver" },
  { number: "440", name: "Elic Ayomanor", team: "Tennessee Titans", section: "Rookie Variations Prizms Silver" },
  { number: "441", name: "Cam Ward", team: "Tennessee Titans", section: "Rookie Variations Prizms Silver" },
  { number: "442", name: "Jaylin Lane", team: "Washington Commanders", section: "Rookie Variations Prizms Silver" },
];