export type Prizm2025AutographEntry = {
  number: string;
  name: string;
  team?: string;
  section: string;
};

export const PRIZM_2025_AUTOGRAPHS: Prizm2025AutographEntry[] = [
  { number: "1", name: "Javonte Williams", team: "Dallas Cowboys", section: "Base Autographs" },
  { number: "3", name: "Christian Kirk", team: "Houston Texans", section: "Base Autographs" },
  { number: "8", name: "Rome Odunze", team: "Chicago Bears", section: "Base Autographs" },
  { number: "9", name: "Greg Rousseau", team: "Buffalo Bills", section: "Base Autographs" },
  { number: "10", name: "Jared Goff", team: "Detroit Lions", section: "Base Autographs" },
  { number: "13", name: "Tee Higgins", team: "Cincinnati Bengals", section: "Base Autographs" },
  { number: "14", name: "Earnest Byner", team: "Cleveland Browns", section: "Base Autographs" },
  { number: "15", name: "Craig Morton", team: "Denver Broncos", section: "Base Autographs" },
  { number: "16", name: "Cooper Kupp", team: "Seattle Seahawks", section: "Base Autographs" },
  { number: "17", name: "Eric Allen", team: "Philadelphia Eagles", section: "Base Autographs" },
  { number: "18", name: "Ladd McConkey", team: "Los Angeles Chargers", section: "Base Autographs" },
  { number: "20", name: "Chop Robinson", team: "Miami Dolphins", section: "Base Autographs" },
  { number: "21", name: "Matthew Stafford", team: "Los Angeles Rams", section: "Base Autographs" },
  { number: "22", name: "Nnamdi Madubuike", team: "Baltimore Ravens", section: "Base Autographs" },
  { number: "23", name: "Michael Pittman Jr.", team: "Indianapolis Colts", section: "Base Autographs" },
  { number: "25", name: "Jayden Reed", team: "Green Bay Packers", section: "Base Autographs" },
  { number: "29", name: "Jason Sehorn", team: "New York Giants", section: "Base Autographs" },
  { number: "30", name: "Jared Verse", team: "Los Angeles Rams", section: "Base Autographs" },
  { number: "33", name: "Hunter Henry", team: "New England Patriots", section: "Base Autographs" },
  { number: "34", name: "Ray-Ray McCloud", team: "Atlanta Falcons", section: "Base Autographs" },
  { number: "35", name: "Tarheeb Still", team: "Los Angeles Chargers", section: "Base Autographs" },
  { number: "37", name: "Leonard Fournette", team: "Jacksonville Jaguars", section: "Base Autographs" },
  { number: "39", name: "Vernon Davis", team: "San Francisco 49ers", section: "Base Autographs" },
  { number: "41", name: "Kerby Joseph", team: "Detroit Lions", section: "Base Autographs" },
  { number: "42", name: "Ray Lewis", team: "Baltimore Ravens", section: "Base Autographs" },
  { number: "43", name: "Josh Hines-Allen", team: "Jacksonville Jaguars", section: "Base Autographs" },
  { number: "44", name: "Jaylon Johnson", team: "Chicago Bears", section: "Base Autographs" },
  { number: "45", name: "Willis McGahee", team: "Buffalo Bills", section: "Base Autographs" },
  { number: "46", name: "Dwayne Bowe", team: "Kansas City Chiefs", section: "Base Autographs" },
  { number: "48", name: "Danielle Hunter", team: "Houston Texans", section: "Base Autographs" },
  { number: "50", name: "Breece Hall", team: "New York Jets", section: "Base Autographs" },
  { number: "52", name: "Warren Moon", team: "Kansas City Chiefs", section: "Base Autographs" },
  { number: "53", name: "Eric Moulds", team: "Houston Texans", section: "Base Autographs" },
  { number: "54", name: "Devaughn Vele", team: "Denver Broncos", section: "Base Autographs" },
  { number: "57", name: "Dak Prescott", team: "Dallas Cowboys", section: "Base Autographs" },
  { number: "60", name: "Ozzie Newsome", team: "Cleveland Browns", section: "Base Autographs" },
  { number: "63", name: "Andrew Van Ginkel", team: "Minnesota Vikings", section: "Base Autographs" },
  { number: "64", name: "Zach Ertz", team: "Washington Commanders", section: "Base Autographs" },
  { number: "65", name: "Dawson Knox", team: "Buffalo Bills", section: "Base Autographs" },
  { number: "68", name: "Travis Etienne Jr.", team: "Jacksonville Jaguars", section: "Base Autographs" },
  { number: "69", name: "Trey Benson", team: "Arizona Cardinals", section: "Base Autographs" },
  { number: "70", name: "DeVonta Smith", team: "Philadelphia Eagles", section: "Base Autographs" },
  { number: "72", name: "Jim Kelly", team: "Buffalo Bills", section: "Base Autographs" },
  { number: "73", name: "Myles Garrett", team: "Cleveland Browns", section: "Base Autographs" },
  { number: "75", name: "Marshall Faulk", team: "Indianapolis Colts", section: "Base Autographs" },
  { number: "77", name: "Ivan Pace Jr.", team: "Minnesota Vikings", section: "Base Autographs" },
  { number: "79", name: "Mike Gesicki", team: "Cincinnati Bengals", section: "Base Autographs" },
  { number: "81", name: "Justin Jefferson", team: "Minnesota Vikings", section: "Base Autographs" },
  { number: "83", name: "Eric Dickerson", team: "Los Angeles Raiders", section: "Base Autographs" },
  { number: "85", name: "Arik Armstead", team: "Jacksonville Jaguars", section: "Base Autographs" },
  { number: "86", name: "Raghib \"Rocket\" Ismail", team: "Carolina Panthers", section: "Base Autographs" },
  { number: "88", name: "Dave Krieg", team: "Seattle Seahawks", section: "Base Autographs" },
  { number: "89", name: "Dan Fouts", team: "San Diego Chargers", section: "Base Autographs" },
  { number: "90", name: "Denzel Ward", team: "Cleveland Browns", section: "Base Autographs" },
  { number: "91", name: "Zaire Franklin", team: "Indianapolis Colts", section: "Base Autographs" },
  { number: "92", name: "DJ Moore", team: "Chicago Bears", section: "Base Autographs" },
  { number: "93", name: "Terrell Suggs", team: "Baltimore Ravens", section: "Base Autographs" },
  { number: "94", name: "George Kittle", team: "San Francisco 49ers", section: "Base Autographs" },
  { number: "96", name: "Bijan Robinson", team: "Atlanta Falcons", section: "Base Autographs" },
  { number: "99", name: "Ricky Pearsall", team: "San Francisco 49ers", section: "Base Autographs" },
  { number: "100", name: "Braelon Allen", team: "New York Jets", section: "Base Autographs" },
  { number: "101", name: "Cade Stover", team: "Houston Texans", section: "Base Autographs" },
  { number: "102", name: "Hines Ward", team: "Pittsburgh Steelers", section: "Base Autographs" },
  { number: "106", name: "Zay Flowers", team: "Baltimore Ravens", section: "Base Autographs" },
  { number: "107", name: "Chris Chambers", team: "Miami Dolphins", section: "Base Autographs" },
  { number: "108", name: "Jonathan Taylor", team: "Indianapolis Colts", section: "Base Autographs" },
  { number: "110", name: "Mike Vrabel", team: "New England Patriots", section: "Base Autographs" },
  { number: "111", name: "Calvin Johnson", team: "Detroit Lions", section: "Base Autographs" },
  { number: "112", name: "Cole Kmet", team: "Chicago Bears", section: "Base Autographs" },
  { number: "114", name: "Antoine Winfield Jr.", team: "Tampa Bay Buccaneers", section: "Base Autographs" },
  { number: "115", name: "Rich Gannon", team: "Oakland Raiders", section: "Base Autographs" },
  { number: "118", name: "Xavier Legette", team: "Carolina Panthers", section: "Base Autographs" },
  { number: "119", name: "Charles Woodson", team: "Green Bay Packers", section: "Base Autographs" },
  { number: "120", name: "Dwight Freeney", team: "Indianapolis Colts", section: "Base Autographs" },
  { number: "121", name: "Torry Holt", team: "Jacksonville Jaguars", section: "Base Autographs" },
  { number: "122", name: "Sam LaPorta", team: "Detroit Lions", section: "Base Autographs" },
  { number: "128", name: "Randy White", team: "Dallas Cowboys", section: "Base Autographs" },
  { number: "137", name: "KaVontae Turpin", team: "Dallas Cowboys", section: "Base Autographs" },
  { number: "139", name: "Golden Tate III", team: "Detroit Lions", section: "Base Autographs" },
  { number: "140", name: "Frank Gore", team: "Buffalo Bills", section: "Base Autographs" },
  { number: "144", name: "Braden Fiske", team: "Los Angeles Rams", section: "Base Autographs" },
  { number: "146", name: "Jerry Jeudy", team: "Cleveland Browns", section: "Base Autographs" },
  { number: "147", name: "Brian Burns", team: "New York Giants", section: "Base Autographs" },
  { number: "149", name: "James Lofton", team: "Green Bay Packers", section: "Base Autographs" },
  { number: "150", name: "De'Von Achane", team: "Miami Dolphins", section: "Base Autographs" },
  { number: "151", name: "Cade Otton", team: "Tampa Bay Buccaneers", section: "Base Autographs" },
  { number: "152", name: "Carl Pickens", team: "Cincinnati Bengals", section: "Base Autographs" },
  { number: "154", name: "CeeDee Lamb", team: "Dallas Cowboys", section: "Base Autographs" },
  { number: "155", name: "David Njoku", team: "Cleveland Browns", section: "Base Autographs" },
  { number: "157", name: "Steve Spurrier", team: "San Francisco 49ers", section: "Base Autographs" },
  { number: "158", name: "Ricky Williams", team: "Baltimore Ravens", section: "Base Autographs" },
  { number: "159", name: "Jeremiah Owusu-Koramoah", team: "Cleveland Browns", section: "Base Autographs" },
  { number: "160", name: "Brett Favre", team: "Minnesota Vikings", section: "Base Autographs" },
  { number: "162", name: "Tre Tucker", team: "Las Vegas Raiders", section: "Base Autographs" },
  { number: "163", name: "Courtland Sutton", team: "Denver Broncos", section: "Base Autographs" },
  { number: "166", name: "Archie Manning", team: "Houston Oilers", section: "Base Autographs" },
  { number: "168", name: "Derrick Henry", team: "Baltimore Ravens", section: "Base Autographs" },
  { number: "169", name: "Bucky Irving", team: "Tampa Bay Buccaneers", section: "Base Autographs" },
  { number: "172", name: "Jaylen Waddle", team: "Miami Dolphins", section: "Base Autographs" },
  { number: "174", name: "Chris Boswell", team: "Pittsburgh Steelers", section: "Base Autographs" },
  { number: "175", name: "Tank Bigsby", team: "Jacksonville Jaguars", section: "Base Autographs" },
  { number: "177", name: "Trent McDuffie", team: "Kansas City Chiefs", section: "Base Autographs" },
  { number: "178", name: "Garrett Wilson", team: "New York Jets", section: "Base Autographs" },
  { number: "180", name: "Chad Johnson", team: "New England Patriots", section: "Base Autographs" },
  { number: "181", name: "Wes Welker", team: "New England Patriots", section: "Base Autographs" },
  { number: "185", name: "Ken O'Brien", team: "New York Jets", section: "Base Autographs" },
  { number: "186", name: "Spencer Rattler", team: "New Orleans Saints", section: "Base Autographs" },
  { number: "187", name: "Amon-Ra St. Brown", team: "Detroit Lions", section: "Base Autographs" },
  { number: "188", name: "Josh Jacobs", team: "Green Bay Packers", section: "Base Autographs" },
  { number: "192", name: "Chris Olave", team: "New Orleans Saints", section: "Base Autographs" },
  { number: "193", name: "Anthony Richardson", team: "Indianapolis Colts", section: "Base Autographs" },
  { number: "196", name: "Tyrann Mathieu", team: "New Orleans Saints", section: "Base Autographs" },
  { number: "200", name: "Jeremy Shockey", team: "New Orleans Saints", section: "Base Autographs" },
  { number: "201", name: "Joe Horn", team: "New Orleans Saints", section: "Base Autographs" },
  { number: "202", name: "Russell Wilson", team: "New York Giants", section: "Base Autographs" },
  { number: "203", name: "Tyrone Tracy Jr.", team: "New York Giants", section: "Base Autographs" },
  { number: "205", name: "Puka Nacua", team: "Los Angeles Rams", section: "Base Autographs" },
  { number: "207", name: "Ron Jaworski", team: "Philadelphia Eagles", section: "Base Autographs" },
  { number: "209", name: "Alec Pierce", team: "Indianapolis Colts", section: "Base Autographs" },
  { number: "212", name: "Warren Sapp", team: "Oakland Raiders", section: "Base Autographs" },
  { number: "213", name: "Brad Johnson", team: "Tampa Bay Buccaneers", section: "Base Autographs" },
  { number: "214", name: "Cris Carter", team: "Miami Dolphins", section: "Base Autographs" },
  { number: "215", name: "Justin Herbert", team: "Los Angeles Chargers", section: "Base Autographs" },
  { number: "216", name: "Ed Reed", team: "Houston Texans", section: "Base Autographs" },
  { number: "217", name: "Kam Chancellor", team: "Seattle Seahawks", section: "Base Autographs" },
  { number: "219", name: "Nick Bosa", team: "San Francisco 49ers", section: "Base Autographs" },
  { number: "223", name: "Terry McLaurin", team: "Washington Commanders", section: "Base Autographs" },
  { number: "224", name: "Antonio Gibson", team: "New England Patriots", section: "Base Autographs" },
  { number: "225", name: "Mike Evans", team: "Tampa Bay Buccaneers", section: "Base Autographs" },
  { number: "226", name: "Audric Estime", team: "Denver Broncos", section: "Base Autographs" },
  { number: "227", name: "Jerome Ford", team: "Cleveland Browns", section: "Base Autographs" },
  { number: "228", name: "Jalen Hurts", team: "Philadelphia Eagles", section: "Base Autographs" },
  { number: "229", name: "Cris Dishman", team: "Houston Oilers", section: "Base Autographs" },
  { number: "231", name: "Nico Collins", team: "Houston Texans", section: "Base Autographs" },
  { number: "232", name: "Tony Pollard", team: "Tennessee Titans", section: "Base Autographs" },
  { number: "233", name: "Devin Hester", team: "Atlanta Falcons", section: "Base Autographs" },
  { number: "234", name: "Dallas Goedert", team: "Philadelphia Eagles", section: "Base Autographs" },
  { number: "235", name: "Jerome Bettis", team: "Los Angeles Rams", section: "Base Autographs" },
  { number: "236", name: "D'Andre Swift", team: "Chicago Bears", section: "Base Autographs" },
  { number: "238", name: "Trevor Lawrence", team: "Jacksonville Jaguars", section: "Base Autographs" },
  { number: "239", name: "Zack Baun", team: "Philadelphia Eagles", section: "Base Autographs" },
  { number: "240", name: "Vince Ferragamo", team: "Los Angeles Rams", section: "Base Autographs" },
  { number: "242", name: "Austin Ekeler", team: "Washington Commanders", section: "Base Autographs" },
  { number: "244", name: "Chris Godwin", team: "Tampa Bay Buccaneers", section: "Base Autographs" },
  { number: "245", name: "Tremaine Edmunds", team: "Chicago Bears", section: "Base Autographs" },
  { number: "248", name: "Mike Rozier", team: "Houston Oilers", section: "Base Autographs" },
  { number: "249", name: "Tyreek Hill", team: "Miami Dolphins", section: "Base Autographs" },
  { number: "250", name: "Tyler Nubin", team: "New York Giants", section: "Base Autographs" },
  { number: "252", name: "Carnell Lake", team: "Pittsburgh Steelers", section: "Base Autographs" },
  { number: "254", name: "Jaxon Smith-Njigba", team: "Seattle Seahawks", section: "Base Autographs" },
  { number: "255", name: "Brock Purdy", team: "San Francisco 49ers", section: "Base Autographs" },
  { number: "256", name: "Dave Casper", team: "Minnesota Vikings", section: "Base Autographs" },
  { number: "257", name: "Lance Briggs", team: "Chicago Bears", section: "Base Autographs" },
  { number: "258", name: "Jauan Jennings", team: "San Francisco 49ers", section: "Base Autographs" },
  { number: "260", name: "Tony Dorsett", team: "Denver Broncos", section: "Base Autographs" },
  { number: "261", name: "Bobby Wagner", team: "Washington Commanders", section: "Base Autographs" },
  { number: "264", name: "Keyshawn Johnson", team: "Carolina Panthers", section: "Base Autographs" },
  { number: "266", name: "Drew Brees", team: "San Diego Chargers", section: "Base Autographs" },
  { number: "267", name: "Jeff Garcia", team: "San Francisco 49ers", section: "Base Autographs" },
  { number: "269", name: "Sam Darnold", team: "Seattle Seahawks", section: "Base Autographs" },
  { number: "270", name: "Tyjae Spears", team: "Tennessee Titans", section: "Base Autographs" },
  { number: "271", name: "Daniel Carlson", team: "Las Vegas Raiders", section: "Base Autographs" },
  { number: "273", name: "Rashod Bateman", team: "Baltimore Ravens", section: "Base Autographs" },
  { number: "274", name: "Trey McBride", team: "Arizona Cardinals", section: "Base Autographs" },
  { number: "275", name: "Keon Coleman", team: "Buffalo Bills", section: "Base Autographs" },
  { number: "276", name: "Jameson Williams", team: "Detroit Lions", section: "Base Autographs" },
  { number: "279", name: "J.J. McCarthy", team: "Minnesota Vikings", section: "Base Autographs" },
  { number: "281", name: "Deommodore Lenoir", team: "San Francisco 49ers", section: "Base Autographs" },
  { number: "282", name: "Ernest Jones", team: "Seattle Seahawks", section: "Base Autographs" },
  { number: "284", name: "Joe Theismann", team: "Washington Redskins", section: "Base Autographs" },
  { number: "285", name: "Odell Beckham Jr.", team: "New York Giants", section: "Base Autographs" },
  { number: "287", name: "Marquise Brown", team: "Kansas City Chiefs", section: "Base Autographs" },
  { number: "288", name: "Kordell Stewart", team: "Pittsburgh Steelers", section: "Base Autographs" },
  { number: "289", name: "Steven Jackson", team: "St. Louis Rams", section: "Base Autographs" },
  { number: "294", name: "DeSean Jackson", team: "Philadelphia Eagles", section: "Base Autographs" },
  { number: "295", name: "Wayne Chrebet", team: "New York Jets", section: "Base Autographs" },
  { number: "296", name: "Julius Peppers", team: "Chicago Bears", section: "Base Autographs" },
  { number: "300", name: "Tim Tebow", team: "Denver Broncos", section: "Base Autographs" },
  { number: "301", name: "Travis Hunter", team: "Jacksonville Jaguars", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "302", name: "Shedeur Sanders", team: "Cleveland Browns", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "303", name: "RJ Harvey", team: "Denver Broncos", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "304", name: "Mykel Williams", team: "San Francisco 49ers", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "305", name: "Bhayshul Tuten", team: "Jacksonville Jaguars", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "306", name: "Savion Williams", team: "Green Bay Packers", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "307", name: "Quinn Ewers", team: "Miami Dolphins", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "308", name: "Brashard Smith", team: "Kansas City Chiefs", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "309", name: "Elijah Arroyo", team: "Seattle Seahawks", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "311", name: "Tetairoa McMillan", team: "Carolina Panthers", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "312", name: "Will Campbell", team: "New England Patriots", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "313", name: "Quinshon Judkins", team: "Cleveland Browns", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "314", name: "Donovan Ezeiruaku", team: "Dallas Cowboys", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "315", name: "Ashton Jeanty", team: "Las Vegas Raiders", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "316", name: "Isaac TeSlaa", team: "Detroit Lions", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "317", name: "Jalen Milroe", team: "Seattle Seahawks", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "318", name: "Walter Nolen", team: "Arizona Cardinals", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "319", name: "Colston Loveland", team: "Chicago Bears", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "320", name: "Nick Emmanwori", team: "Seattle Seahawks", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "321", name: "Elic Ayomanor", team: "Tennessee Titans", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "322", name: "Tyler Booker", team: "Dallas Cowboys", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "323", name: "Jordan James", team: "San Francisco 49ers", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "324", name: "JT Tuimoloau", team: "Indianapolis Colts", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "325", name: "Jaydon Blue", team: "Dallas Cowboys", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "326", name: "Matthew Golden", team: "Green Bay Packers", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "327", name: "Tyler Shough", team: "New Orleans Saints", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "328", name: "Tyleik Williams", team: "Detroit Lions", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "329", name: "Mason Taylor", team: "New York Jets", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "330", name: "Andrew Mukuba", team: "Philadelphia Eagles", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "333", name: "Ollie Gordon II", team: "Miami Dolphins", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "334", name: "Jihaad Campbell", team: "Philadelphia Eagles", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "335", name: "Tahj Brooks", team: "Cincinnati Bengals", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "336", name: "Kyle Williams", team: "New England Patriots", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "338", name: "T.J. Sanders", team: "Buffalo Bills", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "339", name: "Tyler Warren", team: "Indianapolis Colts", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "340", name: "Kevin Winston Jr.", team: "Tennessee Titans", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "341", name: "Jalen Royals", team: "Kansas City Chiefs", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "342", name: "Riley Leonard", team: "Indianapolis Colts", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "343", name: "TreVeyon Henderson", team: "New England Patriots", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "344", name: "Shemar Stewart", team: "Cincinnati Bengals", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "345", name: "Trevor Etienne", team: "Carolina Panthers", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "346", name: "Jack Bech", team: "Las Vegas Raiders", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "347", name: "Kelvin Banks Jr.", team: "New Orleans Saints", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "349", name: "KeAndre Lambert-Smith", team: "Los Angeles Chargers", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "353", name: "Jarquez Hunter", team: "Los Angeles Rams", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "354", name: "Mason Graham", team: "Cleveland Browns", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "355", name: "Omarion Hampton", team: "Los Angeles Chargers", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "356", name: "Jaylin Lane", team: "Washington Commanders", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "358", name: "Donovan Jackson", team: "Minnesota Vikings", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "359", name: "Gunnar Helm", team: "Tennessee Titans", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "360", name: "Maxwell Hairston", team: "Buffalo Bills", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "361", name: "Tai Felton", team: "Minnesota Vikings", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "362", name: "Cam Miller", team: "Las Vegas Raiders", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "363", name: "Cam Skattebo", team: "New York Giants", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "365", name: "Dylan Sampson", team: "Cleveland Browns", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "366", name: "Pat Bryant", team: "Denver Broncos", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "367", name: "Will Howard", team: "Pittsburgh Steelers", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "369", name: "Dont'e Thornton Jr.", team: "Las Vegas Raiders", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "370", name: "Will Johnson", team: "Arizona Cardinals", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "371", name: "Tre Harris", team: "Los Angeles Chargers", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "372", name: "Dillon Gabriel", team: "Cleveland Browns", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "373", name: "Damien Martinez", team: "Seattle Seahawks", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "374", name: "Kenneth Grant", team: "Miami Dolphins", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "375", name: "Kaleb Johnson", team: "Pittsburgh Steelers", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "376", name: "Jayden Higgins", team: "Houston Texans", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "377", name: "Kyle McCord", team: "Philadelphia Eagles", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "378", name: "Phil Mafah", team: "Dallas Cowboys", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "379", name: "Terrance Ferguson", team: "Los Angeles Rams", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "380", name: "Shavon Revel Jr.", team: "Dallas Cowboys", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "381", name: "Tez Johnson", team: "Tampa Bay Buccaneers", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "382", name: "Josh Conerly Jr.", team: "Washington Commanders", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "383", name: "DJ Giddens", team: "Indianapolis Colts", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "384", name: "Carson Schwesinger", team: "Cleveland Browns", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "385", name: "Kalel Mullings", team: "Tennessee Titans", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "386", name: "Jaylin Noel", team: "Houston Texans", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "387", name: "Grey Zabel", team: "Seattle Seahawks", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "388", name: "Alfred Collins", team: "San Francisco 49ers", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "389", name: "Jordan Watkins", team: "San Francisco 49ers", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "392", name: "Graham Mertz", team: "Houston Texans", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "393", name: "Devin Neal", team: "New Orleans Saints", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "394", name: "Abdul Carter", team: "New York Giants", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "397", name: "Kurtis Rourke", team: "San Francisco 49ers", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "398", name: "Jalon Walker", team: "Atlanta Falcons", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "399", name: "Harold Fannin Jr.", team: "Cleveland Browns", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "400", name: "Trey Amos", team: "Washington Commanders", section: "Base - Rookie Autographs Silver Prizm" },
  { number: "1", name: "Javonte Williams", team: "Dallas Cowboys", section: "Base Prizm Choice Autographs /25" },
  { number: "3", name: "Christian Kirk", team: "Houston Texans", section: "Base Prizm Choice Autographs /100" },
  { number: "8", name: "Rome Odunze", team: "Chicago Bears", section: "Base Prizm Choice Autographs /25" },
  { number: "9", name: "Greg Rousseau", team: "Buffalo Bills", section: "Base Prizm Choice Autographs /25" },
  { number: "10", name: "Jared Goff", team: "Detroit Lions", section: "Base Prizm Choice Autographs /10" },
  { number: "13", name: "Tee Higgins", team: "Cincinnati Bengals", section: "Base Prizm Choice Autographs /25" },
  { number: "14", name: "Earnest Byner", team: "Cleveland Browns", section: "Base Prizm Choice Autographs /25" },
  { number: "15", name: "Craig Morton", team: "Denver Broncos", section: "Base Prizm Choice Autographs /25" },
  { number: "16", name: "Cooper Kupp", team: "Seattle Seahawks", section: "Base Prizm Choice Autographs /25" },
  { number: "17", name: "Eric Allen", team: "Philadelphia Eagles", section: "Base Prizm Choice Autographs /25" },
  { number: "18", name: "Ladd McConkey", team: "Los Angeles Chargers", section: "Base Prizm Choice Autographs /25" },
  { number: "21", name: "Matthew Stafford", team: "Los Angeles Rams", section: "Base Prizm Choice Autographs /25" },
  { number: "22", name: "Nnamdi Madubuike", team: "Baltimore Ravens", section: "Base Prizm Choice Autographs /25" },
  { number: "25", name: "Jayden Reed", team: "Green Bay Packers", section: "Base Prizm Choice Autographs /25" },
  { number: "29", name: "Jason Sehorn", team: "New York Giants", section: "Base Prizm Choice Autographs /25" },
  { number: "30", name: "Jared Verse", team: "Los Angeles Rams", section: "Base Prizm Choice Autographs /100" },
  { number: "33", name: "Hunter Henry", team: "New England Patriots", section: "Base Prizm Choice Autographs /25" },
  { number: "37", name: "Leonard Fournette", team: "Jacksonville Jaguars", section: "Base Prizm Choice Autographs /25" },
  { number: "39", name: "Vernon Davis", team: "San Francisco 49ers", section: "Base Prizm Choice Autographs /25" },
  { number: "41", name: "Kerby Joseph", team: "Detroit Lions", section: "Base Prizm Choice Autographs /25" },
  { number: "42", name: "Ray Lewis", team: "Baltimore Ravens", section: "Base Prizm Choice Autographs /100" },
  { number: "43", name: "Josh Hines-Allen", team: "Jacksonville Jaguars", section: "Base Prizm Choice Autographs /100" },
  { number: "45", name: "Willis McGahee", team: "Buffalo Bills", section: "Base Prizm Choice Autographs /25" },
  { number: "46", name: "Dwayne Bowe", team: "Kansas City Chiefs", section: "Base Prizm Choice Autographs /25" },
  { number: "48", name: "Danielle Hunter", team: "Houston Texans", section: "Base Prizm Choice Autographs /25" },
  { number: "50", name: "Breece Hall", team: "New York Jets", section: "Base Prizm Choice Autographs /25" },
  { number: "53", name: "Eric Moulds", team: "Houston Texans", section: "Base Prizm Choice Autographs /25" },
  { number: "54", name: "Devaughn Vele", team: "Denver Broncos", section: "Base Prizm Choice Autographs /25" },
  { number: "57", name: "Dak Prescott", team: "Dallas Cowboys", section: "Base Prizm Choice Autographs /100" },
  { number: "60", name: "Ozzie Newsome", team: "Cleveland Browns", section: "Base Prizm Choice Autographs /25" },
  { number: "70", name: "DeVonta Smith", team: "Philadelphia Eagles", section: "Base Prizm Choice Autographs /100" },
  { number: "72", name: "Jim Kelly", team: "Buffalo Bills", section: "Base Prizm Choice Autographs /10" },
  { number: "75", name: "Marshall Faulk", team: "Indianapolis Colts", section: "Base Prizm Choice Autographs /25" },
  { number: "77", name: "Ivan Pace Jr.", team: "Minnesota Vikings", section: "Base Prizm Choice Autographs /25" },
  { number: "79", name: "Mike Gesicki", team: "Cincinnati Bengals", section: "Base Prizm Choice Autographs /100" },
  { number: "81", name: "Justin Jefferson", team: "Minnesota Vikings", section: "Base Prizm Choice Autographs /50" },
  { number: "83", name: "Eric Dickerson", team: "Los Angeles Raiders", section: "Base Prizm Choice Autographs /10" },
  { number: "85", name: "Arik Armstead", team: "Jacksonville Jaguars", section: "Base Prizm Choice Autographs /25" },
  { number: "86", name: "Raghib \"Rocket\" Ismail", team: "Carolina Panthers", section: "Base Prizm Choice Autographs /25" },
  { number: "88", name: "Dave Krieg", team: "Seattle Seahawks", section: "Base Prizm Choice Autographs /25" },
  { number: "89", name: "Dan Fouts", team: "San Diego Chargers", section: "Base Prizm Choice Autographs /25" },
  { number: "90", name: "Denzel Ward", team: "Cleveland Browns", section: "Base Prizm Choice Autographs /25" },
  { number: "91", name: "Zaire Franklin", team: "Indianapolis Colts", section: "Base Prizm Choice Autographs /25" },
  { number: "92", name: "DJ Moore", team: "Chicago Bears", section: "Base Prizm Choice Autographs /25" },
  { number: "93", name: "Terrell Suggs", team: "Baltimore Ravens", section: "Base Prizm Choice Autographs /25" },
  { number: "94", name: "George Kittle", team: "San Francisco 49ers", section: "Base Prizm Choice Autographs /100" },
  { number: "96", name: "Bijan Robinson", team: "Atlanta Falcons", section: "Base Prizm Choice Autographs /25" },
  { number: "99", name: "Ricky Pearsall", team: "San Francisco 49ers", section: "Base Prizm Choice Autographs /25" },
  { number: "102", name: "Hines Ward", team: "Pittsburgh Steelers", section: "Base Prizm Choice Autographs /25" },
  { number: "106", name: "Zay Flowers", team: "Baltimore Ravens", section: "Base Prizm Choice Autographs /100" },
  { number: "107", name: "Chris Chambers", team: "Miami Dolphins", section: "Base Prizm Choice Autographs /25" },
  { number: "111", name: "Calvin Johnson", team: "Detroit Lions", section: "Base Prizm Choice Autographs /25" },
  { number: "115", name: "Rich Gannon", team: "Oakland Raiders", section: "Base Prizm Choice Autographs /25" },
  { number: "118", name: "Xavier Legette", team: "Carolina Panthers", section: "Base Prizm Choice Autographs /100" },
  { number: "119", name: "Charles Woodson", team: "Green Bay Packers", section: "Base Prizm Choice Autographs /25" },
  { number: "120", name: "Dwight Freeney", team: "Indianapolis Colts", section: "Base Prizm Choice Autographs /25" },
  { number: "121", name: "Torry Holt", team: "Jacksonville Jaguars", section: "Base Prizm Choice Autographs /25" },
  { number: "122", name: "Sam LaPorta", team: "Detroit Lions", section: "Base Prizm Choice Autographs /25" },
  { number: "128", name: "Randy White", team: "Dallas Cowboys", section: "Base Prizm Choice Autographs /25" },
  { number: "147", name: "Brian Burns", team: "New York Giants", section: "Base Prizm Choice Autographs /25" },
  { number: "149", name: "James Lofton", team: "Green Bay Packers", section: "Base Prizm Choice Autographs /25" },
  { number: "150", name: "De'Von Achane", team: "Miami Dolphins", section: "Base Prizm Choice Autographs /25" },
  { number: "151", name: "Cade Otton", team: "Tampa Bay Buccaneers", section: "Base Prizm Choice Autographs /25" },
  { number: "152", name: "Carl Pickens", team: "Cincinnati Bengals", section: "Base Prizm Choice Autographs /25" },
  { number: "154", name: "CeeDee Lamb", team: "Dallas Cowboys", section: "Base Prizm Choice Autographs /100" },
  { number: "155", name: "David Njoku", team: "Cleveland Browns", section: "Base Prizm Choice Autographs /100" },
  { number: "157", name: "Steve Spurrier", team: "San Francisco 49ers", section: "Base Prizm Choice Autographs /100" },
  { number: "159", name: "Jeremiah Owusu-Koramoah", team: "Cleveland Browns", section: "Base Prizm Choice Autographs /100" },
  { number: "160", name: "Brett Favre", team: "Minnesota Vikings", section: "Base Prizm Choice Autographs /100" },
  { number: "166", name: "Archie Manning", team: "Houston Oilers", section: "Base Prizm Choice Autographs /100" },
  { number: "168", name: "Derrick Henry", team: "Baltimore Ravens", section: "Base Prizm Choice Autographs /100" },
  { number: "169", name: "Bucky Irving", team: "Tampa Bay Buccaneers", section: "Base Prizm Choice Autographs /100" },
  { number: "174", name: "Chris Boswell", team: "Pittsburgh Steelers", section: "Base Prizm Choice Autographs /100" },
  { number: "175", name: "Tank Bigsby", team: "Jacksonville Jaguars", section: "Base Prizm Choice Autographs /100" },
  { number: "177", name: "Trent McDuffie", team: "Kansas City Chiefs", section: "Base Prizm Choice Autographs /50" },
  { number: "180", name: "Chad Johnson", team: "New England Patriots", section: "Base Prizm Choice Autographs /100" },
  { number: "185", name: "Ken O'Brien", team: "New York Jets", section: "Base Prizm Choice Autographs /100" },
  { number: "193", name: "Anthony Richardson", team: "Indianapolis Colts", section: "Base Prizm Choice Autographs /100" },
  { number: "196", name: "Tyrann Mathieu", team: "New Orleans Saints", section: "Base Prizm Choice Autographs /100" },
  { number: "200", name: "Jeremy Shockey", team: "New Orleans Saints", section: "Base Prizm Choice Autographs /100" },
  { number: "201", name: "Joe Horn", team: "New Orleans Saints", section: "Base Prizm Choice Autographs /100" },
  { number: "202", name: "Russell Wilson", team: "New York Giants", section: "Base Prizm Choice Autographs /100" },
  { number: "203", name: "Tyrone Tracy Jr.", team: "New York Giants", section: "Base Prizm Choice Autographs /100" },
  { number: "205", name: "Puka Nacua", team: "Los Angeles Rams", section: "Base Prizm Choice Autographs /100" },
  { number: "207", name: "Ron Jaworski", team: "Philadelphia Eagles", section: "Base Prizm Choice Autographs /25" },
  { number: "209", name: "Alec Pierce", team: "Indianapolis Colts", section: "Base Prizm Choice Autographs /100" },
  { number: "212", name: "Warren Sapp", team: "Oakland Raiders", section: "Base Prizm Choice Autographs /100" },
  { number: "213", name: "Brad Johnson", team: "Tampa Bay Buccaneers", section: "Base Prizm Choice Autographs /100" },
  { number: "214", name: "Cris Carter", team: "Miami Dolphins", section: "Base Prizm Choice Autographs /25" },
  { number: "216", name: "Ed Reed", team: "Houston Texans", section: "Base Prizm Choice Autographs /50" },
  { number: "219", name: "Nick Bosa", team: "San Francisco 49ers", section: "Base Prizm Choice Autographs /50" },
  { number: "223", name: "Terry McLaurin", team: "Washington Commanders", section: "Base Prizm Choice Autographs /25" },
  { number: "224", name: "Antonio Gibson", team: "New England Patriots", section: "Base Prizm Choice Autographs /25" },
  { number: "225", name: "Mike Evans", team: "Tampa Bay Buccaneers", section: "Base Prizm Choice Autographs /100" },
  { number: "228", name: "Jalen Hurts", team: "Philadelphia Eagles", section: "Base Prizm Choice Autographs /100" },
  { number: "229", name: "Cris Dishman", team: "Houston Oilers", section: "Base Prizm Choice Autographs /25" },
  { number: "233", name: "Devin Hester", team: "Atlanta Falcons", section: "Base Prizm Choice Autographs /25" },
  { number: "234", name: "Dallas Goedert", team: "Philadelphia Eagles", section: "Base Prizm Choice Autographs /25" },
  { number: "235", name: "Jerome Bettis", team: "Los Angeles Rams", section: "Base Prizm Choice Autographs /25" },
  { number: "236", name: "D'Andre Swift", team: "Chicago Bears", section: "Base Prizm Choice Autographs /25" },
  { number: "238", name: "Trevor Lawrence", team: "Jacksonville Jaguars", section: "Base Prizm Choice Autographs /100" },
  { number: "239", name: "Zack Baun", team: "Philadelphia Eagles", section: "Base Prizm Choice Autographs /50" },
  { number: "244", name: "Chris Godwin", team: "Tampa Bay Buccaneers", section: "Base Prizm Choice Autographs /100" },
  { number: "245", name: "Tremaine Edmunds", team: "Chicago Bears", section: "Base Prizm Choice Autographs /100" },
  { number: "248", name: "Mike Rozier", team: "Houston Oilers", section: "Base Prizm Choice Autographs /100" },
  { number: "249", name: "Tyreek Hill", team: "Miami Dolphins", section: "Base Prizm Choice Autographs /25" },
  { number: "250", name: "Tyler Nubin", team: "New York Giants", section: "Base Prizm Choice Autographs /100" },
  { number: "252", name: "Carnell Lake", team: "Pittsburgh Steelers", section: "Base Prizm Choice Autographs /100" },
  { number: "255", name: "Brock Purdy", team: "San Francisco 49ers", section: "Base Prizm Choice Autographs /100" },
  { number: "256", name: "Dave Casper", team: "Minnesota Vikings", section: "Base Prizm Choice Autographs /100" },
  { number: "257", name: "Lance Briggs", team: "Chicago Bears", section: "Base Prizm Choice Autographs /100" },
  { number: "258", name: "Jauan Jennings", team: "San Francisco 49ers", section: "Base Prizm Choice Autographs /100" },
  { number: "260", name: "Tony Dorsett", team: "Denver Broncos", section: "Base Prizm Choice Autographs /100" },
  { number: "261", name: "Bobby Wagner", team: "Washington Commanders", section: "Base Prizm Choice Autographs /100" },
  { number: "264", name: "Keyshawn Johnson", team: "Carolina Panthers", section: "Base Prizm Choice Autographs /100" },
  { number: "266", name: "Drew Brees", team: "San Diego Chargers", section: "Base Prizm Choice Autographs /100" },
  { number: "267", name: "Jeff Garcia", team: "San Francisco 49ers", section: "Base Prizm Choice Autographs /100" },
  { number: "269", name: "Sam Darnold", team: "Seattle Seahawks", section: "Base Prizm Choice Autographs /100" },
  { number: "271", name: "Daniel Carlson", team: "Las Vegas Raiders", section: "Base Prizm Choice Autographs /100" },
  { number: "273", name: "Rashod Bateman", team: "Baltimore Ravens", section: "Base Prizm Choice Autographs /100" },
  { number: "275", name: "Keon Coleman", team: "Buffalo Bills", section: "Base Prizm Choice Autographs /100" },
  { number: "281", name: "Deommodore Lenoir", team: "San Francisco 49ers", section: "Base Prizm Choice Autographs /100" },
  { number: "282", name: "Ernest Jones", team: "Seattle Seahawks", section: "Base Prizm Choice Autographs /100" },
  { number: "284", name: "Joe Theismann", team: "Washington Redskins", section: "Base Prizm Choice Autographs /100" },
  { number: "285", name: "Odell Beckham Jr.", team: "New York Giants", section: "Base Prizm Choice Autographs /100" },
  { number: "287", name: "Marquise Brown", team: "Kansas City Chiefs", section: "Base Prizm Choice Autographs /100" },
  { number: "288", name: "Kordell Stewart", team: "Pittsburgh Steelers", section: "Base Prizm Choice Autographs /100" },
  { number: "289", name: "Steven Jackson", team: "St. Louis Rams", section: "Base Prizm Choice Autographs /100" },
  { number: "294", name: "DeSean Jackson", team: "Philadelphia Eagles", section: "Base Prizm Choice Autographs /100" },
  { number: "295", name: "Wayne Chrebet", team: "New York Jets", section: "Base Prizm Choice Autographs /100" },
  { number: "296", name: "Julius Peppers", team: "Chicago Bears", section: "Base Prizm Choice Autographs /100" },
  { number: "300", name: "Tim Tebow", team: "Denver Broncos", section: "Base Prizm Choice Autographs /100" },
  { number: "301", name: "Travis Hunter", team: "Jacksonville Jaguars", section: "Rookie Prizm Choice Auto /100" },
  { number: "302", name: "Shedeur Sanders", team: "Cleveland Browns", section: "Rookie Prizm Choice Auto /100" },
  { number: "303", name: "RJ Harvey", team: "Denver Broncos", section: "Rookie Prizm Choice Auto /100" },
  { number: "304", name: "Mykel Williams", team: "San Francisco 49ers", section: "Rookie Prizm Choice Auto /100" },
  { number: "305", name: "Bhayshul Tuten", team: "Jacksonville Jaguars", section: "Rookie Prizm Choice Auto /100" },
  { number: "306", name: "Savion Williams", team: "Green Bay Packers", section: "Rookie Prizm Choice Auto /100" },
  { number: "307", name: "Quinn Ewers", team: "Miami Dolphins", section: "Rookie Prizm Choice Auto /100" },
  { number: "309", name: "Elijah Arroyo", team: "Seattle Seahawks", section: "Rookie Prizm Choice Auto /100" },
  { number: "311", name: "Tetairoa McMillan", team: "Carolina Panthers", section: "Rookie Prizm Choice Auto /100" },
  { number: "312", name: "Will Campbell", team: "New England Patriots", section: "Rookie Prizm Choice Auto /100" },
  { number: "313", name: "Quinshon Judkins", team: "Cleveland Browns", section: "Rookie Prizm Choice Auto /100" },
  { number: "314", name: "Donovan Ezeiruaku", team: "Dallas Cowboys", section: "Rookie Prizm Choice Auto /100" },
  { number: "315", name: "Ashton Jeanty", team: "Las Vegas Raiders", section: "Rookie Prizm Choice Auto /100" },
  { number: "317", name: "Jalen Milroe", team: "Seattle Seahawks", section: "Rookie Prizm Choice Auto /100" },
  { number: "319", name: "Colston Loveland", team: "Chicago Bears", section: "Rookie Prizm Choice Auto /100" },
  { number: "320", name: "Nick Emmanwori", team: "Seattle Seahawks", section: "Rookie Prizm Choice Auto /100" },
  { number: "321", name: "Elic Ayomanor", team: "Tennessee Titans", section: "Rookie Prizm Choice Auto /100" },
  { number: "323", name: "Jordan James", team: "San Francisco 49ers", section: "Rookie Prizm Choice Auto /100" },
  { number: "325", name: "Jaydon Blue", team: "Dallas Cowboys", section: "Rookie Prizm Choice Auto /100" },
  { number: "326", name: "Matthew Golden", team: "Green Bay Packers", section: "Rookie Prizm Choice Auto /100" },
  { number: "327", name: "Tyler Shough", team: "New Orleans Saints", section: "Rookie Prizm Choice Auto /100" },
  { number: "330", name: "Andrew Mukuba", team: "Philadelphia Eagles", section: "Rookie Prizm Choice Auto /100" },
  { number: "333", name: "Ollie Gordon II", team: "Miami Dolphins", section: "Rookie Prizm Choice Auto /100" },
  { number: "335", name: "Tahj Brooks", team: "Cincinnati Bengals", section: "Rookie Prizm Choice Auto /100" },
  { number: "338", name: "T.J. Sanders", team: "Buffalo Bills", section: "Rookie Prizm Choice Auto /100" },
  { number: "339", name: "Tyler Warren", team: "Indianapolis Colts", section: "Rookie Prizm Choice Auto /100" },
  { number: "341", name: "Jalen Royals", team: "Kansas City Chiefs", section: "Rookie Prizm Choice Auto /100" },
  { number: "342", name: "Riley Leonard", team: "Indianapolis Colts", section: "Rookie Prizm Choice Auto /100" },
  { number: "343", name: "TreVeyon Henderson", team: "New England Patriots", section: "Rookie Prizm Choice Auto /100" },
  { number: "344", name: "Shemar Stewart", team: "Cincinnati Bengals", section: "Rookie Prizm Choice Auto /100" },
  { number: "345", name: "Trevor Etienne", team: "Carolina Panthers", section: "Rookie Prizm Choice Auto /100" },
  { number: "346", name: "Jack Bech", team: "Las Vegas Raiders", section: "Rookie Prizm Choice Auto /100" },
  { number: "347", name: "Kelvin Banks Jr.", team: "New Orleans Saints", section: "Rookie Prizm Choice Auto /100" },
  { number: "353", name: "Jarquez Hunter", team: "Los Angeles Rams", section: "Rookie Prizm Choice Auto /100" },
  { number: "354", name: "Mason Graham", team: "Cleveland Browns", section: "Rookie Prizm Choice Auto /100" },
  { number: "355", name: "Omarion Hampton", team: "Los Angeles Chargers", section: "Rookie Prizm Choice Auto /100" },
  { number: "356", name: "Jaylin Lane", team: "Washington Commanders", section: "Rookie Prizm Choice Auto /100" },
  { number: "358", name: "Donovan Jackson", team: "Minnesota Vikings", section: "Rookie Prizm Choice Auto /100" },
  { number: "359", name: "Gunnar Helm", team: "Tennessee Titans", section: "Rookie Prizm Choice Auto /100" },
  { number: "360", name: "Maxwell Hairston", team: "Buffalo Bills", section: "Rookie Prizm Choice Auto /100" },
  { number: "361", name: "Tai Felton", team: "Minnesota Vikings", section: "Rookie Prizm Choice Auto /100" },
  { number: "362", name: "Cam Miller", team: "Las Vegas Raiders", section: "Rookie Prizm Choice Auto /100" },
  { number: "363", name: "Cam Skattebo", team: "New York Giants", section: "Rookie Prizm Choice Auto /100" },
  { number: "365", name: "Dylan Sampson", team: "Cleveland Browns", section: "Rookie Prizm Choice Auto /100" },
  { number: "366", name: "Pat Bryant", team: "Denver Broncos", section: "Rookie Prizm Choice Auto /100" },
  { number: "367", name: "Will Howard", team: "Pittsburgh Steelers", section: "Rookie Prizm Choice Auto /100" },
  { number: "369", name: "Dont'e Thornton Jr.", team: "Las Vegas Raiders", section: "Rookie Prizm Choice Auto /100" },
  { number: "370", name: "Will Johnson", team: "Arizona Cardinals", section: "Rookie Prizm Choice Auto /100" },
  { number: "371", name: "Tre Harris", team: "Los Angeles Chargers", section: "Rookie Prizm Choice Auto /100" },
  { number: "372", name: "Dillon Gabriel", team: "Cleveland Browns", section: "Rookie Prizm Choice Auto /100" },
  { number: "374", name: "Kenneth Grant", team: "Miami Dolphins", section: "Rookie Prizm Choice Auto /100" },
  { number: "376", name: "Jayden Higgins", team: "Houston Texans", section: "Rookie Prizm Choice Auto /100" },
  { number: "377", name: "Kyle McCord", team: "Philadelphia Eagles", section: "Rookie Prizm Choice Auto /100" },
  { number: "378", name: "Phil Mafah", team: "Dallas Cowboys", section: "Rookie Prizm Choice Auto /100" },
  { number: "379", name: "Terrance Ferguson", team: "Los Angeles Rams", section: "Rookie Prizm Choice Auto /100" },
  { number: "380", name: "Shavon Revel Jr.", team: "Dallas Cowboys", section: "Rookie Prizm Choice Auto /100" },
  { number: "381", name: "Tez Johnson", team: "Tampa Bay Buccaneers", section: "Rookie Prizm Choice Auto /100" },
  { number: "382", name: "Josh Conerly Jr.", team: "Washington Commanders", section: "Rookie Prizm Choice Auto /100" },
  { number: "385", name: "Kalel Mullings", team: "Tennessee Titans", section: "Rookie Prizm Choice Auto /100" },
  { number: "386", name: "Jaylin Noel", team: "Houston Texans", section: "Rookie Prizm Choice Auto /100" },
  { number: "388", name: "Alfred Collins", team: "San Francisco 49ers", section: "Rookie Prizm Choice Auto /100" },
  { number: "389", name: "Jordan Watkins", team: "San Francisco 49ers", section: "Rookie Prizm Choice Auto /100" },
  { number: "392", name: "Graham Mertz", team: "Houston Texans", section: "Rookie Prizm Choice Auto /100" },
  { number: "393", name: "Devin Neal", team: "New Orleans Saints", section: "Rookie Prizm Choice Auto /100" },
  { number: "397", name: "Kurtis Rourke", team: "San Francisco 49ers", section: "Rookie Prizm Choice Auto /100" },
  { number: "398", name: "Jalon Walker", team: "Atlanta Falcons", section: "Rookie Prizm Choice Auto /100" },
  { number: "399", name: "Harold Fannin Jr.", team: "Cleveland Browns", section: "Rookie Prizm Choice Auto /100" },
  { number: "1", name: "Shedeur Sanders/Travis Hunter", team: "Cleveland Browns/Jacksonville Jaguars", section: "Dual Patch Autographs /99" },
  { number: "2", name: "Tony Pollard/Chris Johnson", team: "Tennessee Titans", section: "Dual Patch Autographs" },
  { number: "3", name: "Plaxico Burress/Hines Ward", team: "Pittsburgh Steelers", section: "Dual Patch Autographs" },
  { number: "4", name: "Omarion Hampton/Ashton Jeanty", team: "Los Angeles Chargers/Las Vegas Raiders", section: "Dual Patch Autographs /99" },
  { number: "5", name: "Edgerrin James/Willis McGahee", team: "Indianapolis Colts/Buffalo Bills", section: "Dual Patch Autographs /99" },
  { number: "6", name: "J.J. McCarthy/Jordan Addison", team: "Minnesota Vikings", section: "Dual Patch Autographs" },
  { number: "7", name: "Rome Odunze/Keon Coleman", team: "Chicago Bears/Buffalo Bills", section: "Dual Patch Autographs /99" },
  { number: "8", name: "Antonio Gates/Jimmy Graham", team: "San Diego Chargers/New Orleans Saints", section: "Dual Patch Autographs /99" },
  { number: "9", name: "Quinshon Judkins/Dylan Sampson", team: "Cleveland Browns", section: "Dual Patch Autographs /99" },
  { number: "10", name: "Dan Fouts/Kellen Winslow", team: "San Diego Chargers", section: "Dual Patch Autographs /99" },
  { number: "13", name: "Ron Jaworski/Mike Quick", team: "Philadelphia Eagles", section: "Dual Patch Autographs /99" },
  { number: "15", name: "Sam LaPorta/Trey McBride", team: "Detroit Lions/Arizona Cardinals", section: "Dual Patch Autographs /99" },
  { number: "16", name: "Sean McDermott/Marv Levy", team: "Buffalo Bills", section: "Dual Patch Autographs" },
  { number: "17", name: "Cole Kmet/Colston Loveland", team: "Chicago Bears", section: "Dual Patch Autographs /99" },
  { number: "18", name: "Xavier Legette/Tetairoa McMillan", team: "Carolina Panthers", section: "Dual Patch Autographs /99" },
  { number: "19", name: "Jonathan Ogden/Walter Jones", team: "Baltimore Ravens/Seattle Seahawks", section: "Dual Patch Autographs /99" },
  { number: "20", name: "Cooper Kupp/Jaxon Smith-Njigba", team: "Seattle Seahawks", section: "Dual Patch Autographs" },
  { number: "1", name: "Paul Warfield", team: "Miami Dolphins", section: "Flashback Autographs /149" },
  { number: "2", name: "Joe Morris", team: "New York Giants", section: "Flashback Autographs /149" },
  { number: "3", name: "Dexter Manley", team: "Washington Redskins", section: "Flashback Autographs /149" },
  { number: "4", name: "Ken Houston", team: "Houston Oilers", section: "Flashback Autographs /149" },
  { number: "5", name: "Bruce Matthews", team: "Houston Oilers", section: "Flashback Autographs /149" },
  { number: "6", name: "Jim Zorn", team: "Seattle Seahawks", section: "Flashback Autographs" },
  { number: "7", name: "Tom Rathman", team: "San Francisco 49ers", section: "Flashback Autographs /149" },
  { number: "8", name: "John Brodie", team: "San Francisco 49ers", section: "Flashback Autographs /149" },
  { number: "9", name: "Louis Lipps", team: "Pittsburgh Steelers", section: "Flashback Autographs" },
  { number: "10", name: "Wilbert Montgomery", team: "Philadelphia Eagles", section: "Flashback Autographs /149" },
  { number: "11", name: "Freeman McNeil", team: "New York Jets", section: "Flashback Autographs /149" },
  { number: "12", name: "Rickey Jackson", team: "New Orleans Saints", section: "Flashback Autographs /149" },
  { number: "13", name: "Stephen Gostkowski", team: "New England Patriots", section: "Flashback Autographs /149" },
  { number: "14", name: "Alan Page", team: "Minnesota Vikings", section: "Flashback Autographs /149" },
  { number: "15", name: "Gus Frerotte", team: "Washington Redskins", section: "Flashback Autographs /149" },
  { number: "16", name: "Wes Chandler", team: "San Diego Chargers", section: "Flashback Autographs" },
  { number: "17", name: "Fred Biletnikoff", team: "Oakland Raiders", section: "Flashback Autographs /149" },
  { number: "18", name: "Derrick Johnson", team: "Kansas City Chiefs", section: "Flashback Autographs /149" },
  { number: "19", name: "Jerry Kramer", team: "Green Bay Packers", section: "Flashback Autographs /149" },
  { number: "20", name: "William Andrews", team: "Atlanta Falcons", section: "Flashback Autographs" },
  { number: "21", name: "Billy Sims", team: "Detroit Lions", section: "Flashback Autographs /149" },
  { number: "23", name: "Jim Jeffcoat", team: "Dallas Cowboys", section: "Flashback Autographs /149" },
  { number: "24", name: "Leroy Kelly", team: "Cleveland Browns", section: "Flashback Autographs" },
  { number: "25", name: "Vince Ferragamo", team: "Los Angeles Rams", section: "Flashback Autographs" },
  { number: "2", name: "CeeDee Lamb", team: "Dallas Cowboys", section: "Patch Autographs Prizm Silver /99" },
  { number: "3", name: "Aaron Donald", team: "Los Angeles Rams", section: "Patch Autographs Prizm Silver /99" },
  { number: "4", name: "Trevor Lawrence", team: "Jacksonville Jaguars", section: "Patch Autographs Prizm Silver /99" },
  { number: "5", name: "Roddy White", team: "Atlanta Falcons", section: "Patch Autographs Prizm Silver /99" },
  { number: "6", name: "Earl Thomas III", team: "Seattle Seahawks", section: "Patch Autographs Prizm Silver /99" },
  { number: "7", name: "Matt Schaub", team: "Houston Texans", section: "Patch Autographs Prizm Silver /99" },
  { number: "8", name: "Ryan Fitzpatrick", team: "Buffalo Bills", section: "Patch Autographs Prizm Silver /99" },
  { number: "9", name: "DJ Moore", team: "Chicago Bears", section: "Patch Autographs Prizm Silver /99" },
  { number: "10", name: "Chase Brown", team: "Cincinnati Bengals", section: "Patch Autographs Prizm Silver /99" },
  { number: "11", name: "Corey Dillon", team: "New England Patriots", section: "Patch Autographs Prizm Silver /99" },
  { number: "12", name: "Ozzie Newsome", team: "Cleveland Browns", section: "Patch Autographs Prizm Silver /99" },
  { number: "14", name: "Emmanuel Sanders", team: "Denver Broncos", section: "Patch Autographs Prizm Silver /99" },
  { number: "15", name: "Brian Branch", team: "Detroit Lions", section: "Patch Autographs Prizm Silver /99" },
  { number: "16", name: "Eric Moulds", team: "Buffalo Bills", section: "Patch Autographs Prizm Silver /99" },
  { number: "17", name: "Danielle Hunter", team: "Houston Texans", section: "Patch Autographs Prizm Silver /99" },
  { number: "18", name: "Ted Hendricks", team: "Baltimore Colts", section: "Patch Autographs Prizm Silver /99" },
  { number: "19", name: "Marquise Brown", team: "Kansas City Chiefs", section: "Patch Autographs Prizm Silver /99" },
  { number: "20", name: "Rich Gannon", team: "Oakland Raiders", section: "Patch Autographs Prizm Silver /99" },
  { number: "21", name: "Jim Everett", team: "Los Angeles Rams", section: "Patch Autographs Prizm Silver" },
  { number: "22", name: "Zach Thomas", team: "Miami Dolphins", section: "Patch Autographs Prizm Silver /99" },
  { number: "23", name: "Harrison Smith", team: "Minnesota Vikings", section: "Patch Autographs Prizm Silver /99" },
  { number: "24", name: "Daunte Culpepper", team: "Minnesota Vikings", section: "Patch Autographs Prizm Silver /99" },
  { number: "25", name: "Wes Welker", team: "New England Patriots", section: "Patch Autographs Prizm Silver" },
  { number: "26", name: "Pat Swilling", team: "New Orleans Saints", section: "Patch Autographs Prizm Silver /99" },
  { number: "27", name: "Victor Cruz", team: "New York Giants", section: "Patch Autographs Prizm Silver /99" },
  { number: "28", name: "Zack Baun", team: "Philadelphia Eagles", section: "Patch Autographs Prizm Silver /99" },
  { number: "29", name: "Nick Bosa", team: "San Francisco 49ers", section: "Patch Autographs Prizm Silver /99" },
  { number: "30", name: "Aaron Rodgers", team: "Pittsburgh Steelers", section: "Patch Autographs Prizm Silver /99" },
  { number: "1", name: "Patrick Mahomes II", team: "Kansas City Chiefs", section: "Patrick Mahomes Autograph Collection" },
  { number: "2", name: "Patrick Mahomes II", team: "Kansas City Chiefs", section: "Patrick Mahomes Autograph Collection" },
  { number: "1", name: "Shedeur Sanders", team: "Cleveland Browns", section: "Retro 2012 Signatures /149" },
  { number: "2", name: "Travis Hunter", team: "Jacksonville Jaguars", section: "Retro 2012 Signatures /149" },
  { number: "3", name: "Mason Graham", team: "Cleveland Browns", section: "Retro 2012 Signatures /149" },
  { number: "4", name: "Cam Skattebo", team: "New York Giants", section: "Retro 2012 Signatures /149" },
  { number: "5", name: "Jahdae Barron", team: "Denver Broncos", section: "Retro 2012 Signatures" },
  { number: "6", name: "Quinn Ewers", team: "Miami Dolphins", section: "Retro 2012 Signatures /149" },
  { number: "7", name: "Tai Felton", team: "Minnesota Vikings", section: "Retro 2012 Signatures" },
  { number: "8", name: "Bhayshul Tuten", team: "Jacksonville Jaguars", section: "Retro 2012 Signatures /149" },
  { number: "9", name: "Elic Ayomanor", team: "Tennessee Titans", section: "Retro 2012 Signatures /149" },
  { number: "10", name: "Ashton Jeanty", team: "Las Vegas Raiders", section: "Retro 2012 Signatures /149" },
  { number: "11", name: "Tyler Shough", team: "New Orleans Saints", section: "Retro 2012 Signatures /149" },
  { number: "12", name: "Kyle Williams", team: "New England Patriots", section: "Retro 2012 Signatures /149" },
  { number: "13", name: "Tre Harris", team: "Los Angeles Chargers", section: "Retro 2012 Signatures /149" },
  { number: "14", name: "Dillon Gabriel", team: "Cleveland Browns", section: "Retro 2012 Signatures /149" },
  { number: "15", name: "Jaylin Noel", team: "Houston Texans", section: "Retro 2012 Signatures /149" },
  { number: "16", name: "Savion Williams", team: "Green Bay Packers", section: "Retro 2012 Signatures /149" },
  { number: "17", name: "Jalen Royals", team: "Kansas City Chiefs", section: "Retro 2012 Signatures /149" },
  { number: "18", name: "Tyler Warren", team: "Indianapolis Colts", section: "Retro 2012 Signatures /149" },
  { number: "19", name: "Isaac TeSlaa", team: "Detroit Lions", section: "Retro 2012 Signatures" },
  { number: "20", name: "Pat Bryant", team: "Denver Broncos", section: "Retro 2012 Signatures /149" },
  { number: "21", name: "Colston Loveland", team: "Chicago Bears", section: "Retro 2012 Signatures /149" },
  { number: "22", name: "DJ Giddens", team: "Indianapolis Colts", section: "Retro 2012 Signatures" },
  { number: "23", name: "Ollie Gordon II", team: "Miami Dolphins", section: "Retro 2012 Signatures /149" },
  { number: "24", name: "Alfred Collins", team: "San Francisco 49ers", section: "Retro 2012 Signatures /149" },
  { number: "25", name: "Trevor Etienne", team: "Carolina Panthers", section: "Retro 2012 Signatures /149" },
  { number: "1", name: "Tetairoa McMillan", team: "Carolina Panthers", section: "Rookie Patch Autographs Prizm Silver /99" },
  { number: "2", name: "Trevor Etienne", team: "Carolina Panthers", section: "Rookie Patch Autographs Prizm Silver /99" },
  { number: "3", name: "Colston Loveland", team: "Chicago Bears", section: "Rookie Patch Autographs Prizm Silver /99" },
  { number: "4", name: "Shedeur Sanders", team: "Cleveland Browns", section: "Rookie Patch Autographs Prizm Silver /99" },
  { number: "5", name: "Dillon Gabriel", team: "Cleveland Browns", section: "Rookie Patch Autographs Prizm Silver /99" },
  { number: "6", name: "Mason Graham", team: "Cleveland Browns", section: "Rookie Patch Autographs Prizm Silver /99" },
  { number: "7", name: "Quinshon Judkins", team: "Cleveland Browns", section: "Rookie Patch Autographs Prizm Silver /99" },
  { number: "8", name: "Jaydon Blue", team: "Dallas Cowboys", section: "Rookie Patch Autographs Prizm Silver /99" },
  { number: "9", name: "RJ Harvey", team: "Denver Broncos", section: "Rookie Patch Autographs Prizm Silver /99" },
  { number: "10", name: "Pat Bryant", team: "Denver Broncos", section: "Rookie Patch Autographs Prizm Silver /99" },
  { number: "11", name: "Isaac TeSlaa", team: "Detroit Lions", section: "Rookie Patch Autographs Prizm Silver" },
  { number: "12", name: "Savion Williams", team: "Green Bay Packers", section: "Rookie Patch Autographs Prizm Silver /99" },
  { number: "13", name: "Matthew Golden", team: "Green Bay Packers", section: "Rookie Patch Autographs Prizm Silver /99" },
  { number: "14", name: "Jayden Higgins", team: "Houston Texans", section: "Rookie Patch Autographs Prizm Silver /99" },
  { number: "15", name: "Jaylin Noel", team: "Houston Texans", section: "Rookie Patch Autographs Prizm Silver /99" },
  { number: "16", name: "Riley Leonard", team: "Indianapolis Colts", section: "Rookie Patch Autographs Prizm Silver /99" },
  { number: "17", name: "Tyler Warren", team: "Indianapolis Colts", section: "Rookie Patch Autographs Prizm Silver /99" },
  { number: "18", name: "Travis Hunter", team: "Jacksonville Jaguars", section: "Rookie Patch Autographs Prizm Silver /99" },
  { number: "19", name: "Bhayshul Tuten", team: "Jacksonville Jaguars", section: "Rookie Patch Autographs Prizm Silver /99" },
  { number: "20", name: "Jalen Royals", team: "Kansas City Chiefs", section: "Rookie Patch Autographs Prizm Silver /99" },
  { number: "21", name: "Jack Bech", team: "Las Vegas Raiders", section: "Rookie Patch Autographs Prizm Silver /99" },
  { number: "22", name: "Ashton Jeanty", team: "Las Vegas Raiders", section: "Rookie Patch Autographs Prizm Silver /99" },
  { number: "23", name: "Omarion Hampton", team: "Los Angeles Chargers", section: "Rookie Patch Autographs Prizm Silver /99" },
  { number: "24", name: "Tre Harris", team: "Los Angeles Chargers", section: "Rookie Patch Autographs Prizm Silver /99" },
  { number: "25", name: "Terrance Ferguson", team: "Los Angeles Rams", section: "Rookie Patch Autographs Prizm Silver /99" },
  { number: "26", name: "Quinn Ewers", team: "Miami Dolphins", section: "Rookie Patch Autographs Prizm Silver /99" },
  { number: "27", name: "Tai Felton", team: "Minnesota Vikings", section: "Rookie Patch Autographs Prizm Silver" },
  { number: "28", name: "Kyle Williams", team: "New England Patriots", section: "Rookie Patch Autographs Prizm Silver /99" },
  { number: "29", name: "TreVeyon Henderson", team: "New England Patriots", section: "Rookie Patch Autographs Prizm Silver /99" },
  { number: "30", name: "Tyler Shough", team: "New Orleans Saints", section: "Rookie Patch Autographs Prizm Silver /99" },
  { number: "31", name: "Abdul Carter", team: "New York Giants", section: "Rookie Patch Autographs Prizm Silver" },
  { number: "32", name: "Cam Skattebo", team: "New York Giants", section: "Rookie Patch Autographs Prizm Silver /99" },
  { number: "33", name: "Mason Taylor", team: "New York Jets", section: "Rookie Patch Autographs Prizm Silver" },
  { number: "34", name: "Kyle McCord", team: "Philadelphia Eagles", section: "Rookie Patch Autographs Prizm Silver /99" },
  { number: "36", name: "Will Howard", team: "Pittsburgh Steelers", section: "Rookie Patch Autographs Prizm Silver /99" },
  { number: "37", name: "Mykel Williams", team: "San Francisco 49ers", section: "Rookie Patch Autographs Prizm Silver /99" },
  { number: "38", name: "Jalen Milroe", team: "Seattle Seahawks", section: "Rookie Patch Autographs Prizm Silver /99" },
  { number: "39", name: "Elijah Arroyo", team: "Seattle Seahawks", section: "Rookie Patch Autographs Prizm Silver" },
  { number: "40", name: "Tez Johnson", team: "Tampa Bay Buccaneers", section: "Rookie Patch Autographs Prizm Silver /99" },
  { number: "41", name: "Elic Ayomanor", team: "Tennessee Titans", section: "Rookie Patch Autographs Prizm Silver /99" },
  { number: "42", name: "Jaylin Lane", team: "Washington Commanders", section: "Rookie Patch Autographs Prizm Silver /99" },
  { number: "1", name: "Travis Hunter", team: "Jacksonville Jaguars", section: "Sensational Signatures /149" },
  { number: "2", name: "Shedeur Sanders", team: "Cleveland Browns", section: "Sensational Signatures /149" },
  { number: "3", name: "J.J. McCarthy", team: "Minnesota Vikings", section: "Sensational Signatures" },
  { number: "4", name: "Tez Johnson", team: "Tampa Bay Buccaneers", section: "Sensational Signatures /149" },
  { number: "5", name: "Xavier Restrepo", team: "Tennessee Titans", section: "Sensational Signatures /149" },
  { number: "6", name: "Jack Sawyer", team: "Pittsburgh Steelers", section: "Sensational Signatures /149" },
  { number: "7", name: "Kurtis Rourke", team: "San Francisco 49ers", section: "Sensational Signatures /149" },
  { number: "8", name: "Jordan James", team: "San Francisco 49ers", section: "Sensational Signatures /149" },
  { number: "9", name: "DJ Giddens", team: "Indianapolis Colts", section: "Sensational Signatures" },
  { number: "10", name: "Gunnar Helm", team: "Tennessee Titans", section: "Sensational Signatures" },
  { number: "11", name: "Xavier Legette", team: "Carolina Panthers", section: "Sensational Signatures /149" },
  { number: "12", name: "Will Campbell", team: "New England Patriots", section: "Sensational Signatures /149" },
  { number: "15", name: "Grey Zabel", team: "Seattle Seahawks", section: "Sensational Signatures /149" },
  { number: "16", name: "Kelvin Banks Jr.", team: "New Orleans Saints", section: "Sensational Signatures /149" },
  { number: "17", name: "Donovan Jackson", team: "Minnesota Vikings", section: "Sensational Signatures" },
  { number: "18", name: "Demetrius Knight Jr.", team: "Cincinnati Bengals", section: "Sensational Signatures /149" },
  { number: "19", name: "Quinn Ewers", team: "Miami Dolphins", section: "Sensational Signatures /149" },
  { number: "20", name: "Nic Scourton", team: "Carolina Panthers", section: "Sensational Signatures /149" },
  { number: "21", name: "Rome Odunze", team: "Chicago Bears", section: "Sensational Signatures /149" },
  { number: "22", name: "Aidan O'Connell", team: "Las Vegas Raiders", section: "Sensational Signatures /149" },
  { number: "23", name: "Chimere Dike", team: "Tennessee Titans", section: "Sensational Signatures /149" },
  { number: "24", name: "Zay Flowers", team: "Baltimore Ravens", section: "Sensational Signatures /149" },
  { number: "25", name: "Devaughn Vele", team: "Denver Broncos", section: "Sensational Signatures /149" },
  { number: "26", name: "Dalton Kincaid", team: "Buffalo Bills", section: "Sensational Signatures /149" },
  { number: "27", name: "Jeremiah Owusu-Koramoah", team: "Cleveland Browns", section: "Sensational Signatures /149" },
  { number: "29", name: "Ryan Kelly", team: "Minnesota Vikings", section: "Sensational Signatures /149" },
  { number: "30", name: "Joe Milton III", team: "Dallas Cowboys", section: "Sensational Signatures /149" },
  { number: "31", name: "Tyler Allgeier", team: "Atlanta Falcons", section: "Sensational Signatures /149" },
  { number: "32", name: "Kijana Carter", team: "Cincinnati Bengals", section: "Sensational Signatures /149" },
  { number: "33", name: "Terrel Bernard", team: "Buffalo Bills", section: "Sensational Signatures /149" },
  { number: "34", name: "Leonard Marshall", team: "New York Giants", section: "Sensational Signatures /149" },
  { number: "36", name: "Ricky Pearsall", team: "San Francisco 49ers", section: "Sensational Signatures /149" },
  { number: "37", name: "Chris Boswell", team: "Pittsburgh Steelers", section: "Sensational Signatures /149" },
  { number: "38", name: "Dallas Turner", team: "Minnesota Vikings", section: "Sensational Signatures /149" },
  { number: "39", name: "Laiatu Latu", team: "Indianapolis Colts", section: "Sensational Signatures /149" },
  { number: "40", name: "Landon Collins", team: "Washington Commanders", section: "Sensational Signatures /149" },
  { number: "41", name: "Levon Kirkland", team: "Pittsburgh Steelers", section: "Sensational Signatures" },
  { number: "42", name: "Creed Humphrey", team: "Kansas City Chiefs", section: "Sensational Signatures /149" },
  { number: "44", name: "Dylan Sampson", team: "Cleveland Browns", section: "Sensational Signatures /149" },
  { number: "45", name: "Nick Martin", team: "San Francisco 49ers", section: "Sensational Signatures /149" },
  { number: "46", name: "KeAndre Lambert-Smith", team: "Los Angeles Chargers", section: "Sensational Signatures /149" },
  { number: "47", name: "Odell Beckham Jr.", team: "New York Giants", section: "Sensational Signatures /149" },
  { number: "48", name: "Tremaine Edmunds", team: "Chicago Bears", section: "Sensational Signatures /149" },
  { number: "49", name: "Zaire Franklin", team: "Indianapolis Colts", section: "Sensational Signatures /149" },
  { number: "50", name: "Ben Coates", team: "New England Patriots", section: "Sensational Signatures" },
  { number: "1", name: "Shedeur Sanders", team: "Cleveland Browns", section: "Significant Signatures" },
  { number: "2", name: "Travis Hunter", team: "Jacksonville Jaguars", section: "Significant Signatures" },
  { number: "3", name: "Rome Odunze", team: "Chicago Bears", section: "Significant Signatures" },
  { number: "4", name: "Roman Wilson", team: "Pittsburgh Steelers", section: "Significant Signatures" },
  { number: "5", name: "Xavier Restrepo", team: "Tennessee Titans", section: "Significant Signatures" },
  { number: "7", name: "Nic Scourton", team: "Carolina Panthers", section: "Significant Signatures" },
  { number: "8", name: "Elic Ayomanor", team: "Tennessee Titans", section: "Significant Signatures" },
  { number: "9", name: "Jack Sawyer", team: "Pittsburgh Steelers", section: "Significant Signatures" },
  { number: "10", name: "Dylan Sampson", team: "Cleveland Browns", section: "Significant Signatures" },
  { number: "11", name: "Riley Leonard", team: "Indianapolis Colts", section: "Significant Signatures" },
  { number: "12", name: "Jordan James", team: "San Francisco 49ers", section: "Significant Signatures" },
  { number: "13", name: "Kurtis Rourke", team: "San Francisco 49ers", section: "Significant Signatures" },
  { number: "14", name: "Brady Cook", team: "New York Jets", section: "Significant Signatures" },
  { number: "15", name: "Darnell Washington", team: "Pittsburgh Steelers", section: "Significant Signatures" },
  { number: "16", name: "Johnny Wilson", team: "Philadelphia Eagles", section: "Significant Signatures" },
  { number: "17", name: "Patrick Ricard", team: "Baltimore Ravens", section: "Significant Signatures" },
  { number: "18", name: "Devin Leary", team: "Baltimore Ravens", section: "Significant Signatures" },
  { number: "20", name: "Ja'Tavion Sanders", team: "Carolina Panthers", section: "Significant Signatures" },
  { number: "21", name: "Antwaun Powell-Ryland", team: "Philadelphia Eagles", section: "Significant Signatures" },
  { number: "22", name: "Stetson Bennett IV", team: "Los Angeles Rams", section: "Significant Signatures" },
  { number: "23", name: "Jared Wiley", team: "Kansas City Chiefs", section: "Significant Signatures" },
  { number: "24", name: "Zach Evans", team: "New York Jets", section: "Significant Signatures" },
  { number: "25", name: "Jonah Savaiinaea", team: "Miami Dolphins", section: "Significant Signatures" },
  { number: "26", name: "Javion Cohen", team: "Cleveland Browns", section: "Significant Signatures" },
  { number: "27", name: "Marcus Mbow", team: "New York Giants", section: "Significant Signatures" },
  { number: "28", name: "Kalen King", team: "Green Bay Packers", section: "Significant Signatures" },
  { number: "29", name: "Javonte Williams", team: "Dallas Cowboys", section: "Significant Signatures" },
  { number: "30", name: "Sedrick Van Pran", team: "Buffalo Bills", section: "Significant Signatures" },
  { number: "31", name: "Barryn Sorrell", team: "Green Bay Packers", section: "Significant Signatures" },
  { number: "32", name: "Mello Dotson", team: "Las Vegas Raiders", section: "Significant Signatures" },
  { number: "33", name: "Ashton Gillotte", team: "Kansas City Chiefs", section: "Significant Signatures" },
  { number: "34", name: "Jermaine Johnson II", team: "New York Jets", section: "Significant Signatures" },
  { number: "35", name: "Kenny McIntosh", team: "Seattle Seahawks", section: "Significant Signatures" },
  { number: "36", name: "Cameron Latu", team: "Philadelphia Eagles", section: "Significant Signatures" },
  { number: "37", name: "Devonte Wyatt", team: "Green Bay Packers", section: "Significant Signatures" },
  { number: "38", name: "Damone Clark", team: "Dallas Cowboys", section: "Significant Signatures" },
  { number: "39", name: "Clayton Tune", team: "Arizona Cardinals", section: "Significant Signatures" },
  { number: "40", name: "Xavier Hutchinson", team: "Houston Texans", section: "Significant Signatures" },
  { number: "41", name: "Jordan Morgan", team: "Green Bay Packers", section: "Significant Signatures" },
  { number: "42", name: "Emmanuel Forbes", team: "Los Angeles Rams", section: "Significant Signatures" },
  { number: "43", name: "Christian Harris", team: "Houston Texans", section: "Significant Signatures" },
  { number: "44", name: "Connor Heyward", team: "Pittsburgh Steelers", section: "Significant Signatures" },
  { number: "45", name: "Spencer Rattler", team: "New Orleans Saints", section: "Significant Signatures" },
  { number: "46", name: "Felix Anudike-Uzomah", team: "Kansas City Chiefs", section: "Significant Signatures" },
  { number: "47", name: "Kayshon Boutte", team: "New England Patriots", section: "Significant Signatures" },
  { number: "48", name: "Logan Hall", team: "Tampa Bay Buccaneers", section: "Significant Signatures" },
  { number: "49", name: "Derick Hall", team: "Seattle Seahawks", section: "Significant Signatures" },
  { number: "50", name: "Jaden Hicks", team: "Kansas City Chiefs", section: "Significant Signatures" },
  { number: "51", name: "Cade Stover", team: "Houston Texans", section: "Significant Signatures" },
  { number: "52", name: "Roger Rosengarten", team: "Baltimore Ravens", section: "Significant Signatures" },
  { number: "53", name: "Andre Cisco", team: "New York Jets", section: "Significant Signatures" },
  { number: "54", name: "Isaac Guerendo", team: "San Francisco 49ers", section: "Significant Signatures" },
  { number: "55", name: "Leo Chenal", team: "Kansas City Chiefs", section: "Significant Signatures" },
  { number: "56", name: "YaYa Diaby", team: "Tampa Bay Buccaneers", section: "Significant Signatures" },
  { number: "57", name: "Nolan Smith", team: "Philadelphia Eagles", section: "Significant Signatures" },
  { number: "58", name: "Ray Davis", team: "Buffalo Bills", section: "Significant Signatures" },
  { number: "59", name: "Clark Phillips III", team: "Atlanta Falcons", section: "Significant Signatures" },
  { number: "60", name: "Cooper Beebe", team: "Dallas Cowboys", section: "Significant Signatures" },
  { number: "61", name: "Will Dissly", team: "Los Angeles Chargers", section: "Significant Signatures" },
  { number: "62", name: "Ja'Lynn Polk", team: "New England Patriots", section: "Significant Signatures" },
  { number: "63", name: "Will Shipley", team: "Philadelphia Eagles", section: "Significant Signatures" },
  { number: "64", name: "Jordan Jefferson", team: "Jacksonville Jaguars", section: "Significant Signatures" },
  { number: "65", name: "Dan Dierdorf", team: "St. Louis Cardinals", section: "Significant Signatures" },
  { number: "66", name: "Eric Dorsey", team: "New York Giants", section: "Significant Signatures" },
  { number: "67", name: "Hassan Haskins", team: "Los Angeles Chargers", section: "Significant Signatures" },
  { number: "68", name: "Jim Burt", team: "New York Giants", section: "Significant Signatures" },
  { number: "69", name: "Juice Scruggs", team: "Houston Texans", section: "Significant Signatures" },
  { number: "70", name: "Jonathan Mingo", team: "Dallas Cowboys", section: "Significant Signatures" },
  { number: "71", name: "Peter Skoronski", team: "Tennessee Titans", section: "Significant Signatures" },
  { number: "72", name: "Myles Murphy", team: "Cincinnati Bengals", section: "Significant Signatures" },
  { number: "73", name: "Cordale Flott", team: "New York Giants", section: "Significant Signatures" },
  { number: "74", name: "Upton Stout", team: "San Francisco 49ers", section: "Significant Signatures" },
  { number: "75", name: "Cam Jackson", team: "Carolina Panthers", section: "Significant Signatures" },
  { number: "76", name: "Jonas Sanker", team: "New Orleans Saints", section: "Significant Signatures" },
  { number: "77", name: "Graham Mertz", team: "Houston Texans", section: "Significant Signatures" },
  { number: "78", name: "Zy Alexander", team: "Seattle Seahawks", section: "Significant Signatures" },
  { number: "80", name: "Danny Stutsman", team: "New Orleans Saints", section: "Significant Signatures" },
  { number: "81", name: "Ajani Cornelius", team: "Dallas Cowboys", section: "Significant Signatures" },
  { number: "82", name: "Charles Grant", team: "Las Vegas Raiders", section: "Significant Signatures" },
  { number: "83", name: "Phil Mafah", team: "Dallas Cowboys", section: "Significant Signatures" },
  { number: "84", name: "Tahj Brooks", team: "Cincinnati Bengals", section: "Significant Signatures" },
  { number: "85", name: "David Walker", team: "Tampa Bay Buccaneers", section: "Significant Signatures" },
  { number: "86", name: "Lathan Ransom", team: "Carolina Panthers", section: "Significant Signatures" },
  { number: "87", name: "Jimmy Horn Jr.", team: "Carolina Panthers", section: "Significant Signatures" },
  { number: "88", name: "Sai'vion Jones", team: "Denver Broncos", section: "Significant Signatures" },
  { number: "89", name: "Tyler Batty", team: "Minnesota Vikings", section: "Significant Signatures" },
  { number: "90", name: "Chris Paul Jr.", team: "Los Angeles Rams", section: "Significant Signatures" },
  { number: "91", name: "Jamin Davis", team: "New York Jets", section: "Significant Signatures" },
  { number: "92", name: "Jake Camarda", team: "Tampa Bay Buccaneers", section: "Significant Signatures" },
  { number: "93", name: "Donte' Stallworth", team: "New Orleans Saints", section: "Significant Signatures" },
  { number: "94", name: "Grover Stewart", team: "Indianapolis Colts", section: "Significant Signatures" },
  { number: "95", name: "Steve Avila", team: "Los Angeles Rams", section: "Significant Signatures" },
  { number: "96", name: "Brevin Jordan", team: "Houston Texans", section: "Significant Signatures" },
  { number: "97", name: "Braiden McGregor", team: "New York Jets", section: "Significant Signatures" },
  { number: "98", name: "Rocky Bleier", team: "Pittsburgh Steelers", section: "Significant Signatures" },
  { number: "99", name: "Lynn Dickey", team: "Green Bay Packers", section: "Significant Signatures" },
  { number: "100", name: "Zamir White", team: "Las Vegas Raiders", section: "Significant Signatures" },
  { number: "1", name: "Joe Montana/Brock Purdy/Steve Young", team: "San Francisco 49ers", section: "Triple Patch Autographs /99" },
  { number: "3", name: "Garrett Wilson/Chris Olave/Terry McLaurin", team: "New York Jets/New Orleans Saints/Washington Commanders", section: "Triple Patch Autographs" },
  { number: "4", name: "Michael Irvin/CeeDee Lamb/Drew Pearson", team: "Dallas Cowboys", section: "Triple Patch Autographs /99" },
  { number: "5", name: "Mason Taylor/Harold Fannin Jr./Terrance Ferguson", team: "New York Jets/Cleveland Browns/Los Angeles Rams", section: "Triple Patch Autographs" },
  { number: "6", name: "Tua Tagovailoa/Jonnu Smith/Tyreek Hill", team: "Miami Dolphins", section: "Triple Patch Autographs" },
  { number: "7", name: "Pat Bryant/Jack Bech/Tre Harris", team: "Denver Broncos/Las Vegas Raiders/Los Angeles Chargers", section: "Triple Patch Autographs /99" },
  { number: "8", name: "Fred Warner/Roquan Smith/Zack Baun", team: "San Francisco 49ers/Baltimore Ravens/Philadelphia Eagles", section: "Triple Patch Autographs /99" },
];