export type InsertEntry = {
  number: string;
  name: string;
  team?: string;
  section:
    | "Anniversary Rookies"
    | "Celebration"
    | "Emerged"
    | "First Ballot"
    | "Hot Rookies"
    | "Intergalactic"
    | "League Leaders"
    | "Men of Canton"
    | "NFL Draft"
    | "Sack Attack"
    | "Showtime"
    | "Step Ahead"
    | "The Franchise"
    | "Throwbacks"
    | "Top 100";
};

export const SCORE_2025_INSERTS: InsertEntry[] = [
  // Anniversary Rookies
  { number: "1", name: "Ashton Jeanty", team: "Las Vegas Raiders", section: "Anniversary Rookies" },
  { number: "2", name: "Shedeur Sanders", team: "Cleveland Browns", section: "Anniversary Rookies" },
  { number: "3", name: "Tetairoa McMillan", team: "Carolina Panthers", section: "Anniversary Rookies" },
  { number: "4", name: "Cam Ward", team: "Tennessee Titans", section: "Anniversary Rookies" },
  { number: "5", name: "Travis Hunter", team: "Jacksonville Jaguars", section: "Anniversary Rookies" },
  { number: "6", name: "Luther Burden III", team: "Chicago Bears", section: "Anniversary Rookies" },
  { number: "7", name: "Jalen Milroe", team: "Seattle Seahawks", section: "Anniversary Rookies" },
  { number: "8", name: "Emeka Egbuka", team: "Tampa Bay Buccaneers", section: "Anniversary Rookies" },
  { number: "9", name: "Jaxson Dart", team: "New York Giants", section: "Anniversary Rookies" },
  { number: "10", name: "Mason Graham", team: "Cleveland Browns", section: "Anniversary Rookies" },

  // Celebration
  { number: "1", name: "Mike Evans", team: "Tampa Bay Buccaneers", section: "Celebration" },
  { number: "2", name: "Saquon Barkley", team: "Philadelphia Eagles", section: "Celebration" },
  { number: "3", name: "Jayden Daniels", team: "Washington Commanders", section: "Celebration" },
  { number: "4", name: "Sam Darnold", team: "Minnesota Vikings", section: "Celebration" },
  { number: "5", name: "Ja'Marr Chase", team: "Cincinnati Bengals", section: "Celebration" },
  { number: "6", name: "Michael Penix Jr.", team: "Atlanta Falcons", section: "Celebration" },
  { number: "7", name: "Amon-Ra St. Brown", team: "Detroit Lions", section: "Celebration" },
  { number: "8", name: "Andrew Van Ginkel", team: "Minnesota Vikings", section: "Celebration" },
  { number: "9", name: "Drake Maye", team: "New England Patriots", section: "Celebration" },
  { number: "10", name: "Nico Collins", team: "Houston Texans", section: "Celebration" },
  { number: "11", name: "Davante Adams", team: "New York Jets", section: "Celebration" },
  { number: "12", name: "Anthony Richardson", team: "Indianapolis Colts", section: "Celebration" },
  { number: "13", name: "Bo Nix", team: "Denver Broncos", section: "Celebration" },
  { number: "14", name: "T.J. Watt", team: "Pittsburgh Steelers", section: "Celebration" },
  { number: "15", name: "Lamar Jackson", team: "Baltimore Ravens", section: "Celebration" },
  { number: "16", name: "James Cook", team: "Buffalo Bills", section: "Celebration" },
  { number: "17", name: "Trey McBride", team: "Arizona Cardinals", section: "Celebration" },
  { number: "18", name: "Puka Nacua", team: "Los Angeles Rams", section: "Celebration" },
  { number: "19", name: "Josh Allen", team: "Buffalo Bills", section: "Celebration" },
  { number: "20", name: "Brock Bowers", team: "Las Vegas Raiders", section: "Celebration" },
  { number: "21", name: "Ladd McConkey", team: "Los Angeles Chargers", section: "Celebration" },
  { number: "22", name: "Malik Nabers", team: "New York Giants", section: "Celebration" },
  { number: "23", name: "Jaxon Smith-Njigba", team: "Seattle Seahawks", section: "Celebration" },
  { number: "24", name: "Xavier Worthy", team: "Kansas City Chiefs", section: "Celebration" },
  { number: "25", name: "Travis Kelce", team: "Kansas City Chiefs", section: "Celebration" },

  // Emerged
  { number: "1", name: "Ashton Jeanty", team: "Las Vegas Raiders", section: "Emerged" },
  { number: "2", name: "Cam Ward", team: "Tennessee Titans", section: "Emerged" },
  { number: "3", name: "Jayden Daniels", team: "Washington Commanders", section: "Emerged" },
  { number: "4", name: "Brock Bowers", team: "Las Vegas Raiders", section: "Emerged" },
  { number: "5", name: "Bo Nix", team: "Denver Broncos", section: "Emerged" },
  { number: "6", name: "Shedeur Sanders", team: "Cleveland Browns", section: "Emerged" },
  { number: "7", name: "Michael Penix Jr.", team: "Atlanta Falcons", section: "Emerged" },
  { number: "8", name: "Tetairoa McMillan", team: "Carolina Panthers", section: "Emerged" },
  { number: "9", name: "Malik Nabers", team: "New York Giants", section: "Emerged" },
  { number: "10", name: "Drake Maye", team: "New England Patriots", section: "Emerged" },
  { number: "11", name: "Caleb Williams", team: "Chicago Bears", section: "Emerged" },
  { number: "12", name: "Luther Burden III", team: "Chicago Bears", section: "Emerged" },
  { number: "13", name: "Emeka Egbuka", team: "Tampa Bay Buccaneers", section: "Emerged" },

  // First Ballot
  { number: "1", name: "Steve Young", team: "San Francisco 49ers", section: "First Ballot" },
  { number: "2", name: "Earl Campbell", team: "Houston Oilers", section: "First Ballot" },
  { number: "3", name: "Darrell Green", team: "Washington Redskins", section: "First Ballot" },
  { number: "4", name: "Eric Dickerson", team: "Los Angeles Rams", section: "First Ballot" },
  { number: "5", name: "Marshall Faulk", team: "St. Louis Rams", section: "First Ballot" },
  { number: "6", name: "Joe Thomas", team: "Cleveland Browns", section: "First Ballot" },
  { number: "7", name: "Ken Houston", team: "Houston Oilers", section: "First Ballot" },
  { number: "8", name: "Barry Sanders", team: "Detroit Lions", section: "First Ballot" },
  { number: "9", name: "Ray Lewis", team: "Baltimore Ravens", section: "First Ballot" },
  { number: "10", name: "Terry Bradshaw", team: "Pittsburgh Steelers", section: "First Ballot" },

  // Hot Rookies
  { number: "1", name: "Cam Ward", team: "Tennessee Titans", section: "Hot Rookies" },
  { number: "2", name: "Travis Hunter", team: "Jacksonville Jaguars", section: "Hot Rookies" },
  { number: "3", name: "Ashton Jeanty", team: "Las Vegas Raiders", section: "Hot Rookies" },
  { number: "4", name: "Luther Burden III", team: "Chicago Bears", section: "Hot Rookies" },
  { number: "5", name: "Shedeur Sanders", team: "Cleveland Browns", section: "Hot Rookies" },
  { number: "6", name: "Jaxson Dart", team: "New York Giants", section: "Hot Rookies" },
  { number: "7", name: "Tetairoa McMillan", team: "Carolina Panthers", section: "Hot Rookies" },
  { number: "8", name: "Quinn Ewers", team: "Miami Dolphins", section: "Hot Rookies" },
  { number: "9", name: "Jalen Milroe", team: "Seattle Seahawks", section: "Hot Rookies" },
  { number: "10", name: "Emeka Egbuka", team: "Tampa Bay Buccaneers", section: "Hot Rookies" },
  { number: "11", name: "Tre Harris", team: "Los Angeles Chargers", section: "Hot Rookies" },
  { number: "12", name: "TreVeyon Henderson", team: "New England Patriots", section: "Hot Rookies" },
  { number: "13", name: "Isaiah Bond", team: "Texas Longhorns", section: "Hot Rookies" },
  { number: "14", name: "Omarion Hampton", team: "Los Angeles Chargers", section: "Hot Rookies" },
  { number: "15", name: "Tyler Warren", team: "Indianapolis Colts", section: "Hot Rookies" },

  // Intergalactic
  { number: "1", name: "Shedeur Sanders", team: "Cleveland Browns", section: "Intergalactic" },
  { number: "2", name: "Josh Allen", team: "Buffalo Bills", section: "Intergalactic" },
  { number: "3", name: "Luther Burden III", team: "Chicago Bears", section: "Intergalactic" },
  { number: "4", name: "Joe Burrow", team: "Cincinnati Bengals", section: "Intergalactic" },
  { number: "5", name: "Saquon Barkley", team: "Philadelphia Eagles", section: "Intergalactic" },
  { number: "6", name: "Ashton Jeanty", team: "Las Vegas Raiders", section: "Intergalactic" },
  { number: "7", name: "Justin Jefferson", team: "Minnesota Vikings", section: "Intergalactic" },
  { number: "8", name: "Tetairoa McMillan", team: "Carolina Panthers", section: "Intergalactic" },
  { number: "9", name: "Cam Ward", team: "Tennessee Titans", section: "Intergalactic" },
  { number: "10", name: "Ja'Marr Chase", team: "Cincinnati Bengals", section: "Intergalactic" },

  // League Leaders
  { number: "1", name: "Joe Burrow", team: "Cincinnati Bengals", section: "League Leaders" },
  { number: "2", name: "Ja'Marr Chase", team: "Cincinnati Bengals", section: "League Leaders" },
  { number: "3", name: "Saquon Barkley", team: "Philadelphia Eagles", section: "League Leaders" },
  { number: "4", name: "Trey Hendrickson", team: "Cincinnati Bengals", section: "League Leaders" },
  { number: "5", name: "Jahmyr Gibbs", team: "Detroit Lions", section: "League Leaders" },
  { number: "6", name: "Chris Boswell", team: "Pittsburgh Steelers", section: "League Leaders" },
  { number: "7", name: "Kerby Joseph", team: "Detroit Lions", section: "League Leaders" },
  { number: "8", name: "Zaire Franklin", team: "Indianapolis Colts", section: "League Leaders" },
  { number: "9", name: "Nick Westbrook-Ikhine", team: "Tennessee Titans", section: "League Leaders" },
  { number: "10", name: "Kamren Kinchens", team: "Los Angeles Rams", section: "League Leaders" },
  { number: "11", name: "Bo Nix", team: "Denver Broncos", section: "League Leaders" },
  { number: "12", name: "Brock Bowers", team: "Las Vegas Raiders", section: "League Leaders" },
  { number: "13", name: "Brian Thomas Jr.", team: "Jacksonville Jaguars", section: "League Leaders" },
  { number: "14", name: "Bucky Irving", team: "Tampa Bay Buccaneers", section: "League Leaders" },
  { number: "15", name: "Brandon Aubrey", team: "Dallas Cowboys", section: "League Leaders" },

  // Men of Canton
  { number: "1", name: "Terry Bradshaw", team: "Pittsburgh Steelers", section: "Men of Canton" },
  { number: "2", name: "Emmitt Smith", team: "Dallas Cowboys", section: "Men of Canton" },
  { number: "3", name: "Devin Hester", team: "Chicago Bears", section: "Men of Canton" },
  { number: "4", name: "Randy Gradishar", team: "Denver Broncos", section: "Men of Canton" },
  { number: "5", name: "Dwight Freeney", team: "Indianapolis Colts", section: "Men of Canton" },
  { number: "6", name: "Ed Reed", team: "Baltimore Ravens", section: "Men of Canton" },
  { number: "7", name: "Deion Sanders", team: "Atlanta Falcons", section: "Men of Canton" },
  { number: "8", name: "Terrell Owens", team: "San Francisco 49ers", section: "Men of Canton" },
  { number: "9", name: "Ozzie Newsome", team: "Cleveland Browns", section: "Men of Canton" },
  { number: "10", name: "Brian Dawkins", team: "Philadelphia Eagles", section: "Men of Canton" },
  { number: "11", name: "Isaac Bruce", team: "St. Louis Rams", section: "Men of Canton" },
  { number: "12", name: "Dan Marino", team: "Miami Dolphins", section: "Men of Canton" },
  { number: "13", name: "Jimmy Johnson", team: "Dallas Cowboys", section: "Men of Canton" },
  { number: "14", name: "Richard Seymour", team: "New England Patriots", section: "Men of Canton" },
  { number: "15", name: "Joe Namath", team: "New York Jets", section: "Men of Canton" },
  { number: "16", name: "Kellen Winslow", team: "San Diego Chargers", section: "Men of Canton" },
  { number: "17", name: "Ronde Barber", team: "Tampa Bay Buccaneers", section: "Men of Canton" },
  { number: "18", name: "Earl Campbell", team: "Houston Oilers", section: "Men of Canton" },
  { number: "19", name: "Art Monk", team: "Washington Redskins", section: "Men of Canton" },
  { number: "20", name: "Tim Brown", team: "Oakland Raiders", section: "Men of Canton" },

  // NFL Draft
  { number: "1", name: "Tetairoa McMillan", team: "Carolina Panthers", section: "NFL Draft" },
  { number: "2", name: "Shedeur Sanders", team: "Cleveland Browns", section: "NFL Draft" },
  { number: "3", name: "Cam Ward", team: "Tennessee Titans", section: "NFL Draft" },
  { number: "4", name: "Ashton Jeanty", team: "Las Vegas Raiders", section: "NFL Draft" },
  { number: "5", name: "Colston Loveland", team: "Chicago Bears", section: "NFL Draft" },
  { number: "6", name: "Quinshon Judkins", team: "Cleveland Browns", section: "NFL Draft" },
  { number: "7", name: "Luther Burden III", team: "Chicago Bears", section: "NFL Draft" },
  { number: "8", name: "Abdul Carter", team: "New York Giants", section: "NFL Draft" },
  { number: "9", name: "Tre Harris", team: "Los Angeles Chargers", section: "NFL Draft" },
  { number: "10", name: "Jalen Milroe", team: "Seattle Seahawks", section: "NFL Draft" },
  { number: "11", name: "Travis Hunter", team: "Jacksonville Jaguars", section: "NFL Draft" },
  { number: "12", name: "Tyler Warren", team: "Indianapolis Colts", section: "NFL Draft" },
  { number: "13", name: "Emeka Egbuka", team: "Tampa Bay Buccaneers", section: "NFL Draft" },
  { number: "14", name: "Kaleb Johnson", team: "Pittsburgh Steelers", section: "NFL Draft" },
  { number: "15", name: "Omarion Hampton", team: "Los Angeles Chargers", section: "NFL Draft" },
  { number: "16", name: "Cam Skattebo", team: "New York Giants", section: "NFL Draft" },
  { number: "17", name: "Dillon Gabriel", team: "Cleveland Browns", section: "NFL Draft" },
  { number: "18", name: "Jaxson Dart", team: "New York Giants", section: "NFL Draft" },
  { number: "19", name: "Mason Graham", team: "Cleveland Browns", section: "NFL Draft" },
  { number: "20", name: "Riley Leonard", team: "Indianapolis Colts", section: "NFL Draft" },

  // Sack Attack
  { number: "1", name: "Nik Bonitto", team: "Denver Broncos", section: "Sack Attack" },
  { number: "2", name: "Kyle Van Noy", team: "Baltimore Ravens", section: "Sack Attack" },
  { number: "3", name: "Jonathan Greenard", team: "Minnesota Vikings", section: "Sack Attack" },
  { number: "4", name: "Myles Garrett", team: "Cleveland Browns", section: "Sack Attack" },
  { number: "5", name: "Trey Hendrickson", team: "Cincinnati Bengals", section: "Sack Attack" },
  { number: "6", name: "Danielle Hunter", team: "Houston Texans", section: "Sack Attack" },
  { number: "7", name: "Andrew Van Ginkel", team: "Minnesota Vikings", section: "Sack Attack" },
  { number: "8", name: "T.J. Watt", team: "Pittsburgh Steelers", section: "Sack Attack" },
  { number: "9", name: "Will Anderson Jr.", team: "Houston Texans", section: "Sack Attack" },
  { number: "10", name: "Dexter Lawrence", team: "New York Giants", section: "Sack Attack" },
  { number: "11", name: "Leonard Williams", team: "Seattle Seahawks", section: "Sack Attack" },
  { number: "12", name: "Nick Bosa", team: "San Francisco 49ers", section: "Sack Attack" },
  { number: "13", name: "Brian Burns", team: "New York Giants", section: "Sack Attack" },
  { number: "14", name: "Dante Fowler Jr.", team: "Washington Commanders", section: "Sack Attack" },
  { number: "15", name: "Travon Walker", team: "Jacksonville Jaguars", section: "Sack Attack" },

  // Showtime
  { number: "1", name: "Jayden Daniels", team: "Washington Commanders", section: "Showtime" },
  { number: "2", name: "Saquon Barkley", team: "Philadelphia Eagles", section: "Showtime" },
  { number: "3", name: "Caleb Williams", team: "Chicago Bears", section: "Showtime" },
  { number: "4", name: "Drake Maye", team: "New England Patriots", section: "Showtime" },
  { number: "5", name: "Ja'Marr Chase", team: "Cincinnati Bengals", section: "Showtime" },
  { number: "6", name: "Jahmyr Gibbs", team: "Detroit Lions", section: "Showtime" },
  { number: "7", name: "T.J. Watt", team: "Pittsburgh Steelers", section: "Showtime" },
  { number: "8", name: "Nik Bonitto", team: "Denver Broncos", section: "Showtime" },
  { number: "9", name: "Brock Bowers", team: "Las Vegas Raiders", section: "Showtime" },
  { number: "10", name: "Malik Nabers", team: "New York Giants", section: "Showtime" },
  { number: "11", name: "Jaxon Smith-Njigba", team: "Seattle Seahawks", section: "Showtime" },
  { number: "12", name: "Lamar Jackson", team: "Baltimore Ravens", section: "Showtime" },
  { number: "13", name: "Josh Allen", team: "Buffalo Bills", section: "Showtime" },
  { number: "14", name: "Michael Penix Jr.", team: "Atlanta Falcons", section: "Showtime" },
  { number: "15", name: "Brian Thomas Jr.", team: "Jacksonville Jaguars", section: "Showtime" },
  { number: "16", name: "Nico Collins", team: "Houston Texans", section: "Showtime" },
  { number: "17", name: "Travis Kelce", team: "Kansas City Chiefs", section: "Showtime" },
  { number: "18", name: "Joe Burrow", team: "Cincinnati Bengals", section: "Showtime" },
  { number: "19", name: "Nick Bosa", team: "San Francisco 49ers", section: "Showtime" },
  { number: "20", name: "Puka Nacua", team: "Los Angeles Rams", section: "Showtime" },

  // Step Ahead
  { number: "1", name: "Jayden Daniels", team: "Washington Commanders", section: "Step Ahead" },
  { number: "2", name: "Cam Ward", team: "Tennessee Titans", section: "Step Ahead" },
  { number: "3", name: "Jahmyr Gibbs", team: "Detroit Lions", section: "Step Ahead" },
  { number: "4", name: "Ashton Jeanty", team: "Las Vegas Raiders", section: "Step Ahead" },
  { number: "5", name: "Joe Burrow", team: "Cincinnati Bengals", section: "Step Ahead" },
  { number: "6", name: "Shedeur Sanders", team: "Cleveland Browns", section: "Step Ahead" },
  { number: "7", name: "Josh Allen", team: "Buffalo Bills", section: "Step Ahead" },
  { number: "8", name: "Luther Burden III", team: "Chicago Bears", section: "Step Ahead" },
  { number: "9", name: "Malik Nabers", team: "New York Giants", section: "Step Ahead" },
  { number: "10", name: "Lamar Jackson", team: "Baltimore Ravens", section: "Step Ahead" },
  { number: "11", name: "Brock Bowers", team: "Las Vegas Raiders", section: "Step Ahead" },
  { number: "12", name: "Tyler Warren", team: "Indianapolis Colts", section: "Step Ahead" },
  { number: "13", name: "Micah Parsons", team: "Dallas Cowboys", section: "Step Ahead" },
  { number: "14", name: "Abdul Carter", team: "New York Giants", section: "Step Ahead" },
  { number: "15", name: "Ja'Marr Chase", team: "Cincinnati Bengals", section: "Step Ahead" },
  { number: "16", name: "Tetairoa McMillan", team: "Carolina Panthers", section: "Step Ahead" },
  { number: "17", name: "Derrick Henry", team: "Baltimore Ravens", section: "Step Ahead" },
  { number: "18", name: "Justin Jefferson", team: "Minnesota Vikings", section: "Step Ahead" },
  { number: "19", name: "Jaxson Dart", team: "New York Giants", section: "Step Ahead" },
  { number: "20", name: "Bo Nix", team: "Denver Broncos", section: "Step Ahead" },

  // The Franchise
  { number: "1", name: "Marvin Harrison Jr.", team: "Arizona Cardinals", section: "The Franchise" },
  { number: "2", name: "Michael Penix Jr.", team: "Atlanta Falcons", section: "The Franchise" },
  { number: "3", name: "Derrick Henry", team: "Baltimore Ravens", section: "The Franchise" },
  { number: "4", name: "Josh Allen", team: "Buffalo Bills", section: "The Franchise" },
  { number: "5", name: "Bryce Young", team: "Carolina Panthers", section: "The Franchise" },
  { number: "6", name: "Caleb Williams", team: "Chicago Bears", section: "The Franchise" },
  { number: "7", name: "Joe Burrow", team: "Cincinnati Bengals", section: "The Franchise" },
  { number: "9", name: "CeeDee Lamb", team: "Dallas Cowboys", section: "The Franchise" },
  { number: "10", name: "Bo Nix", team: "Denver Broncos", section: "The Franchise" },
  { number: "11", name: "Amon-Ra St. Brown", team: "Detroit Lions", section: "The Franchise" },
  { number: "12", name: "Josh Jacobs", team: "Green Bay Packers", section: "The Franchise" },
  { number: "13", name: "Nico Collins", team: "Houston Texans", section: "The Franchise" },
  { number: "14", name: "Jonathan Taylor", team: "Indianapolis Colts", section: "The Franchise" },
  { number: "15", name: "Josh Hines-Allen", team: "Jacksonville Jaguars", section: "The Franchise" },
  { number: "16", name: "Patrick Mahomes II", team: "Kansas City Chiefs", section: "The Franchise" },
  { number: "17", name: "Brock Bowers", team: "Las Vegas Raiders", section: "The Franchise" },
  { number: "18", name: "Justin Herbert", team: "Los Angeles Chargers", section: "The Franchise" },
  { number: "19", name: "Matthew Stafford", team: "Los Angeles Rams", section: "The Franchise" },
  { number: "20", name: "De'Von Achane", team: "Miami Dolphins", section: "The Franchise" },
  { number: "21", name: "Harrison Smith", team: "Minnesota Vikings", section: "The Franchise" },
  { number: "22", name: "Drake Maye", team: "New England Patriots", section: "The Franchise" },
  { number: "23", name: "Alvin Kamara", team: "New Orleans Saints", section: "The Franchise" },
  { number: "24", name: "Malik Nabers", team: "New York Giants", section: "The Franchise" },
  { number: "25", name: "Garrett Wilson", team: "New York Jets", section: "The Franchise" },
  { number: "26", name: "Jalen Carter", team: "Philadelphia Eagles", section: "The Franchise" },
  { number: "27", name: "T.J. Watt", team: "Pittsburgh Steelers", section: "The Franchise" },
  { number: "28", name: "Christian McCaffrey", team: "San Francisco 49ers", section: "The Franchise" },
  { number: "29", name: "Jaxon Smith-Njigba", team: "Seattle Seahawks", section: "The Franchise" },
  { number: "30", name: "Mike Evans", team: "Tampa Bay Buccaneers", section: "The Franchise" },
  { number: "31", name: "Jeffery Simmons", team: "Tennessee Titans", section: "The Franchise" },
  { number: "32", name: "Jayden Daniels", team: "Washington Commanders", section: "The Franchise" },

  // Throwbacks
  { number: "1", name: "Saquon Barkley", team: "Philadelphia Eagles", section: "Throwbacks" },
  { number: "2", name: "Baker Mayfield", team: "Tampa Bay Buccaneers", section: "Throwbacks" },
  { number: "3", name: "Drake Maye", team: "New England Patriots", section: "Throwbacks" },
  { number: "4", name: "Caleb Williams", team: "Chicago Bears", section: "Throwbacks" },
  { number: "5", name: "Jaxon Smith-Njigba", team: "Seattle Seahawks", section: "Throwbacks" },
  { number: "6", name: "Bo Nix", team: "Denver Broncos", section: "Throwbacks" },
  { number: "7", name: "Josh Jacobs", team: "Green Bay Packers", section: "Throwbacks" },
  { number: "8", name: "Brian Thomas Jr.", team: "Jacksonville Jaguars", section: "Throwbacks" },
  { number: "9", name: "De'Von Achane", team: "Miami Dolphins", section: "Throwbacks" },
  { number: "10", name: "Aaron Rodgers", team: "New York Jets", section: "Throwbacks" },
  { number: "11", name: "Malik Nabers", team: "New York Giants", section: "Throwbacks" },
  { number: "12", name: "Calvin Ridley", team: "Tennessee Titans", section: "Throwbacks" },
  { number: "13", name: "Michael Penix Jr.", team: "Atlanta Falcons", section: "Throwbacks" },
  { number: "14", name: "Tony Pollard", team: "Tennessee Titans", section: "Throwbacks" },
  { number: "15", name: "DK Metcalf", team: "Seattle Seahawks", section: "Throwbacks" },
  { number: "16", name: "Dexter Lawrence", team: "New York Giants", section: "Throwbacks" },
  { number: "17", name: "Cooper DeJean", team: "Philadelphia Eagles", section: "Throwbacks" },
  { number: "18", name: "Tyreek Hill", team: "Miami Dolphins", section: "Throwbacks" },
  { number: "19", name: "Cade Otton", team: "Tampa Bay Buccaneers", section: "Throwbacks" },
  { number: "20", name: "DJ Moore", team: "Chicago Bears", section: "Throwbacks" },
  { number: "21", name: "Garrett Wilson", team: "New York Jets", section: "Throwbacks" },
  { number: "22", name: "Tua Tagovailoa", team: "Miami Dolphins", section: "Throwbacks" },
  { number: "23", name: "Bucky Irving", team: "Tampa Bay Buccaneers", section: "Throwbacks" },
  { number: "24", name: "Jayden Reed", team: "Green Bay Packers", section: "Throwbacks" },
  { number: "25", name: "CeeDee Lamb", team: "Dallas Cowboys", section: "Throwbacks" },

  // Top 100
  { number: "1", name: "Tyreek Hill", team: "Miami Dolphins", section: "Top 100" },
  { number: "2", name: "Lamar Jackson", team: "Baltimore Ravens", section: "Top 100" },
  { number: "3", name: "Christian McCaffrey", team: "San Francisco 49ers", section: "Top 100" },
  { number: "4", name: "Patrick Mahomes II", team: "Kansas City Chiefs", section: "Top 100" },
  { number: "5", name: "Myles Garrett", team: "Cleveland Browns", section: "Top 100" },
  { number: "6", name: "Chris Jones", team: "Kansas City Chiefs", section: "Top 100" },
  { number: "7", name: "Trent Williams", team: "San Francisco 49ers", section: "Top 100" },
  { number: "8", name: "T.J. Watt", team: "Pittsburgh Steelers", section: "Top 100" },
  { number: "9", name: "Travis Kelce", team: "Kansas City Chiefs", section: "Top 100" },
  { number: "10", name: "Maxx Crosby", team: "Las Vegas Raiders", section: "Top 100" },
  { number: "11", name: "Fred Warner", team: "San Francisco 49ers", section: "Top 100" },
  { number: "12", name: "Josh Allen", team: "Buffalo Bills", section: "Top 100" },
  { number: "13", name: "CeeDee Lamb", team: "Dallas Cowboys", section: "Top 100" },
  { number: "14", name: "George Kittle", team: "San Francisco 49ers", section: "Top 100" },
  { number: "15", name: "Jalen Hurts", team: "Philadelphia Eagles", section: "Top 100" },
  { number: "16", name: "Dak Prescott", team: "Dallas Cowboys", section: "Top 100" },
  { number: "17", name: "Micah Parsons", team: "Dallas Cowboys", section: "Top 100" },
  { number: "18", name: "Justin Jefferson", team: "Minnesota Vikings", section: "Top 100" },
  { number: "19", name: "Roquan Smith", team: "Baltimore Ravens", section: "Top 100" },
  { number: "20", name: "C.J. Stroud", team: "Houston Texans", section: "Top 100" },
  { number: "21", name: "A.J. Brown", team: "Philadelphia Eagles", section: "Top 100" },
  { number: "22", name: "Penei Sewell", team: "Detroit Lions", section: "Top 100" },
  { number: "23", name: "Amon-Ra St. Brown", team: "Detroit Lions", section: "Top 100" },
  { number: "24", name: "Dexter Lawrence", team: "New York Giants", section: "Top 100" },
  { number: "25", name: "Jalen Ramsey", team: "Miami Dolphins", section: "Top 100" },
  { number: "26", name: "Mike Evans", team: "Tampa Bay Buccaneers", section: "Top 100" },
  { number: "27", name: "Nick Bosa", team: "San Francisco 49ers", section: "Top 100" },
  { number: "28", name: "Brock Purdy", team: "San Francisco 49ers", section: "Top 100" },
  { number: "29", name: "Khalil Mack", team: "Los Angeles Chargers", section: "Top 100" },
  { number: "31", name: "DaRon Bland", team: "Dallas Cowboys", section: "Top 100" },
  { number: "32", name: "Quincy Williams", team: "New York Jets", section: "Top 100" },
  { number: "33", name: "Puka Nacua", team: "Los Angeles Rams", section: "Top 100" },
  { number: "34", name: "Jordan Love", team: "Green Bay Packers", section: "Top 100" },
  { number: "35", name: "Josh Hines-Allen", team: "Jacksonville Jaguars", section: "Top 100" },
  { number: "36", name: "Tua Tagovailoa", team: "Miami Dolphins", section: "Top 100" },
  { number: "37", name: "Quinnen Williams", team: "New York Jets", section: "Top 100" },
  { number: "38", name: "Ahmad 'Sauce' Gardner", team: "New York Jets", section: "Top 100" },
  { number: "39", name: "Joe Burrow", team: "Cincinnati Bengals", section: "Top 100" },
  { number: "40", name: "Davante Adams", team: "New York Jets", section: "Top 100" },
  { number: "41", name: "Lane Johnson", team: "Philadelphia Eagles", section: "Top 100" },
  { number: "42", name: "Matthew Stafford", team: "Los Angeles Rams", section: "Top 100" },
  { number: "43", name: "Kyle Hamilton", team: "Baltimore Ravens", section: "Top 100" },
  { number: "44", name: "Demario Davis", team: "New Orleans Saints", section: "Top 100" },
  { number: "45", name: "Ja'Marr Chase", team: "Cincinnati Bengals", section: "Top 100" },
  { number: "46", name: "Antoine Winfield Jr.", team: "Tampa Bay Buccaneers", section: "Top 100" },
  { number: "47", name: "Aidan Hutchinson", team: "Detroit Lions", section: "Top 100" },
  { number: "48", name: "Jared Goff", team: "Detroit Lions", section: "Top 100" },
  { number: "49", name: "Derrick Henry", team: "Baltimore Ravens", section: "Top 100" },
  { number: "50", name: "Rashan Gary", team: "Green Bay Packers", section: "Top 100" },
  { number: "51", name: "Keenan Allen", team: "Chicago Bears", section: "Top 100" },
  { number: "52", name: "Patrick Surtain II", team: "Denver Broncos", section: "Top 100" },
  { number: "53", name: "Zack Martin", team: "Dallas Cowboys", section: "Top 100" },
  { number: "54", name: "Jonathan Allen", team: "Washington Commanders", section: "Top 100" },
  { number: "55", name: "Brian Burns", team: "New York Giants", section: "Top 100" },
  { number: "56", name: "Stefon Diggs", team: "Houston Texans", section: "Top 100" },
  { number: "57", name: "Justin Simmons", team: "Atlanta Falcons", section: "Top 100" },
  { number: "58", name: "Christian Wilkins", team: "Las Vegas Raiders", section: "Top 100" },
  { number: "59", name: "Bobby Wagner", team: "Washington Commanders", section: "Top 100" },
  { number: "60", name: "Raheem Mostert", team: "Miami Dolphins", section: "Top 100" },
  { number: "61", name: "Nnamdi Madubuike", team: "Baltimore Ravens", section: "Top 100" },
  { number: "62", name: "Bradley Chubb", team: "Miami Dolphins", section: "Top 100" },
  { number: "63", name: "Jaylen Waddle", team: "Miami Dolphins", section: "Top 100" },
  { number: "64", name: "Patrick Queen", team: "Pittsburgh Steelers", section: "Top 100" },
  { number: "65", name: "Jordan Poyer", team: "Miami Dolphins", section: "Top 100" },
  { number: "66", name: "Brandon Aiyuk", team: "San Francisco 49ers", section: "Top 100" },
  { number: "67", name: "Terron Armstead", team: "Miami Dolphins", section: "Top 100" },
  { number: "68", name: "Danielle Hunter", team: "Houston Texans", section: "Top 100" },
  { number: "69", name: "Cooper Kupp", team: "Los Angeles Rams", section: "Top 100" },
  { number: "70", name: "Amari Cooper", team: "Buffalo Bills", section: "Top 100" },
  { number: "71", name: "Laremy Tunsil", team: "Houston Texans", section: "Top 100" },
  { number: "72", name: "Garrett Wilson", team: "New York Jets", section: "Top 100" },
  { number: "73", name: "Jeffery Simmons", team: "Tennessee Titans", section: "Top 100" },
  { number: "74", name: "Jessie Bates III", team: "Atlanta Falcons", section: "Top 100" },
  { number: "75", name: "Justin Herbert", team: "Los Angeles Chargers", section: "Top 100" },
  { number: "76", name: "Dre Greenlaw", team: "San Francisco 49ers", section: "Top 100" },
  { number: "77", name: "Trey Hendrickson", team: "Cincinnati Bengals", section: "Top 100" },
  { number: "78", name: "Kyren Williams", team: "Los Angeles Rams", section: "Top 100" },
  { number: "79", name: "Minkah Fitzpatrick", team: "Pittsburgh Steelers", section: "Top 100" },
  { number: "80", name: "Sam LaPorta", team: "Detroit Lions", section: "Top 100" },
  { number: "81", name: "Kirk Cousins", team: "Atlanta Falcons", section: "Top 100" },
  { number: "82", name: "Montez Sweat", team: "Chicago Bears", section: "Top 100" },
  { number: "83", name: "Derwin James Jr.", team: "Los Angeles Chargers", section: "Top 100" },
  { number: "84", name: "DK Metcalf", team: "Seattle Seahawks", section: "Top 100" },
  { number: "85", name: "Tristan Wirfs", team: "Tampa Bay Buccaneers", section: "Top 100" },
  { number: "86", name: "Saquon Barkley", team: "Philadelphia Eagles", section: "Top 100" },
  { number: "88", name: "Chris Lindstrom", team: "Atlanta Falcons", section: "Top 100" },
  { number: "89", name: "Budda Baker", team: "Arizona Cardinals", section: "Top 100" },
  { number: "90", name: "DeVonta Smith", team: "Philadelphia Eagles", section: "Top 100" },
  { number: "91", name: "Tariq Woolen", team: "Seattle Seahawks", section: "Top 100" },
  { number: "92", name: "Aaron Rodgers", team: "New York Jets", section: "Top 100" },
  { number: "93", name: "Harrison Smith", team: "Minnesota Vikings", section: "Top 100" },
  { number: "94", name: "Trevor Lawrence", team: "Jacksonville Jaguars", section: "Top 100" },
  { number: "95", name: "Julian Love", team: "Seattle Seahawks", section: "Top 100" },
  { number: "96", name: "Dion Dawkins", team: "Buffalo Bills", section: "Top 100" },
  { number: "97", name: "Terry McLaurin", team: "Washington Commanders", section: "Top 100" },
  { number: "98", name: "Cameron Heyward", team: "Pittsburgh Steelers", section: "Top 100" },
  { number: "99", name: "Lavonte David", team: "Tampa Bay Buccaneers", section: "Top 100" },
  { number: "100", name: "Zaire Franklin", team: "Indianapolis Colts", section: "Top 100" },
];
