export type ChecklistEntry = {
  number: string;
  name: string;
  team?: string;
  section: string;
};

export const SCORE_2025_CHECKLIST: ChecklistEntry[] = [
  { number: "1", name: "A.J. Brown", team: "Philadelphia Eagles", section: "Base" },
  { number: "2", name: "Dak Prescott", team: "Dallas Cowboys", section: "Base" },
  { number: "3", name: "Ja'Lynn Polk", team: "New England Patriots", section: "Base" },
  { number: "4", name: "Keon Coleman", team: "Buffalo Bills", section: "Base" },
  { number: "5", name: "Trey McBride", team: "Arizona Cardinals", section: "Base" },
  { number: "6", name: "Brian Burns", team: "New York Giants", section: "Base" },
  { number: "7", name: "Doug Williams", team: "Tampa Bay Buccaneers", section: "Base" },
  { number: "8", name: "Joe Greene", team: "Pittsburgh Steelers", section: "Base" },
  { number: "9", name: "Nick Bolton", team: "Kansas City Chiefs", section: "Base" },
  { number: "10", name: "Roquan Smith", team: "Baltimore Ravens", section: "Base" },
  { number: "11", name: "Aaron Jones", team: "Minnesota Vikings", section: "Base" },
  { number: "12", name: "Dalton Hilliard", team: "New Orleans Saints", section: "Base" },
  { number: "13", name: "Ja'Marr Chase", team: "Cincinnati Bengals", section: "Base" },
  { number: "14", name: "Khalil Mack", team: "Los Angeles Chargers", section: "Base" },
  { number: "15", name: "Troy Franklin", team: "Denver Broncos", section: "Base" },
  { number: "16", name: "Brian Thomas Jr.", team: "Jacksonville Jaguars", section: "Base" },
  { number: "17", name: "Drake London", team: "Atlanta Falcons", section: "Base" },
  { number: "18", name: "Joe Horn", team: "New Orleans Saints", section: "Base" },
  { number: "19", name: "Nick Chubb", team: "Cleveland Browns", section: "Base" },
  { number: "20", name: "Roschon Johnson", team: "Chicago Bears", section: "Base" },
  { number: "21", name: "Adam Thielen", team: "Carolina Panthers", section: "Base" },
  { number: "22", name: "Dalton Kincaid", team: "Buffalo Bills", section: "Base" },
  { number: "23", name: "Ja'Tavion Sanders", team: "Carolina Panthers", section: "Base" },
  { number: "24", name: "Khalil Shakir", team: "Buffalo Bills", section: "Base" },
  { number: "25", name: "Tua Tagovailoa", team: "Miami Dolphins", section: "Base" },
  { number: "26", name: "Brian Urlacher", team: "Chicago Bears", section: "Base" },
  { number: "27", name: "Drake Maye", team: "New England Patriots", section: "Base" },
  { number: "28", name: "Joe Milton III", team: "New England Patriots", section: "Base" },
  { number: "29", name: "Nick Westbrook-Ikhine", team: "Miami Dolphins", section: "Base" },
  { number: "30", name: "Russell Wilson", team: "New York Giants", section: "Base" },
  { number: "31", name: "Aeneas Williams", team: "Arizona Cardinals", section: "Base" },
  { number: "32", name: "Dalton Schultz", team: "Houston Texans", section: "Base" },
  { number: "33", name: "Jahmyr Gibbs", team: "Detroit Lions", section: "Base" },
  { number: "34", name: "Kimani Vidal", team: "Los Angeles Chargers", section: "Base" },
  { number: "35", name: "Tucker Kraft", team: "Green Bay Packers", section: "Base" },
  { number: "36", name: "Brock Bowers", team: "Las Vegas Raiders", section: "Base" },
  { number: "37", name: "Drew Bledsoe", team: "Buffalo Bills", section: "Base" },
  { number: "38", name: "Joe Mixon", team: "Houston Texans", section: "Base" },
  { number: "39", name: "Nico Collins", team: "Houston Texans", section: "Base" },
  { number: "40", name: "Sam Darnold", team: "Seattle Seahawks", section: "Base" },
  { number: "41", name: "Aidan Hutchinson", team: "Detroit Lions", section: "Base" },
  { number: "42", name: "Danielle Hunter", team: "Houston Texans", section: "Base" },
  { number: "43", name: "Jakobi Meyers", team: "Las Vegas Raiders", section: "Base" },
  { number: "44", name: "Kyler Murray", team: "Arizona Cardinals", section: "Base" },
  { number: "45", name: "Cooper DeJean", team: "Philadelphia Eagles", section: "Base" },
  { number: "46", name: "Tyjae Spears", team: "Tennessee Titans", section: "Base" },
  { number: "47", name: "Brock Purdy", team: "San Francisco 49ers", section: "Base" },
  { number: "48", name: "E.J. Speed", team: "Indianapolis Colts", section: "Base" },
  { number: "49", name: "Joe Morris", team: "New York Giants", section: "Base" },
  { number: "50", name: "Nik Bonitto", team: "Denver Broncos", section: "Base" },
  { number: "51", name: "Sam LaPorta", team: "Detroit Lions", section: "Base" },
  { number: "52", name: "Aidan O'Connell", team: "Las Vegas Raiders", section: "Base" },
  { number: "53", name: "Darnell Mooney", team: "Atlanta Falcons", section: "Base" },
  { number: "54", name: "Jaleel McLaughlin", team: "Denver Broncos", section: "Base" },
  { number: "55", name: "Kyren Williams", team: "Los Angeles Rams", section: "Base" },
  { number: "56", name: "Tyler Allgeier", team: "Atlanta Falcons", section: "Base" },
  { number: "57", name: "Bryce Young", team: "Carolina Panthers", section: "Base" },
  { number: "58", name: "Eddy Pineiro", team: "Carolina Panthers", section: "Base" },
  { number: "59", name: "Joe Thomas", team: "Cleveland Browns", section: "Base" },
  { number: "60", name: "Olamide Zaccheaus", team: "Chicago Bears", section: "Base" },
  { number: "61", name: "Saquon Barkley", team: "Philadelphia Eagles", section: "Base" },
  { number: "62", name: "Al Toon", team: "New York Jets", section: "Base" },
  { number: "63", name: "Darren Woodson", team: "Dallas Cowboys", section: "Base" },
  { number: "64", name: "Jalen Carter", team: "Philadelphia Eagles", section: "Base" },
  { number: "65", name: "Ladd McConkey", team: "Los Angeles Chargers", section: "Base" },
  { number: "66", name: "Tyler Bass", team: "Buffalo Bills", section: "Base" },
  { number: "67", name: "Bucky Irving", team: "Tampa Bay Buccaneers", section: "Base" },
  { number: "68", name: "Edgerrin James", team: "Indianapolis Colts", section: "Base" },
  { number: "69", name: "John Elway", team: "Denver Broncos", section: "Base" },
  { number: "70", name: "Ozzie Newsome", team: "Cleveland Browns", section: "Base" },
  { number: "71", name: "Stefon Diggs", team: "New England Patriots", section: "Base" },
  { number: "72", name: "Alec Pierce", team: "Indianapolis Colts", section: "Base" },
  { number: "73", name: "Davante Adams", team: "Los Angeles Rams", section: "Base" },
  { number: "74", name: "Jalen Coker", team: "Carolina Panthers", section: "Base" },
  { number: "75", name: "Lamar Jackson", team: "Baltimore Ravens", section: "Base" },
  { number: "76", name: "Tyler Boyd", team: "Tennessee Titans", section: "Base" },
  { number: "77", name: "Budda Baker", team: "Arizona Cardinals", section: "Base" },
  { number: "78", name: "Eli Manning", team: "New York Giants", section: "Base" },
  { number: "79", name: "Jonathan Stewart", team: "Carolina Panthers", section: "Base" },
  { number: "80", name: "Parker Washington", team: "Jacksonville Jaguars", section: "Base" },
  { number: "81", name: "Stephon Gilmore", team: "Minnesota Vikings", section: "Base" },
  { number: "82", name: "AJ Barner", team: "Seattle Seahawks", section: "Base" },
  { number: "83", name: "Dave Casper", team: "Oakland Raiders", section: "Base" },
  { number: "84", name: "Jalen Hurts", team: "Philadelphia Eagles", section: "Base" },
  { number: "85", name: "Malachi Corley", team: "New York Jets", section: "Base" },
  { number: "86", name: "Tyler Lockett", team: "Tennessee Titans", section: "Base" },
  { number: "87", name: "C.J. Mosley", team: "New York Jets", section: "Base" },
  { number: "88", name: "Foye Oluokun", team: "Jacksonville Jaguars", section: "Base" },
  { number: "89", name: "Jonathan Taylor", team: "Indianapolis Colts", section: "Base" },
  { number: "90", name: "Pat Freiermuth", team: "Pittsburgh Steelers", section: "Base" },
  { number: "91", name: "T'Vondre Sweat", team: "Tennessee Titans", section: "Base" },
  { number: "92", name: "Alex Anzalone", team: "Detroit Lions", section: "Base" },
  { number: "93", name: "Dave Krieg", team: "Seattle Seahawks", section: "Base" },
  { number: "94", name: "Jalen McMillan", team: "Tampa Bay Buccaneers", section: "Base" },
  { number: "95", name: "Malik Hooker", team: "Dallas Cowboys", section: "Base" },
  { number: "96", name: "Tyrann Mathieu", team: "New Orleans Saints", section: "Base" },
  { number: "97", name: "C.J. Stroud", team: "Houston Texans", section: "Base" },
  { number: "98", name: "Fran Tarkenton", team: "Minnesota Vikings", section: "Base" },
  { number: "99", name: "Jonnu Smith", team: "Miami Dolphins", section: "Base" },
  { number: "100", name: "Patrick Mahomes II", team: "Kansas City Chiefs", section: "Base" },
  { number: "101", name: "T.J. Hockenson", team: "Minnesota Vikings", section: "Base" },
  { number: "102", name: "Alex Highsmith", team: "Pittsburgh Steelers", section: "Base" },
  { number: "103", name: "David Montgomery", team: "Detroit Lions", section: "Base" },
  { number: "104", name: "Jalen Tolbert", team: "Dallas Cowboys", section: "Base" },
  { number: "105", name: "Malik Nabers", team: "New York Giants", section: "Base" },
  { number: "106", name: "Tyreek Hill", team: "Miami Dolphins", section: "Base" },
  { number: "107", name: "Caleb Williams", team: "Chicago Bears", section: "Base" },
  { number: "108", name: "Frankie Luvu", team: "Washington Commanders", section: "Base" },
  { number: "109", name: "Jordan Addison", team: "Minnesota Vikings", section: "Base" },
  { number: "110", name: "Patrick Surtain II", team: "Denver Broncos", section: "Base" },
  { number: "111", name: "T.J. Watt", team: "Pittsburgh Steelers", section: "Base" },
  { number: "112", name: "Alexander Mattison", team: "Miami Dolphins", section: "Base" },
  { number: "113", name: "David Njoku", team: "Cleveland Browns", section: "Base" },
  { number: "114", name: "James Conner", team: "Arizona Cardinals", section: "Base" },
  { number: "115", name: "Mark Andrews", team: "Baltimore Ravens", section: "Base" },
  { number: "116", name: "Tyrone Tracy Jr.", team: "New York Giants", section: "Base" },
  { number: "117", name: "Calvin Ridley", team: "Tennessee Titans", section: "Base" },
  { number: "118", name: "Fred Warner", team: "San Francisco 49ers", section: "Base" },
  { number: "119", name: "Jordan Love", team: "Green Bay Packers", section: "Base" },
  { number: "120", name: "Puka Nacua", team: "Los Angeles Rams", section: "Base" },
  { number: "121", name: "Tank Bigsby", team: "Jacksonville Jaguars", section: "Base" },
  { number: "122", name: "Alvin Kamara", team: "New Orleans Saints", section: "Base" },
  { number: "123", name: "De'Von Achane", team: "Miami Dolphins", section: "Base" },
  { number: "124", name: "James Cook", team: "Buffalo Bills", section: "Base" },
  { number: "125", name: "Mark Gastineau", team: "New York Jets", section: "Base" },
  { number: "126", name: "Vince Ferragamo", team: "Los Angeles Rams", section: "Base" },
  { number: "127", name: "Cameron Dicker", team: "Los Angeles Chargers", section: "Base" },
  { number: "128", name: "Garrett Wilson", team: "New York Jets", section: "Base" },
  { number: "129", name: "Jordan Mailata", team: "Philadelphia Eagles", section: "Base" },
  { number: "130", name: "Quentin Johnston", team: "Los Angeles Chargers", section: "Base" },
  { number: "131", name: "Tank Dell", team: "Houston Texans", section: "Base" },
  { number: "132", name: "Amari Cooper", team: "Buffalo Bills", section: "Base" },
  { number: "133", name: "DeAndre Hopkins", team: "Baltimore Ravens", section: "Base" },
  { number: "134", name: "Jameson Williams", team: "Detroit Lions", section: "Base" },
  { number: "135", name: "Mark Rypien", team: "Washington Redskins", section: "Base" },
  { number: "136", name: "Vince Young", team: "Tennessee Titans", section: "Base" },
  { number: "137", name: "CeeDee Lamb", team: "Dallas Cowboys", section: "Base" },
  { number: "138", name: "Geno Smith", team: "Las Vegas Raiders", section: "Base" },
  { number: "139", name: "Jordyn Brooks", team: "Miami Dolphins", section: "Base" },
  { number: "140", name: "Quinyon Mitchell", team: "Philadelphia Eagles", section: "Base" },
  { number: "141", name: "Taysom Hill", team: "New Orleans Saints", section: "Base" },
  { number: "142", name: "Amon-Ra St. Brown", team: "Detroit Lions", section: "Base" },
  { number: "143", name: "Deebo Samuel", team: "Washington Commanders", section: "Base" },
  { number: "144", name: "Jamien Sherwood", team: "New York Jets", section: "Base" },
  { number: "145", name: "Marlon Humphrey", team: "Baltimore Ravens", section: "Base" },
  { number: "146", name: "Vinny Testaverde", team: "Cleveland Browns", section: "Base" },
  { number: "147", name: "Charvarius Ward", team: "Indianapolis Colts", section: "Base" },
  { number: "148", name: "Geno Stone", team: "Cincinnati Bengals", section: "Base" },
  { number: "149", name: "Josey Jewell", team: "Carolina Panthers", section: "Base" },
  { number: "150", name: "Rachaad White", team: "Tampa Bay Buccaneers", section: "Base" },
  { number: "151", name: "Tedy Bruschi", team: "New England Patriots", section: "Base" },
  { number: "152", name: "Andrew Van Ginkel", team: "Minnesota Vikings", section: "Base" },
  { number: "153", name: "DeForest Buckner", team: "Indianapolis Colts", section: "Base" },
  { number: "154", name: "Jared Goff", team: "Detroit Lions", section: "Base" },
  { number: "155", name: "Marquez Valdes-Scantling", team: "Seattle Seahawks", section: "Base" },
  { number: "156", name: "Vita Vea", team: "Tampa Bay Buccaneers", section: "Base" },
  { number: "157", name: "Chase Brown", team: "Cincinnati Bengals", section: "Base" },
  { number: "158", name: "George Karlaftis", team: "Kansas City Chiefs", section: "Base" },
  { number: "159", name: "Josh Allen", team: "Buffalo Bills", section: "Base" },
  { number: "160", name: "Raheem Mostert", team: "Las Vegas Raiders", section: "Base" },
  { number: "161", name: "Tee Higgins", team: "Cincinnati Bengals", section: "Base" },
  { number: "162", name: "Anthony Munoz", team: "Cincinnati Bengals", section: "Base" },
  { number: "163", name: "Demario Douglas", team: "New England Patriots", section: "Base" },
  { number: "164", name: "Jared Verse", team: "Los Angeles Rams", section: "Base" },
  { number: "165", name: "Marshon Lattimore", team: "Washington Commanders", section: "Base" },
  { number: "166", name: "Wan'Dale Robinson", team: "New York Giants", section: "Base" },
  { number: "167", name: "Chop Robinson", team: "Miami Dolphins", section: "Base" },
  { number: "168", name: "George Kittle", team: "San Francisco 49ers", section: "Base" },
  { number: "169", name: "Josh Downs", team: "Indianapolis Colts", section: "Base" },
  { number: "170", name: "Rashan Gary", team: "Green Bay Packers", section: "Base" },
  { number: "171", name: "Terrell Suggs", team: "Baltimore Ravens", section: "Base" },
  { number: "172", name: "Audric Estime", team: "Denver Broncos", section: "Base" },
  { number: "173", name: "Anthony Richardson", team: "Indianapolis Colts", section: "Base" },
  { number: "174", name: "Denzel Ward", team: "Cleveland Browns", section: "Base" },
  { number: "175", name: "Jason Taylor", team: "Miami Dolphins", section: "Base" },
  { number: "176", name: "Brian Robinson Jr.", team: "Washington Commanders", section: "Base" },
  { number: "177", name: "Marte Mapu", team: "New England Patriots", section: "Base" },
  { number: "178", name: "Warren Moon", team: "Minnesota Vikings", section: "Base" },
  { number: "179", name: "Chris Boswell", team: "Pittsburgh Steelers", section: "Base" },
  { number: "180", name: "George Pickens", team: "Pittsburgh Steelers", section: "Base" },
  { number: "181", name: "Josh Hines-Allen", team: "Jacksonville Jaguars", section: "Base" },
  { number: "182", name: "Rashee Rice", team: "Kansas City Chiefs", section: "Base" },
  { number: "183", name: "Terry McLaurin", team: "Washington Commanders", section: "Base" },
  { number: "184", name: "Deommodore Lenoir", team: "San Francisco 49ers", section: "Base" },
  { number: "185", name: "Jaxon Smith-Njigba", team: "Seattle Seahawks", section: "Base" },
  { number: "186", name: "Marvin Harrison Jr.", team: "Arizona Cardinals", section: "Base" },
  { number: "187", name: "Will Anderson Jr.", team: "Houston Texans", section: "Base" },
  { number: "188", name: "Chris Godwin", team: "Tampa Bay Buccaneers", section: "Base" },
  { number: "189", name: "Gervon Dexter Sr.", team: "Chicago Bears", section: "Base" },
  { number: "190", name: "Josh Jacobs", team: "Green Bay Packers", section: "Base" },
  { number: "191", name: "Rashid Shaheed", team: "New Orleans Saints", section: "Base" },
  { number: "192", name: "Theo Johnson", team: "New York Giants", section: "Base" },
  { number: "193", name: "Antonio Gates", team: "Los Angeles Chargers", section: "Base" },
  { number: "194", name: "Derek Stingley Jr.", team: "Houston Texans", section: "Base" },
  { number: "195", name: "Jayden Daniels", team: "Washington Commanders", section: "Base" },
  { number: "196", name: "Matthew Stafford", team: "Los Angeles Rams", section: "Base" },
  { number: "197", name: "William Andrews", team: "Atlanta Falcons", section: "Base" },
  { number: "198", name: "Chris Jones", team: "Kansas City Chiefs", section: "Base" },
  { number: "199", name: "Golden Tate III", team: "Detroit Lions", section: "Base" },
  { number: "200", name: "Joshua Karty", team: "Los Angeles Rams", section: "Base" },
  { number: "201", name: "Rashod Bateman", team: "Baltimore Ravens", section: "Base" },
  { number: "202", name: "Tony Dorsett", team: "Dallas Cowboys", section: "Base" },
  { number: "203", name: "Austin Ekeler", team: "Washington Commanders", section: "Base" },
  { number: "204", name: "Derrick Henry", team: "Baltimore Ravens", section: "Base" },
  { number: "205", name: "Jayden Reed", team: "Green Bay Packers", section: "Base" },
  { number: "206", name: "Maxx Crosby", team: "Las Vegas Raiders", section: "Base" },
  { number: "207", name: "Willie Gault", team: "Chicago Bears", section: "Base" },
  { number: "208", name: "Chris Long", team: "St. Louis Rams", section: "Base" },
  { number: "209", name: "Grady Jarrett", team: "Chicago Bears", section: "Base" },
  { number: "210", name: "Justin Fields", team: "New York Jets", section: "Base" },
  { number: "211", name: "Rhamondre Stevenson", team: "New England Patriots", section: "Base" },
  { number: "212", name: "Tony Pollard", team: "Tennessee Titans", section: "Base" },
  { number: "213", name: "Baker Mayfield", team: "Tampa Bay Buccaneers", section: "Base" },
  { number: "214", name: "Derwin James Jr.", team: "Los Angeles Chargers", section: "Base" },
  { number: "215", name: "Jaylen Waddle", team: "Miami Dolphins", section: "Base" },
  { number: "216", name: "Micah McFadden", team: "New York Giants", section: "Base" },
  { number: "217", name: "Xavier Legette", team: "Carolina Panthers", section: "Base" },
  { number: "218", name: "Chris Olave", team: "New Orleans Saints", section: "Base" },
  { number: "219", name: "Grant Calcaterra", team: "Philadelphia Eagles", section: "Base" },
  { number: "220", name: "Justin Herbert", team: "Los Angeles Chargers", section: "Base" },
  { number: "221", name: "Rich Gannon", team: "Oakland Raiders", section: "Base" },
  { number: "222", name: "Travis Etienne Jr.", team: "Jacksonville Jaguars", section: "Base" },
  { number: "223", name: "Bijan Robinson", team: "Atlanta Falcons", section: "Base" },
  { number: "224", name: "Deshaun Watson", team: "Cleveland Browns", section: "Base" },
  { number: "225", name: "Jaylen Warren", team: "Pittsburgh Steelers", section: "Base" },
  { number: "226", name: "Micah Parsons", team: "Dallas Cowboys", section: "Base" },
  { number: "227", name: "Xavier McKinney", team: "Green Bay Packers", section: "Base" },
  { number: "228", name: "Christian Gonzalez", team: "New England Patriots", section: "Base" },
  { number: "229", name: "Greg Dortch", team: "Arizona Cardinals", section: "Base" },
  { number: "230", name: "Justin Jefferson", team: "Minnesota Vikings", section: "Base" },
  { number: "231", name: "Ricky Pearsall", team: "San Francisco 49ers", section: "Base" },
  { number: "232", name: "Travis Kelce", team: "Kansas City Chiefs", section: "Base" },
  { number: "233", name: "Billy Sims", team: "Detroit Lions", section: "Base" },
  { number: "234", name: "Devin Singletary", team: "New York Giants", section: "Base" },
  { number: "235", name: "Jeffery Simmons", team: "Tennessee Titans", section: "Base" },
  { number: "236", name: "Michael Penix Jr.", team: "Atlanta Falcons", section: "Base" },
  { number: "237", name: "Xavier Worthy", team: "Kansas City Chiefs", section: "Base" },
  { number: "238", name: "Christian McCaffrey", team: "San Francisco 49ers", section: "Base" },
  { number: "239", name: "Greg Rousseau", team: "Buffalo Bills", section: "Base" },
  { number: "240", name: "Justin Simmons", team: "Atlanta Falcons", section: "Base" },
  { number: "241", name: "Rico Dowdle", team: "Carolina Panthers", section: "Base" },
  { number: "242", name: "Tre Tucker", team: "Las Vegas Raiders", section: "Base" },
  { number: "243", name: "Blake Corum", team: "Los Angeles Rams", section: "Base" },
  { number: "244", name: "DeVonta Smith", team: "Philadelphia Eagles", section: "Base" },
  { number: "245", name: "Jerome Bettis", team: "Pittsburgh Steelers", section: "Base" },
  { number: "246", name: "Michael Pittman Jr.", team: "Indianapolis Colts", section: "Base" },
  { number: "247", name: "Zach Charbonnet", team: "Seattle Seahawks", section: "Base" },
  { number: "248", name: "Christian Watson", team: "Green Bay Packers", section: "Base" },
  { number: "249", name: "Hunter Henry", team: "New England Patriots", section: "Base" },
  { number: "250", name: "KaVontae Turpin", team: "Dallas Cowboys", section: "Base" },
  { number: "251", name: "Riley Moss", team: "Denver Broncos", section: "Base" },
  { number: "252", name: "Trent Dilfer", team: "Baltimore Ravens", section: "Base" },
  { number: "253", name: "Bo Nix", team: "Denver Broncos", section: "Base" },
  { number: "254", name: "DJ Moore", team: "Chicago Bears", section: "Base" },
  { number: "255", name: "Jerome Ford", team: "Cleveland Browns", section: "Base" },
  { number: "256", name: "Michael Vick", team: "Atlanta Falcons", section: "Base" },
  { number: "257", name: "Zach Ertz", team: "Washington Commanders", section: "Base" },
  { number: "258", name: "Chuba Hubbard", team: "Carolina Panthers", section: "Base" },
  { number: "259", name: "Isaac Guerendo", team: "San Francisco 49ers", section: "Base" },
  { number: "260", name: "Keenan Allen", team: "Chicago Bears", section: "Base" },
  { number: "261", name: "Robert Brazile", team: "Houston Oilers", section: "Base" },
  { number: "262", name: "Trent Green", team: "Kansas City Chiefs", section: "Base" },
  { number: "263", name: "Braden Fiske", team: "Los Angeles Rams", section: "Base" },
  { number: "264", name: "DK Metcalf", team: "Pittsburgh Steelers", section: "Base" },
  { number: "265", name: "Jerry Jeudy", team: "Cleveland Browns", section: "Base" },
  { number: "266", name: "Michael Wilson", team: "Arizona Cardinals", section: "Base" },
  { number: "267", name: "Zay Flowers", team: "Baltimore Ravens", section: "Base" },
  { number: "268", name: "Coby Bryant", team: "Seattle Seahawks", section: "Base" },
  { number: "269", name: "Isaiah Likely", team: "Baltimore Ravens", section: "Base" },
  { number: "270", name: "Kellen Winslow", team: "San Diego Chargers", section: "Base" },
  { number: "271", name: "Robert Mathis", team: "Indianapolis Colts", section: "Base" },
  { number: "272", name: "Trevor Lawrence", team: "Jacksonville Jaguars", section: "Base" },
  { number: "273", name: "Braelon Allen", team: "New York Jets", section: "Base" },
  { number: "274", name: "Don Majkowski", team: "Green Bay Packers", section: "Base" },
  { number: "275", name: "Jimmy Smith", team: "Jacksonville Jaguars", section: "Base" },
  { number: "276", name: "Mike Alstott", team: "Tampa Bay Buccaneers", section: "Base" },
  { number: "277", name: "Cooper Kupp", team: "Seattle Seahawks", section: "Base" },
  { number: "278", name: "Isiah Pacheco", team: "Kansas City Chiefs", section: "Base" },
  { number: "279", name: "Ken Anderson", team: "Cincinnati Bengals", section: "Base" },
  { number: "280", name: "Robert Spillane", team: "New England Patriots", section: "Base" },
  { number: "281", name: "Trey Benson", team: "Arizona Cardinals", section: "Base" },
  { number: "282", name: "Breece Hall", team: "New York Jets", section: "Base" },
  { number: "283", name: "Donovan McNabb", team: "Philadelphia Eagles", section: "Base" },
  { number: "284", name: "Joe Burrow", team: "Cincinnati Bengals", section: "Base" },
  { number: "285", name: "Mike Evans", team: "Tampa Bay Buccaneers", section: "Base" },
  { number: "286", name: "Courtland Sutton", team: "Denver Broncos", section: "Base" },
  { number: "287", name: "Ivan Pace Jr.", team: "Minnesota Vikings", section: "Base" },
  { number: "288", name: "Matt Araiza", team: "Kansas City Chiefs", section: "Base" },
  { number: "289", name: "Rome Odunze", team: "Chicago Bears", section: "Base" },
  { number: "290", name: "Trey Hendrickson", team: "Cincinnati Bengals", section: "Base" },
  { number: "291", name: "J.J. McCarthy", team: "Minnesota Vikings", section: "Base" },
  { number: "292", name: "Dontayvion Wicks", team: "Green Bay Packers", section: "Base" },
  { number: "293", name: "Joe Cribbs", team: "Buffalo Bills", section: "Base" },
  { number: "294", name: "Mike Sainristil", team: "Washington Commanders", section: "Base" },
  { number: "295", name: "D'Andre Swift", team: "Chicago Bears", section: "Base" },
  { number: "296", name: "J.K. Dobbins", team: "Los Angeles Chargers", section: "Base" },
  { number: "297", name: "Kenneth Walker III", team: "Seattle Seahawks", section: "Base" },
  { number: "298", name: "Ronde Barber", team: "Tampa Bay Buccaneers", section: "Base" },
  { number: "299", name: "Ken Houston", team: "Houston Oilers", section: "Base" },
  { number: "300", name: "Payton Wilson", team: "Pittsburgh Steelers", section: "Base" },
  { number: "1", name: "Cam Skattebo", team: "New York Giants", section: "Rookies" },
  { number: "2", name: "Emeka Egbuka", team: "Tampa Bay Buccaneers", section: "Rookies" },
  { number: "3", name: "Will Howard", team: "Pittsburgh Steelers", section: "Rookies" },
  { number: "4", name: "Harold Fannin Jr.", team: "Cleveland Browns", section: "Rookies" },
  { number: "5", name: "Elic Ayomanor", team: "Tennessee Titans", section: "Rookies" },
  { number: "6", name: "Xavier Restrepo", team: "Tennessee Titans", section: "Rookies" },
  { number: "7", name: "Mason Taylor", team: "New York Jets", section: "Rookies" },
  { number: "8", name: "Jalen Royals", team: "Kansas City Chiefs", section: "Rookies" },
  { number: "9", name: "Riley Leonard", team: "Indianapolis Colts", section: "Rookies" },
  { number: "10", name: "Ollie Gordon II", team: "Miami Dolphins", section: "Rookies" },
  { number: "11", name: "Will Johnson", team: "Arizona Cardinals", section: "Rookies" },
  { number: "12", name: "Kaleb Johnson", team: "Pittsburgh Steelers", section: "Rookies" },
  { number: "13", name: "Cam Ward", team: "Tennessee Titans", section: "Rookies" },
  { number: "14", name: "Ashton Jeanty", team: "Las Vegas Raiders", section: "Rookies" },
  { number: "15", name: "Shedeur Sanders", team: "Cleveland Browns", section: "Rookies" },
  { number: "16", name: "Abdul Carter", team: "New York Giants", section: "Rookies" },
  { number: "17", name: "Tetairoa McMillan", team: "Carolina Panthers", section: "Rookies" },
  { number: "18", name: "Luther Burden III", team: "Chicago Bears", section: "Rookies" },
  { number: "19", name: "Kaden Prather", team: "Buffalo Bills", section: "Rookies" },
  { number: "20", name: "Travis Hunter", team: "Jacksonville Jaguars", section: "Rookies" },
  { number: "21", name: "Tyler Warren", team: "Indianapolis Colts", section: "Rookies" },
  { number: "22", name: "Mason Graham", team: "Cleveland Browns", section: "Rookies" },
  { number: "23", name: "Kelvin Banks Jr.", team: "New Orleans Saints", section: "Rookies" },
  { number: "24", name: "Malaki Starks", team: "Baltimore Ravens", section: "Rookies" },
  { number: "25", name: "Will Campbell", team: "New England Patriots", section: "Rookies" },
  { number: "26", name: "James Pearce Jr.", team: "Atlanta Falcons", section: "Rookies" },
  { number: "27", name: "Nic Scourton", team: "Carolina Panthers", section: "Rookies" },
  { number: "28", name: "Mykel Williams", team: "San Francisco 49ers", section: "Rookies" },
  { number: "29", name: "Jalen Milroe", team: "Seattle Seahawks", section: "Rookies" },
  { number: "30", name: "Jalon Walker", team: "Atlanta Falcons", section: "Rookies" },
  { number: "31", name: "Colston Loveland", team: "Chicago Bears", section: "Rookies" },
  { number: "32", name: "Josh Simmons", team: "Kansas City Chiefs", section: "Rookies" },
  { number: "33", name: "Kenneth Grant", team: "Miami Dolphins", section: "Rookies" },
  { number: "34", name: "Tez Johnson", team: "Tampa Bay Buccaneers", section: "Rookies" },
  { number: "35", name: "Jaxson Dart", team: "New York Giants", section: "Rookies" },
  { number: "36", name: "Brady Cook", team: "New York Jets", section: "Rookies" },
  { number: "37", name: "Omarion Hampton", team: "Los Angeles Chargers", section: "Rookies" },
  { number: "38", name: "Quinshon Judkins", team: "Cleveland Browns", section: "Rookies" },
  { number: "39", name: "Jaydon Blue", team: "Dallas Cowboys", section: "Rookies" },
  { number: "40", name: "Devin Neal", team: "New Orleans Saints", section: "Rookies" },
  { number: "41", name: "Dillon Gabriel", team: "Cleveland Browns", section: "Rookies" },
  { number: "42", name: "Tre Harris", team: "Los Angeles Chargers", section: "Rookies" },
  { number: "43", name: "Woody Marks", team: "Houston Texans", section: "Rookies" },
  { number: "44", name: "Phil Mafah", team: "Dallas Cowboys", section: "Rookies" },
  { number: "45", name: "Raheim Sanders", team: "Los Angeles Chargers", section: "Rookies" },
  { number: "46", name: "Damien Martinez", team: "Seattle Seahawks", section: "Rookies" },
  { number: "47", name: "Jordan James", team: "San Francisco 49ers", section: "Rookies" },
  { number: "48", name: "Kyle Monangai", team: "Chicago Bears", section: "Rookies" },
  { number: "49", name: "RJ Harvey", team: "Denver Broncos", section: "Rookies" },
  { number: "50", name: "Elijah Arroyo", team: "Seattle Seahawks", section: "Rookies" },
  { number: "51", name: "Trevor Etienne", team: "Carolina Panthers", section: "Rookies" },
  { number: "52", name: "Dylan Sampson", team: "Cleveland Browns", section: "Rookies" },
  { number: "53", name: "Isaiah Bond", team: "Texas Longhorns", section: "Rookies" },
  { number: "54", name: "Savion Williams", team: "Green Bay Packers", section: "Rookies" },
  { number: "55", name: "Jayden Higgins", team: "Houston Texans", section: "Rookies" },
  { number: "56", name: "Matthew Golden", team: "Green Bay Packers", section: "Rookies" },
  { number: "57", name: "Kyle Williams", team: "New England Patriots", section: "Rookies" },
  { number: "58", name: "Tory Horton", team: "Seattle Seahawks", section: "Rookies" },
  { number: "59", name: "TreVeyon Henderson", team: "New England Patriots", section: "Rookies" },
  { number: "60", name: "Tai Felton", team: "Minnesota Vikings", section: "Rookies" },
  { number: "61", name: "Ja'Corey Brooks", team: "Washington Commanders", section: "Rookies" },
  { number: "62", name: "Kalel Mullings", team: "Tennessee Titans", section: "Rookies" },
  { number: "63", name: "Jack Bech", team: "Las Vegas Raiders", section: "Rookies" },
  { number: "64", name: "Pat Bryant", team: "Denver Broncos", section: "Rookies" },
  { number: "65", name: "Cobee Bryant", team: "Atlanta Falcons", section: "Rookies" },
  { number: "66", name: "Cameron Williams", team: "Philadelphia Eagles", section: "Rookies" },
  { number: "67", name: "Antwane Wells Jr.", team: "New York Giants", section: "Rookies" },
  { number: "68", name: "Jaylin Noel", team: "Houston Texans", section: "Rookies" },
  { number: "69", name: "Elijhah Badger", team: "Kansas City Chiefs", section: "Rookies" },
  { number: "70", name: "Armand Membou", team: "New York Jets", section: "Rookies" },
  { number: "71", name: "Tyler Shough", team: "New Orleans Saints", section: "Rookies" },
  { number: "72", name: "Terrance Ferguson", team: "Los Angeles Rams", section: "Rookies" },
  { number: "73", name: "Kyle McCord", team: "Philadelphia Eagles", section: "Rookies" },
  { number: "74", name: "Jake Briningstool", team: "Kansas City Chiefs", section: "Rookies" },
  { number: "75", name: "Quinn Ewers", team: "Miami Dolphins", section: "Rookies" },
  { number: "76", name: "Andres Borregales", team: "New England Patriots", section: "Rookies" },
  { number: "77", name: "Aireontae Ersery", team: "Houston Texans", section: "Rookies" },
  { number: "78", name: "Walter Nolen", team: "Arizona Cardinals", section: "Rookies" },
  { number: "79", name: "Shemar Stewart", team: "Cincinnati Bengals", section: "Rookies" },
  { number: "80", name: "Bhayshul Tuten", team: "Jacksonville Jaguars", section: "Rookies" },
  { number: "81", name: "Derrick Harmon", team: "Pittsburgh Steelers", section: "Rookies" },
  { number: "82", name: "Kurtis Rourke", team: "San Francisco 49ers", section: "Rookies" },
  { number: "83", name: "Jack Sawyer", team: "Pittsburgh Steelers", section: "Rookies" },
  { number: "84", name: "JT Tuimoloau", team: "Indianapolis Colts", section: "Rookies" },
  { number: "85", name: "Tyleik Williams", team: "Detroit Lions", section: "Rookies" },
  { number: "86", name: "Princely Umanmielen", team: "Carolina Panthers", section: "Rookies" },
  { number: "87", name: "Landon Jackson", team: "Buffalo Bills", section: "Rookies" },
  { number: "88", name: "Mike Green", team: "Baltimore Ravens", section: "Rookies" },
  { number: "89", name: "Jahdae Barron", team: "Denver Broncos", section: "Rookies" },
  { number: "90", name: "Donovan Jackson", team: "Minnesota Vikings", section: "Rookies" },
  { number: "91", name: "Shavon Revel Jr.", team: "Dallas Cowboys", section: "Rookies" },
  { number: "92", name: "Trey Amos", team: "Washington Commanders", section: "Rookies" },
  { number: "93", name: "Benjamin Morrison", team: "Tampa Bay Buccaneers", section: "Rookies" },
  { number: "94", name: "Xavier Watts", team: "Atlanta Falcons", section: "Rookies" },
  { number: "95", name: "DJ Giddens", team: "Indianapolis Colts", section: "Rookies" },
  { number: "96", name: "Nick Emmanwori", team: "Seattle Seahawks", section: "Rookies" },
  { number: "97", name: "Kevin Winston Jr.", team: "Tennessee Titans", section: "Rookies" },
  { number: "98", name: "Andrew Mukuba", team: "Philadelphia Eagles", section: "Rookies" },
  { number: "99", name: "Gunnar Helm", team: "Tennessee Titans", section: "Rookies" },
  { number: "100", name: "Josh Conerly Jr.", team: "Washington Commanders", section: "Rookies" },
  { number: "301", name: "Mystery Rookie 1", section: "Mystery Rookie Redemption" },
  { number: "302", name: "Mystery Rookie 2", section: "Mystery Rookie Redemption" },
  { number: "303", name: "Mystery Rookie 3", section: "Mystery Rookie Redemption" },
  { number: "304", name: "Mystery Rookie 4", section: "Mystery Rookie Redemption" },
  { number: "305", name: "Mystery Rookie 5", section: "Mystery Rookie Redemption" },
  { number: "306", name: "Mystery Rookie 6", section: "Mystery Rookie Redemption" },
];
