export type MemorabiliaEntry = {
  number: string;
  name: string;
  team?: string;
  section: "Stars of the NFL Jerseys" | "Zoned In Jerseys";
};

export const SCORE_2025_MEMORABILIA: MemorabiliaEntry[] = [
  // Stars of the NFL Jerseys
  { number: "1", name: "Kyler Murray", team: "Arizona Cardinals", section: "Stars of the NFL Jerseys" },
  { number: "2", name: "Marvin Harrison Jr.", team: "Arizona Cardinals", section: "Stars of the NFL Jerseys" },
  { number: "3", name: "Bijan Robinson", team: "Atlanta Falcons", section: "Stars of the NFL Jerseys" },
  { number: "4", name: "Drake London", team: "Atlanta Falcons", section: "Stars of the NFL Jerseys" },
  { number: "5", name: "Lamar Jackson", team: "Baltimore Ravens", section: "Stars of the NFL Jerseys" },
  { number: "6", name: "Derrick Henry", team: "Baltimore Ravens", section: "Stars of the NFL Jerseys" },
  { number: "7", name: "Josh Allen", team: "Buffalo Bills", section: "Stars of the NFL Jerseys" },
  { number: "8", name: "Chuba Hubbard", team: "Carolina Panthers", section: "Stars of the NFL Jerseys" },
  { number: "9", name: "Caleb Williams", team: "Chicago Bears", section: "Stars of the NFL Jerseys" },
  { number: "10", name: "DJ Moore", team: "Chicago Bears", section: "Stars of the NFL Jerseys" },
  { number: "11", name: "Ja'Marr Chase", team: "Cincinnati Bengals", section: "Stars of the NFL Jerseys" },
  { number: "12", name: "Joe Burrow", team: "Cincinnati Bengals", section: "Stars of the NFL Jerseys" },
  { number: "13", name: "Jerry Jeudy", team: "Cleveland Browns", section: "Stars of the NFL Jerseys" },
  { number: "14", name: "CeeDee Lamb", team: "Dallas Cowboys", section: "Stars of the NFL Jerseys" },
  { number: "15", name: "Dak Prescott", team: "Dallas Cowboys", section: "Stars of the NFL Jerseys" },
  { number: "16", name: "Bo Nix", team: "Denver Broncos", section: "Stars of the NFL Jerseys" },
  { number: "17", name: "Jahmyr Gibbs", team: "Detroit Lions", section: "Stars of the NFL Jerseys" },
  { number: "18", name: "Amon-Ra St. Brown", team: "Detroit Lions", section: "Stars of the NFL Jerseys" },
  { number: "19", name: "Jordan Love", team: "Green Bay Packers", section: "Stars of the NFL Jerseys" },
  { number: "20", name: "Josh Jacobs", team: "Green Bay Packers", section: "Stars of the NFL Jerseys" },
  { number: "21", name: "Nico Collins", team: "Houston Texans", section: "Stars of the NFL Jerseys" },
  { number: "22", name: "C.J. Stroud", team: "Houston Texans", section: "Stars of the NFL Jerseys" },
  { number: "23", name: "Jonathan Taylor", team: "Indianapolis Colts", section: "Stars of the NFL Jerseys" },
  { number: "24", name: "Brian Thomas Jr.", team: "Jacksonville Jaguars", section: "Stars of the NFL Jerseys" },
  { number: "25", name: "Patrick Mahomes II", team: "Kansas City Chiefs", section: "Stars of the NFL Jerseys" },
  { number: "26", name: "Travis Kelce", team: "Kansas City Chiefs", section: "Stars of the NFL Jerseys" },
  { number: "27", name: "Brock Bowers", team: "Las Vegas Raiders", section: "Stars of the NFL Jerseys" },
  { number: "28", name: "Justin Herbert", team: "Los Angeles Chargers", section: "Stars of the NFL Jerseys" },
  { number: "29", name: "Kyren Williams", team: "Los Angeles Rams", section: "Stars of the NFL Jerseys" },
  { number: "30", name: "Puka Nacua", team: "Los Angeles Rams", section: "Stars of the NFL Jerseys" },
  { number: "31", name: "De'Von Achane", team: "Miami Dolphins", section: "Stars of the NFL Jerseys" },
  { number: "32", name: "Tua Tagovailoa", team: "Miami Dolphins", section: "Stars of the NFL Jerseys" },
  { number: "33", name: "Justin Jefferson", team: "Minnesota Vikings", section: "Stars of the NFL Jerseys" },
  { number: "34", name: "Drake Maye", team: "New England Patriots", section: "Stars of the NFL Jerseys" },
  { number: "35", name: "Alvin Kamara", team: "New Orleans Saints", section: "Stars of the NFL Jerseys" },
  { number: "36", name: "Malik Nabers", team: "New York Giants", section: "Stars of the NFL Jerseys" },
  { number: "37", name: "Breece Hall", team: "New York Jets", section: "Stars of the NFL Jerseys" },
  { number: "38", name: "Garrett Wilson", team: "New York Jets", section: "Stars of the NFL Jerseys" },
  { number: "39", name: "Saquon Barkley", team: "Philadelphia Eagles", section: "Stars of the NFL Jerseys" },
  { number: "40", name: "A.J. Brown", team: "Philadelphia Eagles", section: "Stars of the NFL Jerseys" },
  { number: "41", name: "George Pickens", team: "Pittsburgh Steelers", section: "Stars of the NFL Jerseys" },
  { number: "42", name: "Christian McCaffrey", team: "San Francisco 49ers", section: "Stars of the NFL Jerseys" },
  { number: "43", name: "Brock Purdy", team: "San Francisco 49ers", section: "Stars of the NFL Jerseys" },
  { number: "44", name: "Jaxon Smith-Njigba", team: "Seattle Seahawks", section: "Stars of the NFL Jerseys" },
  { number: "45", name: "Kenneth Walker III", team: "Seattle Seahawks", section: "Stars of the NFL Jerseys" },
  { number: "46", name: "Baker Mayfield", team: "Tampa Bay Buccaneers", section: "Stars of the NFL Jerseys" },
  { number: "47", name: "Mike Evans", team: "Tampa Bay Buccaneers", section: "Stars of the NFL Jerseys" },
  { number: "48", name: "Calvin Ridley", team: "Tennessee Titans", section: "Stars of the NFL Jerseys" },
  { number: "49", name: "Jayden Daniels", team: "Washington Commanders", section: "Stars of the NFL Jerseys" },
  { number: "50", name: "Terry McLaurin", team: "Washington Commanders", section: "Stars of the NFL Jerseys" },

  // Zoned In Jerseys
  { number: "1", name: "Brian Robinson Jr.", team: "Washington Commanders", section: "Zoned In Jerseys" },
  { number: "2", name: "Austin Ekeler", team: "Washington Commanders", section: "Zoned In Jerseys" },
  { number: "3", name: "Jeffery Simmons", team: "Tennessee Titans", section: "Zoned In Jerseys" },
  { number: "4", name: "Tony Pollard", team: "Tennessee Titans", section: "Zoned In Jerseys" },
  { number: "5", name: "Bucky Irving", team: "Tampa Bay Buccaneers", section: "Zoned In Jerseys" },
  { number: "6", name: "Zach Charbonnet", team: "Seattle Seahawks", section: "Zoned In Jerseys" },
  { number: "7", name: "Devon Witherspoon", team: "Seattle Seahawks", section: "Zoned In Jerseys" },
  { number: "8", name: "Fred Warner", team: "San Francisco 49ers", section: "Zoned In Jerseys" },
  { number: "9", name: "George Kittle", team: "San Francisco 49ers", section: "Zoned In Jerseys" },
  { number: "10", name: "T.J. Watt", team: "Pittsburgh Steelers", section: "Zoned In Jerseys" },
  { number: "11", name: "Jaylen Warren", team: "Pittsburgh Steelers", section: "Zoned In Jerseys" },
  { number: "12", name: "Jalen Hurts", team: "Philadelphia Eagles", section: "Zoned In Jerseys" },
  { number: "13", name: "Cooper DeJean", team: "Philadelphia Eagles", section: "Zoned In Jerseys" },
  { number: "14", name: "Breece Hall", team: "New York Jets", section: "Zoned In Jerseys" },
  { number: "15", name: "Ahmad 'Sauce' Gardner", team: "New York Jets", section: "Zoned In Jerseys" },
  { number: "16", name: "Dexter Lawrence", team: "New York Giants", section: "Zoned In Jerseys" },
  { number: "17", name: "Tyrone Tracy Jr.", team: "New York Giants", section: "Zoned In Jerseys" },
  { number: "18", name: "Cameron Jordan", team: "New Orleans Saints", section: "Zoned In Jerseys" },
  { number: "19", name: "Taysom Hill", team: "New Orleans Saints", section: "Zoned In Jerseys" },
  { number: "20", name: "Rhamondre Stevenson", team: "New England Patriots", section: "Zoned In Jerseys" },
  { number: "21", name: "Jordan Addison", team: "Minnesota Vikings", section: "Zoned In Jerseys" },
  { number: "22", name: "Aaron Jones", team: "Minnesota Vikings", section: "Zoned In Jerseys" },
  { number: "23", name: "Tyreek Hill", team: "Miami Dolphins", section: "Zoned In Jerseys" },
  { number: "24", name: "Jalen Ramsey", team: "Miami Dolphins", section: "Zoned In Jerseys" },
  { number: "25", name: "Cooper Kupp", team: "Los Angeles Rams", section: "Zoned In Jerseys" },
  { number: "26", name: "Derwin James Jr.", team: "Los Angeles Chargers", section: "Zoned In Jerseys" },
  { number: "27", name: "J.K. Dobbins", team: "Los Angeles Chargers", section: "Zoned In Jerseys" },
  { number: "28", name: "Maxx Crosby", team: "Las Vegas Raiders", section: "Zoned In Jerseys" },
  { number: "29", name: "Chris Jones", team: "Kansas City Chiefs", section: "Zoned In Jerseys" },
  { number: "30", name: "Xavier Worthy", team: "Kansas City Chiefs", section: "Zoned In Jerseys" },
  { number: "31", name: "Tank Bigsby", team: "Jacksonville Jaguars", section: "Zoned In Jerseys" },
  { number: "32", name: "Trevor Lawrence", team: "Jacksonville Jaguars", section: "Zoned In Jerseys" },
  { number: "33", name: "Josh Downs", team: "Indianapolis Colts", section: "Zoned In Jerseys" },
  { number: "34", name: "Will Anderson Jr.", team: "Houston Texans", section: "Zoned In Jerseys" },
  { number: "35", name: "Stefon Diggs", team: "Houston Texans", section: "Zoned In Jerseys" },
  { number: "36", name: "Jayden Reed", team: "Green Bay Packers", section: "Zoned In Jerseys" },
  { number: "37", name: "Jared Goff", team: "Detroit Lions", section: "Zoned In Jerseys" },
  { number: "38", name: "David Montgomery", team: "Detroit Lions", section: "Zoned In Jerseys" },
  { number: "39", name: "Courtland Sutton", team: "Denver Broncos", section: "Zoned In Jerseys" },
  { number: "40", name: "Patrick Surtain II", team: "Denver Broncos", section: "Zoned In Jerseys" },
  { number: "41", name: "Micah Parsons", team: "Dallas Cowboys", section: "Zoned In Jerseys" },
  { number: "42", name: "Myles Garrett", team: "Cleveland Browns", section: "Zoned In Jerseys" },
  { number: "43", name: "Chase Brown", team: "Cincinnati Bengals", section: "Zoned In Jerseys" },
  { number: "44", name: "Trey Hendrickson", team: "Cincinnati Bengals", section: "Zoned In Jerseys" },
  { number: "45", name: "Keenan Allen", team: "Chicago Bears", section: "Zoned In Jerseys" },
  { number: "46", name: "James Cook", team: "Buffalo Bills", section: "Zoned In Jerseys" },
  { number: "47", name: "Zay Flowers", team: "Baltimore Ravens", section: "Zoned In Jerseys" },
  { number: "48", name: "Kyle Hamilton", team: "Baltimore Ravens", section: "Zoned In Jerseys" },
  { number: "49", name: "Michael Penix Jr.", team: "Atlanta Falcons", section: "Zoned In Jerseys" },
  { number: "50", name: "James Conner", team: "Arizona Cardinals", section: "Zoned In Jerseys" },
];
